{"total_count": 18, "incomplete_results": false, "items": [{"url": "https://api.github.com/repos/pyexcel/pyexcel-xlsx/issues/34", "repository_url": "https://api.github.com/repos/pyexcel/pyexcel-xlsx", "labels_url": "https://api.github.com/repos/pyexcel/pyexcel-xlsx/issues/34/labels{/name}", "comments_url": "https://api.github.com/repos/pyexcel/pyexcel-xlsx/issues/34/comments", "events_url": "https://api.github.com/repos/pyexcel/pyexcel-xlsx/issues/34/events", "html_url": "https://github.com/pyexcel/pyexcel-xlsx/issues/34", "id": 541471824, "node_id": "MDU6SXNzdWU1NDE0NzE4MjQ=", "number": 34, "title": "openpyxl newer versions", "user": {"login": "Thimxx", "id": 30757290, "node_id": "MDQ6VXNlcjMwNzU3Mjkw", "avatar_url": "https://avatars2.githubusercontent.com/u/30757290?v=4", "gravatar_id": "", "url": "https://api.github.com/users/Thimxx", "html_url": "https://github.com/Thimxx", "followers_url": "https://api.github.com/users/Thimxx/followers", "following_url": "https://api.github.com/users/Thimxx/following{/other_user}", "gists_url": "https://api.github.com/users/Thimxx/gists{/gist_id}", "starred_url": "https://api.github.com/users/Thimxx/starred{/owner}{/repo}", "subscriptions_url": "https://api.github.com/users/Thimxx/subscriptions", "organizations_url": "https://api.github.com/users/Thimxx/orgs", "repos_url": "https://api.github.com/users/Thimxx/repos", "events_url": "https://api.github.com/users/Thimxx/events{/privacy}", "received_events_url": "https://api.github.com/users/Thimxx/received_events", "type": "User", "site_admin": false}, "labels": [], "state": "closed", "locked": false, "assignee": null, "assignees": [], "milestone": null, "comments": 7, "created_at": "2019-12-22T16:24:05Z", "updated_at": "2019-12-28T20:25:51Z", "closed_at": "2019-12-28T14:24:02Z", "author_association": "NONE", "active_lock_reason": null, "body": "Openpyxl (https://pypi.org/project/openpyxl/) has created new versions. In the dependencies of the code it appears 2.6.0 as the most recent one which is 1 year old.\r\n\r\nIs it possible to update the dependency to the latest version (3.0.2)?", "performed_via_github_app": null, "score": 1.0}, {"url": "https://api.github.com/repos/pyexcel/pyexcel-xlsx/issues/32", "repository_url": "https://api.github.com/repos/pyexcel/pyexcel-xlsx", "labels_url": "https://api.github.com/repos/pyexcel/pyexcel-xlsx/issues/32/labels{/name}", "comments_url": "https://api.github.com/repos/pyexcel/pyexcel-xlsx/issues/32/comments", "events_url": "https://api.github.com/repos/pyexcel/pyexcel-xlsx/issues/32/events", "html_url": "https://github.com/pyexcel/pyexcel-xlsx/issues/32", "id": 427261247, "node_id": "MDU6SXNzdWU0MjcyNjEyNDc=", "number": 32, "title": "Packaging with PyInstaller not work even following the doc", "user": {"login": "xiazhibin", "id": 11945009, "node_id": "MDQ6VXNlcjExOTQ1MDA5", "avatar_url": "https://avatars0.githubusercontent.com/u/11945009?v=4", "gravatar_id": "", "url": "https://api.github.com/users/xiazhibin", "html_url": "https://github.com/xiazhibin", "followers_url": "https://api.github.com/users/xiazhibin/followers", "following_url": "https://api.github.com/users/xiazhibin/following{/other_user}", "gists_url": "https://api.github.com/users/xiazhibin/gists{/gist_id}", "starred_url": "https://api.github.com/users/xiazhibin/starred{/owner}{/repo}", "subscriptions_url": "https://api.github.com/users/xiazhibin/subscriptions", "organizations_url": "https://api.github.com/users/xiazhibin/orgs", "repos_url": "https://api.github.com/users/xiazhibin/repos", "events_url": "https://api.github.com/users/xiazhibin/events{/privacy}", "received_events_url": "https://api.github.com/users/xiazhibin/received_events", "type": "User", "site_admin": false}, "labels": [], "state": "closed", "locked": false, "assignee": null, "assignees": [], "milestone": null, "comments": 1, "created_at": "2019-03-30T08:53:13Z", "updated_at": "2019-03-30T11:34:32Z", "closed_at": "2019-03-30T08:57:08Z", "author_association": "NONE", "active_lock_reason": null, "body": "I add below command in PyInstaller:\r\n```\r\n--hidden-import pyexcel_xlsx\r\n--hidden-import pyexcel_xlsx.xlsxr\r\n--hidden-import pyexcel_xlsx.xlsxw\r\n``` \r\n\r\nHere is the PyInstaller output:\r\n```\r\n3446 INFO: Analyzing hidden import 'pyexcel_xlsx'\r\n3599 INFO: Analyzing hidden import 'pyexcel_xlsx.xlsxr'\r\n5194 INFO: Analyzing hidden import 'pyexcel_xlsx.xlsxw'\r\n```\r\n\r\nBut when I run, I still get\r\n`Please install one of these plugins for read data in 'xlsx': pyexcel-xls,pyexcel-xlsx`\r\n\r\nMac OS\r\nPython3.6.4\r\npyexcel (0.5.13)\r\npyexcel-io (0.5.16)\r\npyexcel-webio (0.1.4)\r\npyexcel-xlsx (0.5.7)\r\nPyInstaller (3.4)", "performed_via_github_app": null, "score": 1.0}, {"url": "https://api.github.com/repos/pyexcel/pyexcel-xlsx/issues/26", "repository_url": "https://api.github.com/repos/pyexcel/pyexcel-xlsx", "labels_url": "https://api.github.com/repos/pyexcel/pyexcel-xlsx/issues/26/labels{/name}", "comments_url": "https://api.github.com/repos/pyexcel/pyexcel-xlsx/issues/26/comments", "events_url": "https://api.github.com/repos/pyexcel/pyexcel-xlsx/issues/26/events", "html_url": "https://github.com/pyexcel/pyexcel-xlsx/issues/26", "id": 326837771, "node_id": "MDU6SXNzdWUzMjY4Mzc3NzE=", "number": 26, "title": "Detect an empty cell", "user": {"login": "colasbd", "id": 4303814, "node_id": "MDQ6VXNlcjQzMDM4MTQ=", "avatar_url": "https://avatars3.githubusercontent.com/u/4303814?v=4", "gravatar_id": "", "url": "https://api.github.com/users/colasbd", "html_url": "https://github.com/colasbd", "followers_url": "https://api.github.com/users/colasbd/followers", "following_url": "https://api.github.com/users/colasbd/following{/other_user}", "gists_url": "https://api.github.com/users/colasbd/gists{/gist_id}", "starred_url": "https://api.github.com/users/colasbd/starred{/owner}{/repo}", "subscriptions_url": "https://api.github.com/users/colasbd/subscriptions", "organizations_url": "https://api.github.com/users/colasbd/orgs", "repos_url": "https://api.github.com/users/colasbd/repos", "events_url": "https://api.github.com/users/colasbd/events{/privacy}", "received_events_url": "https://api.github.com/users/colasbd/received_events", "type": "User", "site_admin": false}, "labels": [], "state": "closed", "locked": false, "assignee": null, "assignees": [], "milestone": null, "comments": 0, "created_at": "2018-05-27T18:22:22Z", "updated_at": "2018-05-27T18:33:37Z", "closed_at": "2018-05-27T18:33:37Z", "author_association": "NONE", "active_lock_reason": null, "body": "I have imported my `.xlsx` file.\r\nThe empty cells are imported as `0`.\r\nIs it possible to detect these empty cells?\r\n\r\nThanks", "performed_via_github_app": null, "score": 1.0}, {"url": "https://api.github.com/repos/pyexcel/pyexcel-xlsx/issues/25", "repository_url": "https://api.github.com/repos/pyexcel/pyexcel-xlsx", "labels_url": "https://api.github.com/repos/pyexcel/pyexcel-xlsx/issues/25/labels{/name}", "comments_url": "https://api.github.com/repos/pyexcel/pyexcel-xlsx/issues/25/comments", "events_url": "https://api.github.com/repos/pyexcel/pyexcel-xlsx/issues/25/events", "html_url": "https://github.com/pyexcel/pyexcel-xlsx/issues/25", "id": 322102638, "node_id": "MDU6SXNzdWUzMjIxMDI2Mzg=", "number": 25, "title": "Excel Mac EPOC 1904 problem", "user": {"login": "chfw", "id": 4280312, "node_id": "MDQ6VXNlcjQyODAzMTI=", "avatar_url": "https://avatars0.githubusercontent.com/u/4280312?v=4", "gravatar_id": "", "url": "https://api.github.com/users/chfw", "html_url": "https://github.com/chfw", "followers_url": "https://api.github.com/users/chfw/followers", "following_url": "https://api.github.com/users/chfw/following{/other_user}", "gists_url": "https://api.github.com/users/chfw/gists{/gist_id}", "starred_url": "https://api.github.com/users/chfw/starred{/owner}{/repo}", "subscriptions_url": "https://api.github.com/users/chfw/subscriptions", "organizations_url": "https://api.github.com/users/chfw/orgs", "repos_url": "https://api.github.com/users/chfw/repos", "events_url": "https://api.github.com/users/chfw/events{/privacy}", "received_events_url": "https://api.github.com/users/chfw/received_events", "type": "User", "site_admin": false}, "labels": [], "state": "closed", "locked": false, "assignee": null, "assignees": [], "milestone": null, "comments": 3, "created_at": "2018-05-10T22:08:01Z", "updated_at": "2018-09-14T17:42:57Z", "closed_at": "2018-09-14T17:42:57Z", "author_association": "MEMBER", "active_lock_reason": null, "body": "https://github.com/pyexcel/pyexcel/issues/135\r\n\r\n\r\npointers:\r\n\r\nhttps://bitbucket.org/openpyxl/openpyxl/issues/558/saving-a-workbook-with-datetimedatetime-1\r\n\r\nhttps://groups.google.com/forum/#!topic/openpyxl-users/ZLW5ykPEZ5M", "performed_via_github_app": null, "score": 1.0}, {"url": "https://api.github.com/repos/pyexcel/pyexcel-xlsx/issues/22", "repository_url": "https://api.github.com/repos/pyexcel/pyexcel-xlsx", "labels_url": "https://api.github.com/repos/pyexcel/pyexcel-xlsx/issues/22/labels{/name}", "comments_url": "https://api.github.com/repos/pyexcel/pyexcel-xlsx/issues/22/comments", "events_url": "https://api.github.com/repos/pyexcel/pyexcel-xlsx/issues/22/events", "html_url": "https://github.com/pyexcel/pyexcel-xlsx/issues/22", "id": 282023479, "node_id": "MDU6SXNzdWUyODIwMjM0Nzk=", "number": 22, "title": "To detect merged cells in xlsx files", "user": {"login": "chfw", "id": 4280312, "node_id": "MDQ6VXNlcjQyODAzMTI=", "avatar_url": "https://avatars0.githubusercontent.com/u/4280312?v=4", "gravatar_id": "", "url": "https://api.github.com/users/chfw", "html_url": "https://github.com/chfw", "followers_url": "https://api.github.com/users/chfw/followers", "following_url": "https://api.github.com/users/chfw/following{/other_user}", "gists_url": "https://api.github.com/users/chfw/gists{/gist_id}", "starred_url": "https://api.github.com/users/chfw/starred{/owner}{/repo}", "subscriptions_url": "https://api.github.com/users/chfw/subscriptions", "organizations_url": "https://api.github.com/users/chfw/orgs", "repos_url": "https://api.github.com/users/chfw/repos", "events_url": "https://api.github.com/users/chfw/events{/privacy}", "received_events_url": "https://api.github.com/users/chfw/received_events", "type": "User", "site_admin": false}, "labels": [{"id": 153225493, "node_id": "MDU6TGFiZWwxNTMyMjU0OTM=", "url": "https://api.github.com/repos/pyexcel/pyexcel-xlsx/labels/enhancement", "name": "enhancement", "color": "84b6eb", "default": true, "description": null}], "state": "closed", "locked": false, "assignee": null, "assignees": [], "milestone": null, "comments": 1, "created_at": "2017-12-14T08:50:49Z", "updated_at": "2017-12-18T00:01:48Z", "closed_at": "2017-12-18T00:01:48Z", "author_association": "MEMBER", "active_lock_reason": null, "body": "Will implement this feature in this library\r\n\r\nreference: \r\n\r\nhttps://github.com/pyexcel/pyexcel-xls/issues/25\r\nhttps://github.com/pyexcel/pyexcel/issues/111\r\n", "performed_via_github_app": null, "score": 1.0}, {"url": "https://api.github.com/repos/pyexcel/pyexcel-xlsx/issues/20", "repository_url": "https://api.github.com/repos/pyexcel/pyexcel-xlsx", "labels_url": "https://api.github.com/repos/pyexcel/pyexcel-xlsx/issues/20/labels{/name}", "comments_url": "https://api.github.com/repos/pyexcel/pyexcel-xlsx/issues/20/comments", "events_url": "https://api.github.com/repos/pyexcel/pyexcel-xlsx/issues/20/events", "html_url": "https://github.com/pyexcel/pyexcel-xlsx/issues/20", "id": 270456682, "node_id": "MDU6SXNzdWUyNzA0NTY2ODI=", "number": 20, "title": "skip hidden columns and rows", "user": {"login": "chfw", "id": 4280312, "node_id": "MDQ6VXNlcjQyODAzMTI=", "avatar_url": "https://avatars0.githubusercontent.com/u/4280312?v=4", "gravatar_id": "", "url": "https://api.github.com/users/chfw", "html_url": "https://github.com/chfw", "followers_url": "https://api.github.com/users/chfw/followers", "following_url": "https://api.github.com/users/chfw/following{/other_user}", "gists_url": "https://api.github.com/users/chfw/gists{/gist_id}", "starred_url": "https://api.github.com/users/chfw/starred{/owner}{/repo}", "subscriptions_url": "https://api.github.com/users/chfw/subscriptions", "organizations_url": "https://api.github.com/users/chfw/orgs", "repos_url": "https://api.github.com/users/chfw/repos", "events_url": "https://api.github.com/users/chfw/events{/privacy}", "received_events_url": "https://api.github.com/users/chfw/received_events", "type": "User", "site_admin": false}, "labels": [{"id": 153225493, "node_id": "MDU6TGFiZWwxNTMyMjU0OTM=", "url": "https://api.github.com/repos/pyexcel/pyexcel-xlsx/labels/enhancement", "name": "enhancement", "color": "84b6eb", "default": true, "description": null}], "state": "closed", "locked": false, "assignee": null, "assignees": [], "milestone": null, "comments": 1, "created_at": "2017-11-01T21:20:35Z", "updated_at": "2017-11-01T21:22:07Z", "closed_at": "2017-11-01T21:22:07Z", "author_association": "MEMBER", "active_lock_reason": null, "body": "https://github.com/pyexcel/pyexcel/issues/53", "performed_via_github_app": null, "score": 1.0}, {"url": "https://api.github.com/repos/pyexcel/pyexcel-xlsx/issues/19", "repository_url": "https://api.github.com/repos/pyexcel/pyexcel-xlsx", "labels_url": "https://api.github.com/repos/pyexcel/pyexcel-xlsx/issues/19/labels{/name}", "comments_url": "https://api.github.com/repos/pyexcel/pyexcel-xlsx/issues/19/comments", "events_url": "https://api.github.com/repos/pyexcel/pyexcel-xlsx/issues/19/events", "html_url": "https://github.com/pyexcel/pyexcel-xlsx/issues/19", "id": 259441170, "node_id": "MDU6SXNzdWUyNTk0NDExNzA=", "number": 19, "title": "mechanism of dynamic load module, confilict with pyinstaller/cx_freeze's execution", "user": {"login": "kerneltravel", "id": 437879, "node_id": "MDQ6VXNlcjQzNzg3OQ==", "avatar_url": "https://avatars3.githubusercontent.com/u/437879?v=4", "gravatar_id": "", "url": "https://api.github.com/users/kerneltravel", "html_url": "https://github.com/kerneltravel", "followers_url": "https://api.github.com/users/kerneltravel/followers", "following_url": "https://api.github.com/users/kerneltravel/following{/other_user}", "gists_url": "https://api.github.com/users/kerneltravel/gists{/gist_id}", "starred_url": "https://api.github.com/users/kerneltravel/starred{/owner}{/repo}", "subscriptions_url": "https://api.github.com/users/kerneltravel/subscriptions", "organizations_url": "https://api.github.com/users/kerneltravel/orgs", "repos_url": "https://api.github.com/users/kerneltravel/repos", "events_url": "https://api.github.com/users/kerneltravel/events{/privacy}", "received_events_url": "https://api.github.com/users/kerneltravel/received_events", "type": "User", "site_admin": false}, "labels": [], "state": "closed", "locked": false, "assignee": null, "assignees": [], "milestone": null, "comments": 4, "created_at": "2017-09-21T09:59:05Z", "updated_at": "2017-09-21T15:06:18Z", "closed_at": "2017-09-21T11:37:02Z", "author_association": "NONE", "active_lock_reason": null, "body": "Hi,  I\u2018ve  test an pyqt GUI app with pyexcel_xlsx, my application is finally packaged as an exectuion file by pyinstaller OR cx_freeze,\r\n```\r\npyinstaller.exe  --distpath dist_pyinstaller  -F mainc.py \r\n```\r\nand get dist_pyinstaller\\mainc.exe  binary file.\r\nthe application can start well. but will fail when it's time to use pyexcel_xlsx functionility. \r\n\r\n```\r\nTraceback (most recent call last):\r\n  File \"pyexcel2csv_gui\\winmain\\winmain.py\", line 72, in  on_btnSelectExcelFileAndExport2Csv_clicked\r\n  File \"site-packages\\pyexcel_xlsx\\__init__.py\", line 38, in get_data\r\n  File \"site-packages\\pyexcel_io\\io.py\", line 65, in get_data\r\n  File \"site-packages\\pyexcel_io\\io.py\", line 83, in _get_data\r\n  File \"site-packages\\pyexcel_io\\io.py\", line 173, in load_data\r\n  File \"site-packages\\pyexcel_io\\plugins.py\", line 78, in get_a_plugin\r\n  File \"site-packages\\lml\\plugin.py\", line 275, in load_me_now\r\n  File \"site-packages\\lml\\plugin.py\", line 303, in dynamic_load_library\r\n  File \"site-packages\\lml\\utils.py\", line 60, in do_import_class\r\nImportError: No module named xlsxr\r\n```\r\nanlyse the source code \r\n```\r\ndef do_import_class(plugin_class):\r\n    \"\"\"dynamically import a class\"\"\"\r\n    try:\r\n        plugin_module_name = plugin_class.rsplit('.', 1)[0]\r\n        #print plugin_module_name,   plugin_class \r\n        #shows \"pyexcel_xlsx.xlsxr\"    , shows  \"pyexcel_xlsx.xlsxr.XLSXBook\"\r\n        plugin_module = __import__(plugin_module_name)\r\n        modules = plugin_class.split('.')\r\n        for module in modules[1:]:\r\n            plugin_module = getattr(plugin_module, module)\r\n        return plugin_module\r\n    except ImportError:\r\n        log.exception(\"Failed to import %s\", plugin_module_name)\r\n        raise\r\n```\r\npyexcel_xlsx has been installed by pip.  and \r\n```\r\nsite-packages\\pyexcel-xlsx\\xlsxr.py\r\n```\r\nfile exists.\r\n\r\nif directory call by CLI way\r\n```\r\npython.exe  mainc.py\r\n```\r\nto run same mainc.py script, ALL works ok.\r\nENV is python 2.7.9.\r\n\r\nso , seems the dynamic loading not works well in pyinstaller OR cx_freeze situation ? ", "performed_via_github_app": null, "score": 1.0}, {"url": "https://api.github.com/repos/pyexcel/pyexcel-xlsx/issues/18", "repository_url": "https://api.github.com/repos/pyexcel/pyexcel-xlsx", "labels_url": "https://api.github.com/repos/pyexcel/pyexcel-xlsx/issues/18/labels{/name}", "comments_url": "https://api.github.com/repos/pyexcel/pyexcel-xlsx/issues/18/comments", "events_url": "https://api.github.com/repos/pyexcel/pyexcel-xlsx/issues/18/events", "html_url": "https://github.com/pyexcel/pyexcel-xlsx/issues/18", "id": 252681031, "node_id": "MDU6SXNzdWUyNTI2ODEwMzE=", "number": 18, "title": "Cannot handle non-seekable io instance!", "user": {"login": "chfw", "id": 4280312, "node_id": "MDQ6VXNlcjQyODAzMTI=", "avatar_url": "https://avatars0.githubusercontent.com/u/4280312?v=4", "gravatar_id": "", "url": "https://api.github.com/users/chfw", "html_url": "https://github.com/chfw", "followers_url": "https://api.github.com/users/chfw/followers", "following_url": "https://api.github.com/users/chfw/following{/other_user}", "gists_url": "https://api.github.com/users/chfw/gists{/gist_id}", "starred_url": "https://api.github.com/users/chfw/starred{/owner}{/repo}", "subscriptions_url": "https://api.github.com/users/chfw/subscriptions", "organizations_url": "https://api.github.com/users/chfw/orgs", "repos_url": "https://api.github.com/users/chfw/repos", "events_url": "https://api.github.com/users/chfw/events{/privacy}", "received_events_url": "https://api.github.com/users/chfw/received_events", "type": "User", "site_admin": false}, "labels": [], "state": "closed", "locked": false, "assignee": null, "assignees": [], "milestone": null, "comments": 0, "created_at": "2017-08-24T17:54:51Z", "updated_at": "2017-08-24T17:55:57Z", "closed_at": "2017-08-24T17:55:57Z", "author_association": "MEMBER", "active_lock_reason": null, "body": "https://github.com/pyexcel/pyexcel-xls/issues/20", "performed_via_github_app": null, "score": 1.0}, {"url": "https://api.github.com/repos/pyexcel/pyexcel-xlsx/issues/17", "repository_url": "https://api.github.com/repos/pyexcel/pyexcel-xlsx", "labels_url": "https://api.github.com/repos/pyexcel/pyexcel-xlsx/issues/17/labels{/name}", "comments_url": "https://api.github.com/repos/pyexcel/pyexcel-xlsx/issues/17/comments", "events_url": "https://api.github.com/repos/pyexcel/pyexcel-xlsx/issues/17/events", "html_url": "https://github.com/pyexcel/pyexcel-xlsx/issues/17", "id": 234347095, "node_id": "MDU6SXNzdWUyMzQzNDcwOTU=", "number": 17, "title": "openpyxl leaks file handle in pypy", "user": {"login": "chfw", "id": 4280312, "node_id": "MDQ6VXNlcjQyODAzMTI=", "avatar_url": "https://avatars0.githubusercontent.com/u/4280312?v=4", "gravatar_id": "", "url": "https://api.github.com/users/chfw", "html_url": "https://github.com/chfw", "followers_url": "https://api.github.com/users/chfw/followers", "following_url": "https://api.github.com/users/chfw/following{/other_user}", "gists_url": "https://api.github.com/users/chfw/gists{/gist_id}", "starred_url": "https://api.github.com/users/chfw/starred{/owner}{/repo}", "subscriptions_url": "https://api.github.com/users/chfw/subscriptions", "organizations_url": "https://api.github.com/users/chfw/orgs", "repos_url": "https://api.github.com/users/chfw/repos", "events_url": "https://api.github.com/users/chfw/events{/privacy}", "received_events_url": "https://api.github.com/users/chfw/received_events", "type": "User", "site_admin": false}, "labels": [{"id": 153225497, "node_id": "MDU6TGFiZWwxNTMyMjU0OTc=", "url": "https://api.github.com/repos/pyexcel/pyexcel-xlsx/labels/wontfix", "name": "wontfix", "color": "ffffff", "default": true, "description": null}], "state": "closed", "locked": false, "assignee": null, "assignees": [], "milestone": null, "comments": 2, "created_at": "2017-06-07T21:22:49Z", "updated_at": "2018-08-05T22:29:43Z", "closed_at": "2018-08-05T22:29:42Z", "author_association": "MEMBER", "active_lock_reason": null, "body": "    $ python test.py\r\n    number of open file handles: 0\r\n    number of open file handles: 2\r\n    [popenfile(path='/Users/github/pyexcel-xlsx/test.xlsx', fd=5), popenfile(path='/Users/github/pyexcel-xlsx/test.xlsx', fd=6)]\r\n    Traceback (most recent call last):\r\n      File \"test.py\", line 14, in <module>\r\n        assert len(open_files_l1) == len(open_files_l2)\r\n    AssertionError\r\n    $ python\r\n    Python 2.7.13 (1aa2d8e03cdf, Mar 31 2017, 10:20:53)\r\n    [PyPy 5.7.1 with GCC 4.2.1 Compatible Apple LLVM 5.1 (clang-503.0.40)] on darwin\r\n    Type \"help\", \"copyright\", \"credits\" or \"license\" for more information.\r\n\r\nreference: https://github.com/pyexcel/pyexcel-xlsx/issues/14", "performed_via_github_app": null, "score": 1.0}, {"url": "https://api.github.com/repos/pyexcel/pyexcel-xlsx/issues/14", "repository_url": "https://api.github.com/repos/pyexcel/pyexcel-xlsx", "labels_url": "https://api.github.com/repos/pyexcel/pyexcel-xlsx/issues/14/labels{/name}", "comments_url": "https://api.github.com/repos/pyexcel/pyexcel-xlsx/issues/14/comments", "events_url": "https://api.github.com/repos/pyexcel/pyexcel-xlsx/issues/14/events", "html_url": "https://github.com/pyexcel/pyexcel-xlsx/issues/14", "id": 226130302, "node_id": "MDU6SXNzdWUyMjYxMzAzMDI=", "number": 14, "title": "file descriptors are not closed", "user": {"login": "benoit-pierre", "id": 5104286, "node_id": "MDQ6VXNlcjUxMDQyODY=", "avatar_url": "https://avatars1.githubusercontent.com/u/5104286?v=4", "gravatar_id": "", "url": "https://api.github.com/users/benoit-pierre", "html_url": "https://github.com/benoit-pierre", "followers_url": "https://api.github.com/users/benoit-pierre/followers", "following_url": "https://api.github.com/users/benoit-pierre/following{/other_user}", "gists_url": "https://api.github.com/users/benoit-pierre/gists{/gist_id}", "starred_url": "https://api.github.com/users/benoit-pierre/starred{/owner}{/repo}", "subscriptions_url": "https://api.github.com/users/benoit-pierre/subscriptions", "organizations_url": "https://api.github.com/users/benoit-pierre/orgs", "repos_url": "https://api.github.com/users/benoit-pierre/repos", "events_url": "https://api.github.com/users/benoit-pierre/events{/privacy}", "received_events_url": "https://api.github.com/users/benoit-pierre/received_events", "type": "User", "site_admin": false}, "labels": [], "state": "closed", "locked": false, "assignee": null, "assignees": [], "milestone": null, "comments": 9, "created_at": "2017-05-03T22:14:34Z", "updated_at": "2017-06-07T21:39:25Z", "closed_at": "2017-06-07T21:39:25Z", "author_association": "CONTRIBUTOR", "active_lock_reason": null, "body": "For example, when running the following code on Linux:\r\n\r\n```python\r\nimport os\r\n\r\nimport pyexcel\r\n\r\npyexcel.get_book_dict(file_name='test.xlsx')\r\n\r\nfd_dir = '/proc/%u/fd' % os.getpid()\r\nfor fd_name in os.listdir(fd_dir):\r\n    print(fd_name, '-> ', end='')\r\n    try:\r\n        print(os.readlink('%s/%s' % (fd_dir, fd_name)))\r\n    except FileNotFoundError:\r\n        print()\r\n```\r\n\r\nThe last file descriptor open point to `test.xlsx`.\r\n\r\nBeside the file descriptor leak, this is really problematic in Windows, as it make it impossible to concurrently modify the spreadsheet in Office when it has been read in another (still running) application.", "performed_via_github_app": null, "score": 1.0}, {"url": "https://api.github.com/repos/pyexcel/pyexcel-xlsx/issues/13", "repository_url": "https://api.github.com/repos/pyexcel/pyexcel-xlsx", "labels_url": "https://api.github.com/repos/pyexcel/pyexcel-xlsx/issues/13/labels{/name}", "comments_url": "https://api.github.com/repos/pyexcel/pyexcel-xlsx/issues/13/comments", "events_url": "https://api.github.com/repos/pyexcel/pyexcel-xlsx/issues/13/events", "html_url": "https://github.com/pyexcel/pyexcel-xlsx/issues/13", "id": 196735861, "node_id": "MDU6SXNzdWUxOTY3MzU4NjE=", "number": 13, "title": "performance concern over sheet.max_column", "user": {"login": "chfw", "id": 4280312, "node_id": "MDQ6VXNlcjQyODAzMTI=", "avatar_url": "https://avatars0.githubusercontent.com/u/4280312?v=4", "gravatar_id": "", "url": "https://api.github.com/users/chfw", "html_url": "https://github.com/chfw", "followers_url": "https://api.github.com/users/chfw/followers", "following_url": "https://api.github.com/users/chfw/following{/other_user}", "gists_url": "https://api.github.com/users/chfw/gists{/gist_id}", "starred_url": "https://api.github.com/users/chfw/starred{/owner}{/repo}", "subscriptions_url": "https://api.github.com/users/chfw/subscriptions", "organizations_url": "https://api.github.com/users/chfw/orgs", "repos_url": "https://api.github.com/users/chfw/repos", "events_url": "https://api.github.com/users/chfw/events{/privacy}", "received_events_url": "https://api.github.com/users/chfw/received_events", "type": "User", "site_admin": false}, "labels": [], "state": "closed", "locked": false, "assignee": null, "assignees": [], "milestone": null, "comments": 0, "created_at": "2016-12-20T17:45:44Z", "updated_at": "2016-12-20T17:47:56Z", "closed_at": "2016-12-20T17:47:56Z", "author_association": "MEMBER", "active_lock_reason": null, "body": "An answer to this is [read_only mode in openpyxl](https://github.com/pyexcel/pyexcel-io/pull/25). \r\n\r\nreference: https://github.com/pyexcel/pyexcel-io/pull/25", "performed_via_github_app": null, "score": 1.0}, {"url": "https://api.github.com/repos/pyexcel/pyexcel-xlsx/issues/12", "repository_url": "https://api.github.com/repos/pyexcel/pyexcel-xlsx", "labels_url": "https://api.github.com/repos/pyexcel/pyexcel-xlsx/issues/12/labels{/name}", "comments_url": "https://api.github.com/repos/pyexcel/pyexcel-xlsx/issues/12/comments", "events_url": "https://api.github.com/repos/pyexcel/pyexcel-xlsx/issues/12/events", "html_url": "https://github.com/pyexcel/pyexcel-xlsx/issues/12", "id": 186486135, "node_id": "MDU6SXNzdWUxODY0ODYxMzU=", "number": 12, "title": "UserWarning: Using a coordinate with ws.cell is deprecated. Use ws[coordinate]", "user": {"login": "chfw", "id": 4280312, "node_id": "MDQ6VXNlcjQyODAzMTI=", "avatar_url": "https://avatars0.githubusercontent.com/u/4280312?v=4", "gravatar_id": "", "url": "https://api.github.com/users/chfw", "html_url": "https://github.com/chfw", "followers_url": "https://api.github.com/users/chfw/followers", "following_url": "https://api.github.com/users/chfw/following{/other_user}", "gists_url": "https://api.github.com/users/chfw/gists{/gist_id}", "starred_url": "https://api.github.com/users/chfw/starred{/owner}{/repo}", "subscriptions_url": "https://api.github.com/users/chfw/subscriptions", "organizations_url": "https://api.github.com/users/chfw/orgs", "repos_url": "https://api.github.com/users/chfw/repos", "events_url": "https://api.github.com/users/chfw/events{/privacy}", "received_events_url": "https://api.github.com/users/chfw/received_events", "type": "User", "site_admin": false}, "labels": [], "state": "closed", "locked": false, "assignee": null, "assignees": [], "milestone": null, "comments": 0, "created_at": "2016-11-01T08:55:17Z", "updated_at": "2016-11-01T08:58:20Z", "closed_at": "2016-11-01T08:58:20Z", "author_association": "MEMBER", "active_lock_reason": null, "body": "To remove the warning. \r\n\r\nreference: https://github.com/pyexcel/pyexcel/issues/62", "performed_via_github_app": null, "score": 1.0}, {"url": "https://api.github.com/repos/pyexcel/pyexcel-xlsx/issues/11", "repository_url": "https://api.github.com/repos/pyexcel/pyexcel-xlsx", "labels_url": "https://api.github.com/repos/pyexcel/pyexcel-xlsx/issues/11/labels{/name}", "comments_url": "https://api.github.com/repos/pyexcel/pyexcel-xlsx/issues/11/comments", "events_url": "https://api.github.com/repos/pyexcel/pyexcel-xlsx/issues/11/events", "html_url": "https://github.com/pyexcel/pyexcel-xlsx/issues/11", "id": 173327209, "node_id": "MDU6SXNzdWUxNzMzMjcyMDk=", "number": 11, "title": "use optimized writer for writing out xlsx so as to support large files", "user": {"login": "chfw", "id": 4280312, "node_id": "MDQ6VXNlcjQyODAzMTI=", "avatar_url": "https://avatars0.githubusercontent.com/u/4280312?v=4", "gravatar_id": "", "url": "https://api.github.com/users/chfw", "html_url": "https://github.com/chfw", "followers_url": "https://api.github.com/users/chfw/followers", "following_url": "https://api.github.com/users/chfw/following{/other_user}", "gists_url": "https://api.github.com/users/chfw/gists{/gist_id}", "starred_url": "https://api.github.com/users/chfw/starred{/owner}{/repo}", "subscriptions_url": "https://api.github.com/users/chfw/subscriptions", "organizations_url": "https://api.github.com/users/chfw/orgs", "repos_url": "https://api.github.com/users/chfw/repos", "events_url": "https://api.github.com/users/chfw/events{/privacy}", "received_events_url": "https://api.github.com/users/chfw/received_events", "type": "User", "site_admin": false}, "labels": [{"id": 153225493, "node_id": "MDU6TGFiZWwxNTMyMjU0OTM=", "url": "https://api.github.com/repos/pyexcel/pyexcel-xlsx/labels/enhancement", "name": "enhancement", "color": "84b6eb", "default": true, "description": null}], "state": "closed", "locked": false, "assignee": null, "assignees": [], "milestone": null, "comments": 4, "created_at": "2016-08-25T22:35:58Z", "updated_at": "2016-08-26T21:09:47Z", "closed_at": "2016-08-25T22:36:52Z", "author_association": "MEMBER", "active_lock_reason": null, "body": "optimized writer is a better fit for pyexcel-xlsx.\n\ntrigger: https://github.com/pyexcel/Flask-Excel/issues/16\nhint: http://stackoverflow.com/questions/21328884/openpyxl-writing-large-excel-files-with-python\ndoc: http://openpyxl.readthedocs.io/en/2.3.3/optimized.html\n", "performed_via_github_app": null, "score": 1.0}, {"url": "https://api.github.com/repos/pyexcel/pyexcel-xlsx/issues/10", "repository_url": "https://api.github.com/repos/pyexcel/pyexcel-xlsx", "labels_url": "https://api.github.com/repos/pyexcel/pyexcel-xlsx/issues/10/labels{/name}", "comments_url": "https://api.github.com/repos/pyexcel/pyexcel-xlsx/issues/10/comments", "events_url": "https://api.github.com/repos/pyexcel/pyexcel-xlsx/issues/10/events", "html_url": "https://github.com/pyexcel/pyexcel-xlsx/issues/10", "id": 166498223, "node_id": "MDU6SXNzdWUxNjY0OTgyMjM=", "number": 10, "title": "Python 2.7 Support Issue", "user": {"login": "AhnSeongHyun", "id": 1414228, "node_id": "MDQ6VXNlcjE0MTQyMjg=", "avatar_url": "https://avatars3.githubusercontent.com/u/1414228?v=4", "gravatar_id": "", "url": "https://api.github.com/users/AhnSeongHyun", "html_url": "https://github.com/AhnSeongHyun", "followers_url": "https://api.github.com/users/AhnSeongHyun/followers", "following_url": "https://api.github.com/users/AhnSeongHyun/following{/other_user}", "gists_url": "https://api.github.com/users/AhnSeongHyun/gists{/gist_id}", "starred_url": "https://api.github.com/users/AhnSeongHyun/starred{/owner}{/repo}", "subscriptions_url": "https://api.github.com/users/AhnSeongHyun/subscriptions", "organizations_url": "https://api.github.com/users/AhnSeongHyun/orgs", "repos_url": "https://api.github.com/users/AhnSeongHyun/repos", "events_url": "https://api.github.com/users/AhnSeongHyun/events{/privacy}", "received_events_url": "https://api.github.com/users/AhnSeongHyun/received_events", "type": "User", "site_admin": false}, "labels": [], "state": "closed", "locked": false, "assignee": null, "assignees": [], "milestone": null, "comments": 1, "created_at": "2016-07-20T05:25:45Z", "updated_at": "2016-07-21T08:55:32Z", "closed_at": "2016-07-21T08:55:32Z", "author_association": "NONE", "active_lock_reason": null, "body": "# $ pip install pyexcel-xlsx\n\nDownloading/unpacking pyexcel-xlsx\n  Downloading pyexcel-xlsx-0.2.1.zip\n  Running setup.py (path:/tmp/pip_build_root/pyexcel-xlsx/setup.py) egg_info for package pyexcel-xlsx\n\nDownloading/unpacking openpyxl>=2.2.2 (from pyexcel-xlsx)\n  Downloading openpyxl-2.3.5.tar.gz (141kB): 141kB downloaded\n  Running setup.py (path:/tmp/pip_build_root/openpyxl/setup.py) egg_info for package openpyxl\n\n```\nno previously-included directories found matching 'openpyxl/tests'\nno previously-included directories found matching 'openpyxl/sample'\nno previously-included directories found matching 'openpyxl/benchmarks'\nno previously-included directories found matching 'openpyxl/develop'\nwarning: no previously-included files matching 'test_*.py' found under directory 'openpyxl'\nwarning: no previously-included files matching 'tests/*.py' found under directory 'openpyxl'\n```\n\nDownloading/unpacking pyexcel-io>=0.1.0 (from pyexcel-xlsx)\n  Downloading pyexcel-io-0.2.1.zip\n  Running setup.py (path:/tmp/pip_build_root/pyexcel-io/setup.py) egg_info for package pyexcel-io\n    error in pyexcel-io setup command: Invalid environment marker: python_version<\"2.7\"\n    Complete output from command python setup.py egg_info:\n    error in pyexcel-io setup command: Invalid environment marker: python_version<\"2.7\"\n\n---\n", "performed_via_github_app": null, "score": 1.0}, {"url": "https://api.github.com/repos/pyexcel/pyexcel-xlsx/issues/9", "repository_url": "https://api.github.com/repos/pyexcel/pyexcel-xlsx", "labels_url": "https://api.github.com/repos/pyexcel/pyexcel-xlsx/issues/9/labels{/name}", "comments_url": "https://api.github.com/repos/pyexcel/pyexcel-xlsx/issues/9/comments", "events_url": "https://api.github.com/repos/pyexcel/pyexcel-xlsx/issues/9/events", "html_url": "https://github.com/pyexcel/pyexcel-xlsx/issues/9", "id": 162220033, "node_id": "MDU6SXNzdWUxNjIyMjAwMzM=", "number": 9, "title": "ImportError: No module named 'texttable'", "user": {"login": "GauravIITR17", "id": 15018791, "node_id": "MDQ6VXNlcjE1MDE4Nzkx", "avatar_url": "https://avatars1.githubusercontent.com/u/15018791?v=4", "gravatar_id": "", "url": "https://api.github.com/users/GauravIITR17", "html_url": "https://github.com/GauravIITR17", "followers_url": "https://api.github.com/users/GauravIITR17/followers", "following_url": "https://api.github.com/users/GauravIITR17/following{/other_user}", "gists_url": "https://api.github.com/users/GauravIITR17/gists{/gist_id}", "starred_url": "https://api.github.com/users/GauravIITR17/starred{/owner}{/repo}", "subscriptions_url": "https://api.github.com/users/GauravIITR17/subscriptions", "organizations_url": "https://api.github.com/users/GauravIITR17/orgs", "repos_url": "https://api.github.com/users/GauravIITR17/repos", "events_url": "https://api.github.com/users/GauravIITR17/events{/privacy}", "received_events_url": "https://api.github.com/users/GauravIITR17/received_events", "type": "User", "site_admin": false}, "labels": [], "state": "closed", "locked": false, "assignee": null, "assignees": [], "milestone": null, "comments": 12, "created_at": "2016-06-24T19:58:42Z", "updated_at": "2016-08-31T19:41:36Z", "closed_at": "2016-08-31T19:41:36Z", "author_association": "NONE", "active_lock_reason": null, "body": "Hey I want to merge multiple csv files into one excel file.\nI used this code.\n\nfrom pyexcel.cookbook import merge_all_to_a_book\nimport pyexcel.ext.xlsx # needed to support xlsx format, pip install pyexcel-xlsx\nimport glob\n\nmerge_all_to_a_book(glob.glob(\"*.csv\"), \"output.xlsx\")\n\n---\n\nAnd I am getting this error\n\n```\nfrom pyexcel.cookbook import merge_all_to_a_book\n```\n\n  File \"C:\\Python34\\lib\\site-packages\\pyexcel__init__.py\", line 12, in <module>\n    from .book import Book\n  File \"C:\\Python34\\lib\\site-packages\\pyexcel\\book.py\", line 11, in <module>\n    from .sheets import Sheet, SheetStream\n  File \"C:\\Python34\\lib\\site-packages\\pyexcel\\sheets__init__.py\", line 10, in <module>\n    from .sheet import (\n  File \"C:\\Python34\\lib\\site-packages\\pyexcel\\sheets\\sheet.py\", line 11, in <module>\n    from .nominablesheet import NominableSheet\n  File \"C:\\Python34\\lib\\site-packages\\pyexcel\\sheets\\nominablesheet.py\", line 10, in <module>\n    from texttable import Texttable\nImportError: No module named 'texttable'\n\n", "performed_via_github_app": null, "score": 1.0}, {"url": "https://api.github.com/repos/pyexcel/pyexcel-xlsx/issues/8", "repository_url": "https://api.github.com/repos/pyexcel/pyexcel-xlsx", "labels_url": "https://api.github.com/repos/pyexcel/pyexcel-xlsx/issues/8/labels{/name}", "comments_url": "https://api.github.com/repos/pyexcel/pyexcel-xlsx/issues/8/comments", "events_url": "https://api.github.com/repos/pyexcel/pyexcel-xlsx/issues/8/events", "html_url": "https://github.com/pyexcel/pyexcel-xlsx/issues/8", "id": 158312086, "node_id": "MDU6SXNzdWUxNTgzMTIwODY=", "number": 8, "title": "Support hidden sheets", "user": {"login": "chfw", "id": 4280312, "node_id": "MDQ6VXNlcjQyODAzMTI=", "avatar_url": "https://avatars0.githubusercontent.com/u/4280312?v=4", "gravatar_id": "", "url": "https://api.github.com/users/chfw", "html_url": "https://github.com/chfw", "followers_url": "https://api.github.com/users/chfw/followers", "following_url": "https://api.github.com/users/chfw/following{/other_user}", "gists_url": "https://api.github.com/users/chfw/gists{/gist_id}", "starred_url": "https://api.github.com/users/chfw/starred{/owner}{/repo}", "subscriptions_url": "https://api.github.com/users/chfw/subscriptions", "organizations_url": "https://api.github.com/users/chfw/orgs", "repos_url": "https://api.github.com/users/chfw/repos", "events_url": "https://api.github.com/users/chfw/events{/privacy}", "received_events_url": "https://api.github.com/users/chfw/received_events", "type": "User", "site_admin": false}, "labels": [], "state": "closed", "locked": false, "assignee": null, "assignees": [], "milestone": null, "comments": 0, "created_at": "2016-06-03T08:01:10Z", "updated_at": "2016-07-12T17:11:40Z", "closed_at": "2016-07-12T17:11:40Z", "author_association": "MEMBER", "active_lock_reason": null, "body": "the use case is to not read the hidden sheets.\n\nhttps://github.com/pyexcel/pyexcel/issues/21\n", "performed_via_github_app": null, "score": 1.0}, {"url": "https://api.github.com/repos/pyexcel/pyexcel-xlsx/issues/2", "repository_url": "https://api.github.com/repos/pyexcel/pyexcel-xlsx", "labels_url": "https://api.github.com/repos/pyexcel/pyexcel-xlsx/issues/2/labels{/name}", "comments_url": "https://api.github.com/repos/pyexcel/pyexcel-xlsx/issues/2/comments", "events_url": "https://api.github.com/repos/pyexcel/pyexcel-xlsx/issues/2/events", "html_url": "https://github.com/pyexcel/pyexcel-xlsx/issues/2", "id": 113854868, "node_id": "MDU6SXNzdWUxMTM4NTQ4Njg=", "number": 2, "title": "ValueError: More than 4094 XFs (styles)    # when writing to xls", "user": {"login": "rlatowicz", "id": 12681122, "node_id": "MDQ6VXNlcjEyNjgxMTIy", "avatar_url": "https://avatars0.githubusercontent.com/u/12681122?v=4", "gravatar_id": "", "url": "https://api.github.com/users/rlatowicz", "html_url": "https://github.com/rlatowicz", "followers_url": "https://api.github.com/users/rlatowicz/followers", "following_url": "https://api.github.com/users/rlatowicz/following{/other_user}", "gists_url": "https://api.github.com/users/rlatowicz/gists{/gist_id}", "starred_url": "https://api.github.com/users/rlatowicz/starred{/owner}{/repo}", "subscriptions_url": "https://api.github.com/users/rlatowicz/subscriptions", "organizations_url": "https://api.github.com/users/rlatowicz/orgs", "repos_url": "https://api.github.com/users/rlatowicz/repos", "events_url": "https://api.github.com/users/rlatowicz/events{/privacy}", "received_events_url": "https://api.github.com/users/rlatowicz/received_events", "type": "User", "site_admin": false}, "labels": [], "state": "closed", "locked": false, "assignee": null, "assignees": [], "milestone": null, "comments": 0, "created_at": "2015-10-28T15:57:57Z", "updated_at": "2015-10-28T16:12:55Z", "closed_at": "2015-10-28T16:00:09Z", "author_association": "NONE", "active_lock_reason": null, "body": "posted in pyexcel-xls\n", "performed_via_github_app": null, "score": 1.0}, {"url": "https://api.github.com/repos/pyexcel/pyexcel-xlsx/issues/1", "repository_url": "https://api.github.com/repos/pyexcel/pyexcel-xlsx", "labels_url": "https://api.github.com/repos/pyexcel/pyexcel-xlsx/issues/1/labels{/name}", "comments_url": "https://api.github.com/repos/pyexcel/pyexcel-xlsx/issues/1/comments", "events_url": "https://api.github.com/repos/pyexcel/pyexcel-xlsx/issues/1/events", "html_url": "https://github.com/pyexcel/pyexcel-xlsx/issues/1", "id": 110744980, "node_id": "MDU6SXNzdWUxMTA3NDQ5ODA=", "number": 1, "title": "Excessive columns trailing each row", "user": {"login": "chfw", "id": 4280312, "node_id": "MDQ6VXNlcjQyODAzMTI=", "avatar_url": "https://avatars0.githubusercontent.com/u/4280312?v=4", "gravatar_id": "", "url": "https://api.github.com/users/chfw", "html_url": "https://github.com/chfw", "followers_url": "https://api.github.com/users/chfw/followers", "following_url": "https://api.github.com/users/chfw/following{/other_user}", "gists_url": "https://api.github.com/users/chfw/gists{/gist_id}", "starred_url": "https://api.github.com/users/chfw/starred{/owner}{/repo}", "subscriptions_url": "https://api.github.com/users/chfw/subscriptions", "organizations_url": "https://api.github.com/users/chfw/orgs", "repos_url": "https://api.github.com/users/chfw/repos", "events_url": "https://api.github.com/users/chfw/events{/privacy}", "received_events_url": "https://api.github.com/users/chfw/received_events", "type": "User", "site_admin": false}, "labels": [], "state": "closed", "locked": false, "assignee": null, "assignees": [], "milestone": null, "comments": 0, "created_at": "2015-10-09T22:18:11Z", "updated_at": "2015-10-09T22:18:49Z", "closed_at": "2015-10-09T22:18:49Z", "author_association": "MEMBER", "active_lock_reason": null, "body": "This issue was escalated from https://github.com/chfw/pyexcel-ods/issues/4. And it is also found in xlsx reader too.\n", "performed_via_github_app": null, "score": 1.0}]}