{"total_count": 60, "incomplete_results": false, "items": [{"url": "https://api.github.com/repos/buriy/python-readability/issues/149", "repository_url": "https://api.github.com/repos/buriy/python-readability", "labels_url": "https://api.github.com/repos/buriy/python-readability/issues/149/labels{/name}", "comments_url": "https://api.github.com/repos/buriy/python-readability/issues/149/comments", "events_url": "https://api.github.com/repos/buriy/python-readability/issues/149/events", "html_url": "https://github.com/buriy/python-readability/issues/149", "id": 650775109, "node_id": "MDU6SXNzdWU2NTA3NzUxMDk=", "number": 149, "title": "New release to PyPI?", "user": {"login": "raharrison", "id": 2327200, "node_id": "MDQ6VXNlcjIzMjcyMDA=", "avatar_url": "https://avatars3.githubusercontent.com/u/2327200?v=4", "gravatar_id": "", "url": "https://api.github.com/users/raharrison", "html_url": "https://github.com/raharrison", "followers_url": "https://api.github.com/users/raharrison/followers", "following_url": "https://api.github.com/users/raharrison/following{/other_user}", "gists_url": "https://api.github.com/users/raharrison/gists{/gist_id}", "starred_url": "https://api.github.com/users/raharrison/starred{/owner}{/repo}", "subscriptions_url": "https://api.github.com/users/raharrison/subscriptions", "organizations_url": "https://api.github.com/users/raharrison/orgs", "repos_url": "https://api.github.com/users/raharrison/repos", "events_url": "https://api.github.com/users/raharrison/events{/privacy}", "received_events_url": "https://api.github.com/users/raharrison/received_events", "type": "User", "site_admin": false}, "labels": [], "state": "closed", "locked": false, "assignee": null, "assignees": [], "milestone": null, "comments": 2, "created_at": "2020-07-03T21:46:13Z", "updated_at": "2020-07-04T02:35:34Z", "closed_at": "2020-07-04T02:35:34Z", "author_association": "NONE", "active_lock_reason": null, "body": "Any plans on releasing a new version to PyPI? The changelog mentions v0.8.1 but the latest available release is still 0.7.1.", "performed_via_github_app": null, "score": 1.0}, {"url": "https://api.github.com/repos/buriy/python-readability/issues/141", "repository_url": "https://api.github.com/repos/buriy/python-readability", "labels_url": "https://api.github.com/repos/buriy/python-readability/issues/141/labels{/name}", "comments_url": "https://api.github.com/repos/buriy/python-readability/issues/141/comments", "events_url": "https://api.github.com/repos/buriy/python-readability/issues/141/events", "html_url": "https://github.com/buriy/python-readability/issues/141", "id": 571354549, "node_id": "MDU6SXNzdWU1NzEzNTQ1NDk=", "number": 141, "title": "please replace log.info() with log.debug() in Document.select_best_candidates()", "user": {"login": "yevgenpa", "id": 44113339, "node_id": "MDQ6VXNlcjQ0MTEzMzM5", "avatar_url": "https://avatars1.githubusercontent.com/u/44113339?v=4", "gravatar_id": "", "url": "https://api.github.com/users/yevgenpa", "html_url": "https://github.com/yevgenpa", "followers_url": "https://api.github.com/users/yevgenpa/followers", "following_url": "https://api.github.com/users/yevgenpa/following{/other_user}", "gists_url": "https://api.github.com/users/yevgenpa/gists{/gist_id}", "starred_url": "https://api.github.com/users/yevgenpa/starred{/owner}{/repo}", "subscriptions_url": "https://api.github.com/users/yevgenpa/subscriptions", "organizations_url": "https://api.github.com/users/yevgenpa/orgs", "repos_url": "https://api.github.com/users/yevgenpa/repos", "events_url": "https://api.github.com/users/yevgenpa/events{/privacy}", "received_events_url": "https://api.github.com/users/yevgenpa/received_events", "type": "User", "site_admin": false}, "labels": [], "state": "closed", "locked": false, "assignee": null, "assignees": [], "milestone": null, "comments": 1, "created_at": "2020-02-26T13:17:37Z", "updated_at": "2020-05-24T16:55:21Z", "closed_at": "2020-05-24T16:55:20Z", "author_association": "NONE", "active_lock_reason": null, "body": "I guess it should be log.debug() - that would make more sense for me.\r\n\r\nsee the following peace of code: \r\n```\r\nfor candidate in sorted_candidates[:5]:\r\n    elem = candidate['elem']\r\n\r\n    # log.debug() instead of log.info()\r\n    log.info(\"Top 5 : %6.3f %s\" % (  \r\n        candidate['content_score'],\r\n        describe(elem)))\r\n```\r\n", "performed_via_github_app": null, "score": 1.0}, {"url": "https://api.github.com/repos/buriy/python-readability/issues/125", "repository_url": "https://api.github.com/repos/buriy/python-readability", "labels_url": "https://api.github.com/repos/buriy/python-readability/issues/125/labels{/name}", "comments_url": "https://api.github.com/repos/buriy/python-readability/issues/125/comments", "events_url": "https://api.github.com/repos/buriy/python-readability/issues/125/events", "html_url": "https://github.com/buriy/python-readability/issues/125", "id": 543418807, "node_id": "MDU6SXNzdWU1NDM0MTg4MDc=", "number": 125, "title": "Issue with self-closing tags", "user": {"login": "azmeuk", "id": 60163, "node_id": "MDQ6VXNlcjYwMTYz", "avatar_url": "https://avatars1.githubusercontent.com/u/60163?v=4", "gravatar_id": "", "url": "https://api.github.com/users/azmeuk", "html_url": "https://github.com/azmeuk", "followers_url": "https://api.github.com/users/azmeuk/followers", "following_url": "https://api.github.com/users/azmeuk/following{/other_user}", "gists_url": "https://api.github.com/users/azmeuk/gists{/gist_id}", "starred_url": "https://api.github.com/users/azmeuk/starred{/owner}{/repo}", "subscriptions_url": "https://api.github.com/users/azmeuk/subscriptions", "organizations_url": "https://api.github.com/users/azmeuk/orgs", "repos_url": "https://api.github.com/users/azmeuk/repos", "events_url": "https://api.github.com/users/azmeuk/events{/privacy}", "received_events_url": "https://api.github.com/users/azmeuk/received_events", "type": "User", "site_admin": false}, "labels": [], "state": "closed", "locked": false, "assignee": null, "assignees": [], "milestone": null, "comments": 1, "created_at": "2019-12-29T14:23:54Z", "updated_at": "2019-12-30T11:43:47Z", "closed_at": "2019-12-30T11:37:56Z", "author_association": "NONE", "active_lock_reason": null, "body": "I encountered an issue with the [Rust-lang blog](https://blog.rust-lang.org/2019/12/19/Rust-1.40.0.html). There are empty `<a>` tags that are used as anchors:\r\n\r\n```html\r\n<h2><a class=\"anchor\" href=\"https://blog.rust-lang.org/2019/12/19/Rust-1.40.0.html#whats-in-1.40.0-stable\" id=\"whats-in-1.40.0-stable\"></a>What's in 1.40.0 stable</h2>\r\n```\r\n\r\nAs the tag is empty, readability transforms it in a self closed tag `<a/>`:\r\n\r\n```python\r\nimport readability\r\n>>> readability.Document('<h2><a href=\"#\"></a>foobar</h2>').summary()\r\n'<body id=\"readabilityBody\"><h2><a href=\"#\"/>foobar</h2></body>'\r\n```\r\n\r\nSelf-closing `a` tags are not well handled by webkit (for instance), so this leads to incorrect HTML display:\r\n\r\n![Capture d\u2019\u00e9cran du 2019-12-29 14-53-51](https://user-images.githubusercontent.com/60163/71558001-98f17c80-2a4e-11ea-96ac-cd21021b4ef9.png)\r\n\r\nIt seems to be because of lxml `tounicode` function is missing the 'method' argument:\r\n\r\n```python\r\n>>> from lxml.etree import tounicode\r\n>>> from lxml.html import document_fromstring\r\n>>> tounicode(document_fromstring('<h2><a href=\"#\"></a>Foobar</h2>'))\r\n'<html><body><h2><a href=\"#\"/>Foobar</h2></body></html>'\r\n>>> tounicode(document_fromstring('<h2><a href=\"#\"></a>Foobar</h2>'), method='html')\r\n'<html><body><h2><a href=\"#\"></a>Foobar</h2></body></html>'\r\n```\r\n\r\nWhat do you think?\r\n\r\n\u00c9loi", "performed_via_github_app": null, "score": 1.0}, {"url": "https://api.github.com/repos/buriy/python-readability/issues/123", "repository_url": "https://api.github.com/repos/buriy/python-readability", "labels_url": "https://api.github.com/repos/buriy/python-readability/issues/123/labels{/name}", "comments_url": "https://api.github.com/repos/buriy/python-readability/issues/123/comments", "events_url": "https://api.github.com/repos/buriy/python-readability/issues/123/events", "html_url": "https://github.com/buriy/python-readability/issues/123", "id": 518175768, "node_id": "MDU6SXNzdWU1MTgxNzU3Njg=", "number": 123, "title": "Will it make the task unable to proceed and end?", "user": {"login": "kjxy", "id": 35479340, "node_id": "MDQ6VXNlcjM1NDc5MzQw", "avatar_url": "https://avatars1.githubusercontent.com/u/35479340?v=4", "gravatar_id": "", "url": "https://api.github.com/users/kjxy", "html_url": "https://github.com/kjxy", "followers_url": "https://api.github.com/users/kjxy/followers", "following_url": "https://api.github.com/users/kjxy/following{/other_user}", "gists_url": "https://api.github.com/users/kjxy/gists{/gist_id}", "starred_url": "https://api.github.com/users/kjxy/starred{/owner}{/repo}", "subscriptions_url": "https://api.github.com/users/kjxy/subscriptions", "organizations_url": "https://api.github.com/users/kjxy/orgs", "repos_url": "https://api.github.com/users/kjxy/repos", "events_url": "https://api.github.com/users/kjxy/events{/privacy}", "received_events_url": "https://api.github.com/users/kjxy/received_events", "type": "User", "site_admin": false}, "labels": [], "state": "closed", "locked": false, "assignee": null, "assignees": [], "milestone": null, "comments": 1, "created_at": "2019-11-06T01:13:08Z", "updated_at": "2019-11-07T10:44:52Z", "closed_at": "2019-11-07T10:44:52Z", "author_association": "NONE", "active_lock_reason": null, "body": "`2019-11-05 10:13:24 [urllib3.connectionpool] DEBUG: Starting new HTTPS connection (1): www.baidu.com:443\r\n\r\n2019-11-05 10:13:24 [urllib3.connectionpool] DEBUG: https://www.baidu.com:443 \"GET /s?wd=site%3Azhoukan.cc HTTP/1.1\" 302 289\r\n\r\n2019-11-05 10:13:24 [urllib3.connectionpool] DEBUG: Starting new HTTPS connection (1): wappass.baidu.com:443\r\n\r\n2019-11-05 10:13:24 [urllib3.connectionpool] DEBUG: https://wappass.baidu.com:443 \"GET /static/captcha/tuxing.html?&ak=c27bbc89afca0463650ac9bde68ebe06&backurl=https%3A%2F%2Fwww.baidu.com%2Fs%3Fwd%3Dsite%253Azhoukan.cc&logid=8389977106990231268&signature=9fbf28a7817615a579e9f5420317dcc8&timestamp=1572920004 HTTP/1.1\" 200 None`\r\n\r\nThe crawler's log is stuck here and will not continue", "performed_via_github_app": null, "score": 1.0}, {"url": "https://api.github.com/repos/buriy/python-readability/issues/118", "repository_url": "https://api.github.com/repos/buriy/python-readability", "labels_url": "https://api.github.com/repos/buriy/python-readability/issues/118/labels{/name}", "comments_url": "https://api.github.com/repos/buriy/python-readability/issues/118/comments", "events_url": "https://api.github.com/repos/buriy/python-readability/issues/118/events", "html_url": "https://github.com/buriy/python-readability/issues/118", "id": 455631855, "node_id": "MDU6SXNzdWU0NTU2MzE4NTU=", "number": 118, "title": "cannot import name 'Document'", "user": {"login": "tobi1993", "id": 51754720, "node_id": "MDQ6VXNlcjUxNzU0NzIw", "avatar_url": "https://avatars1.githubusercontent.com/u/51754720?v=4", "gravatar_id": "", "url": "https://api.github.com/users/tobi1993", "html_url": "https://github.com/tobi1993", "followers_url": "https://api.github.com/users/tobi1993/followers", "following_url": "https://api.github.com/users/tobi1993/following{/other_user}", "gists_url": "https://api.github.com/users/tobi1993/gists{/gist_id}", "starred_url": "https://api.github.com/users/tobi1993/starred{/owner}{/repo}", "subscriptions_url": "https://api.github.com/users/tobi1993/subscriptions", "organizations_url": "https://api.github.com/users/tobi1993/orgs", "repos_url": "https://api.github.com/users/tobi1993/repos", "events_url": "https://api.github.com/users/tobi1993/events{/privacy}", "received_events_url": "https://api.github.com/users/tobi1993/received_events", "type": "User", "site_admin": false}, "labels": [], "state": "closed", "locked": false, "assignee": null, "assignees": [], "milestone": null, "comments": 3, "created_at": "2019-06-13T09:26:35Z", "updated_at": "2020-03-31T02:41:32Z", "closed_at": "2019-06-13T09:39:46Z", "author_association": "NONE", "active_lock_reason": null, "body": "Hi there,\r\nI am having an import error with\r\n`from readability import Document`\r\n\r\n- OS: Ubuntu\r\n- Python 3.6.7\r\n- installation: pip install readability-lxml\r\n\r\nPlease help", "performed_via_github_app": null, "score": 1.0}, {"url": "https://api.github.com/repos/buriy/python-readability/issues/114", "repository_url": "https://api.github.com/repos/buriy/python-readability", "labels_url": "https://api.github.com/repos/buriy/python-readability/issues/114/labels{/name}", "comments_url": "https://api.github.com/repos/buriy/python-readability/issues/114/comments", "events_url": "https://api.github.com/repos/buriy/python-readability/issues/114/events", "html_url": "https://github.com/buriy/python-readability/issues/114", "id": 430358800, "node_id": "MDU6SXNzdWU0MzAzNTg4MDA=", "number": 114, "title": "compile_pattern should not use string.lower() or use re.I flag", "user": {"login": "baby5", "id": 12880800, "node_id": "MDQ6VXNlcjEyODgwODAw", "avatar_url": "https://avatars1.githubusercontent.com/u/12880800?v=4", "gravatar_id": "", "url": "https://api.github.com/users/baby5", "html_url": "https://github.com/baby5", "followers_url": "https://api.github.com/users/baby5/followers", "following_url": "https://api.github.com/users/baby5/following{/other_user}", "gists_url": "https://api.github.com/users/baby5/gists{/gist_id}", "starred_url": "https://api.github.com/users/baby5/starred{/owner}{/repo}", "subscriptions_url": "https://api.github.com/users/baby5/subscriptions", "organizations_url": "https://api.github.com/users/baby5/orgs", "repos_url": "https://api.github.com/users/baby5/repos", "events_url": "https://api.github.com/users/baby5/events{/privacy}", "received_events_url": "https://api.github.com/users/baby5/received_events", "type": "User", "site_admin": false}, "labels": [], "state": "closed", "locked": false, "assignee": null, "assignees": [], "milestone": null, "comments": 2, "created_at": "2019-04-08T09:55:49Z", "updated_at": "2019-05-05T02:01:38Z", "closed_at": "2019-05-05T02:01:38Z", "author_association": "NONE", "active_lock_reason": null, "body": "https://github.com/buriy/python-readability/blob/3cbede6be469ceb8160306ff22e01c3974a2c0e0/readability/readability.py#L80\r\n\r\n`class` or `id` attributes may have uppercase", "performed_via_github_app": null, "score": 1.0}, {"url": "https://api.github.com/repos/buriy/python-readability/issues/110", "repository_url": "https://api.github.com/repos/buriy/python-readability", "labels_url": "https://api.github.com/repos/buriy/python-readability/issues/110/labels{/name}", "comments_url": "https://api.github.com/repos/buriy/python-readability/issues/110/comments", "events_url": "https://api.github.com/repos/buriy/python-readability/issues/110/events", "html_url": "https://github.com/buriy/python-readability/issues/110", "id": 366639647, "node_id": "MDU6SXNzdWUzNjY2Mzk2NDc=", "number": 110, "title": "Documentation", "user": {"login": "tocka9", "id": 1708574, "node_id": "MDQ6VXNlcjE3MDg1NzQ=", "avatar_url": "https://avatars0.githubusercontent.com/u/1708574?v=4", "gravatar_id": "", "url": "https://api.github.com/users/tocka9", "html_url": "https://github.com/tocka9", "followers_url": "https://api.github.com/users/tocka9/followers", "following_url": "https://api.github.com/users/tocka9/following{/other_user}", "gists_url": "https://api.github.com/users/tocka9/gists{/gist_id}", "starred_url": "https://api.github.com/users/tocka9/starred{/owner}{/repo}", "subscriptions_url": "https://api.github.com/users/tocka9/subscriptions", "organizations_url": "https://api.github.com/users/tocka9/orgs", "repos_url": "https://api.github.com/users/tocka9/repos", "events_url": "https://api.github.com/users/tocka9/events{/privacy}", "received_events_url": "https://api.github.com/users/tocka9/received_events", "type": "User", "site_admin": false}, "labels": [], "state": "closed", "locked": false, "assignee": null, "assignees": [], "milestone": null, "comments": 3, "created_at": "2018-10-04T06:26:39Z", "updated_at": "2019-12-30T11:23:56Z", "closed_at": "2019-12-30T11:23:56Z", "author_association": "NONE", "active_lock_reason": null, "body": "Is there any documentation available? I couldn't find anything..", "performed_via_github_app": null, "score": 1.0}, {"url": "https://api.github.com/repos/buriy/python-readability/issues/104", "repository_url": "https://api.github.com/repos/buriy/python-readability", "labels_url": "https://api.github.com/repos/buriy/python-readability/issues/104/labels{/name}", "comments_url": "https://api.github.com/repos/buriy/python-readability/issues/104/comments", "events_url": "https://api.github.com/repos/buriy/python-readability/issues/104/events", "html_url": "https://github.com/buriy/python-readability/issues/104", "id": 334732435, "node_id": "MDU6SXNzdWUzMzQ3MzI0MzU=", "number": 104, "title": "Can not import class Document", "user": {"login": "simhavas", "id": 33806781, "node_id": "MDQ6VXNlcjMzODA2Nzgx", "avatar_url": "https://avatars1.githubusercontent.com/u/33806781?v=4", "gravatar_id": "", "url": "https://api.github.com/users/simhavas", "html_url": "https://github.com/simhavas", "followers_url": "https://api.github.com/users/simhavas/followers", "following_url": "https://api.github.com/users/simhavas/following{/other_user}", "gists_url": "https://api.github.com/users/simhavas/gists{/gist_id}", "starred_url": "https://api.github.com/users/simhavas/starred{/owner}{/repo}", "subscriptions_url": "https://api.github.com/users/simhavas/subscriptions", "organizations_url": "https://api.github.com/users/simhavas/orgs", "repos_url": "https://api.github.com/users/simhavas/repos", "events_url": "https://api.github.com/users/simhavas/events{/privacy}", "received_events_url": "https://api.github.com/users/simhavas/received_events", "type": "User", "site_admin": false}, "labels": [], "state": "closed", "locked": false, "assignee": null, "assignees": [], "milestone": null, "comments": 3, "created_at": "2018-06-22T03:29:20Z", "updated_at": "2018-06-22T10:24:46Z", "closed_at": "2018-06-22T10:24:46Z", "author_association": "NONE", "active_lock_reason": null, "body": "@buriy  I ran \r\n`from readability import Document`\r\n\r\nI throws an error stating cannot import Document", "performed_via_github_app": null, "score": 1.0}, {"url": "https://api.github.com/repos/buriy/python-readability/issues/102", "repository_url": "https://api.github.com/repos/buriy/python-readability", "labels_url": "https://api.github.com/repos/buriy/python-readability/issues/102/labels{/name}", "comments_url": "https://api.github.com/repos/buriy/python-readability/issues/102/comments", "events_url": "https://api.github.com/repos/buriy/python-readability/issues/102/events", "html_url": "https://github.com/buriy/python-readability/issues/102", "id": 293821667, "node_id": "MDU6SXNzdWUyOTM4MjE2Njc=", "number": 102, "title": "Don't use drop_tree() while iterating", "user": {"login": "P1zz4br0etch3n", "id": 9010623, "node_id": "MDQ6VXNlcjkwMTA2MjM=", "avatar_url": "https://avatars0.githubusercontent.com/u/9010623?v=4", "gravatar_id": "", "url": "https://api.github.com/users/P1zz4br0etch3n", "html_url": "https://github.com/P1zz4br0etch3n", "followers_url": "https://api.github.com/users/P1zz4br0etch3n/followers", "following_url": "https://api.github.com/users/P1zz4br0etch3n/following{/other_user}", "gists_url": "https://api.github.com/users/P1zz4br0etch3n/gists{/gist_id}", "starred_url": "https://api.github.com/users/P1zz4br0etch3n/starred{/owner}{/repo}", "subscriptions_url": "https://api.github.com/users/P1zz4br0etch3n/subscriptions", "organizations_url": "https://api.github.com/users/P1zz4br0etch3n/orgs", "repos_url": "https://api.github.com/users/P1zz4br0etch3n/repos", "events_url": "https://api.github.com/users/P1zz4br0etch3n/events{/privacy}", "received_events_url": "https://api.github.com/users/P1zz4br0etch3n/received_events", "type": "User", "site_admin": false}, "labels": [], "state": "closed", "locked": false, "assignee": null, "assignees": [], "milestone": null, "comments": 2, "created_at": "2018-02-02T09:18:52Z", "updated_at": "2018-05-07T10:54:29Z", "closed_at": "2018-05-07T10:54:29Z", "author_association": "NONE", "active_lock_reason": null, "body": "I found that using drop_tree() while iterating through all nodes in the method remove_unlikely_candidates() breaks the iterator if the dropped element has children.\r\n\r\na simple example:\r\n```\r\nfrom lxml.etree import tostring\r\nfrom readability import Document\r\n\r\nHTML = '''\r\n    <html>\r\n        <body>\r\n            <aside id=\"1\">\r\n                    <a>\r\n            </aside>\r\n            <aside id=\"2\"/>\r\n            <aside id=\"3\"/>\r\n        </body>\r\n    </html>\r\n'''\r\n\r\n# parse html\r\nDOC = Document(HTML)\r\nhtml = DOC._html()\r\n\r\n# iter through all elements\r\nfor elem in html.iter():\r\n    if elem.tag == 'aside':\r\n        elem.drop_tree()\r\n\r\n# print resulting html\r\nprint(tostring(DOC.html, pretty_print=True))\r\n```\r\noutput:\r\n```\r\n<html>\r\n        <body>\r\n\r\n            <aside id=\"2\"/>\r\n            <aside id=\"3\"/>\r\n        </body>\r\n    </html>\r\n```\r\n\r\nActually every **aside** tag should be deleted, but it didn't.\r\nIf you leave out the **a** tag, everything works fine. \r\n\r\nA solution to this could be to wrap the iter statement in a list:\r\n`for elem in list(self.html.iter()):`\r\nOr to collect the elements that should be removed in a list, and drop them after iterating.", "performed_via_github_app": null, "score": 1.0}, {"url": "https://api.github.com/repos/buriy/python-readability/issues/99", "repository_url": "https://api.github.com/repos/buriy/python-readability", "labels_url": "https://api.github.com/repos/buriy/python-readability/issues/99/labels{/name}", "comments_url": "https://api.github.com/repos/buriy/python-readability/issues/99/comments", "events_url": "https://api.github.com/repos/buriy/python-readability/issues/99/events", "html_url": "https://github.com/buriy/python-readability/issues/99", "id": 276438683, "node_id": "MDU6SXNzdWUyNzY0Mzg2ODM=", "number": 99, "title": "Unparseable: Invalid IPv6 URL", "user": {"login": "mskrajnowski", "id": 803496, "node_id": "MDQ6VXNlcjgwMzQ5Ng==", "avatar_url": "https://avatars3.githubusercontent.com/u/803496?v=4", "gravatar_id": "", "url": "https://api.github.com/users/mskrajnowski", "html_url": "https://github.com/mskrajnowski", "followers_url": "https://api.github.com/users/mskrajnowski/followers", "following_url": "https://api.github.com/users/mskrajnowski/following{/other_user}", "gists_url": "https://api.github.com/users/mskrajnowski/gists{/gist_id}", "starred_url": "https://api.github.com/users/mskrajnowski/starred{/owner}{/repo}", "subscriptions_url": "https://api.github.com/users/mskrajnowski/subscriptions", "organizations_url": "https://api.github.com/users/mskrajnowski/orgs", "repos_url": "https://api.github.com/users/mskrajnowski/repos", "events_url": "https://api.github.com/users/mskrajnowski/events{/privacy}", "received_events_url": "https://api.github.com/users/mskrajnowski/received_events", "type": "User", "site_admin": false}, "labels": [], "state": "closed", "locked": false, "assignee": null, "assignees": [], "milestone": null, "comments": 0, "created_at": "2017-11-23T17:09:02Z", "updated_at": "2019-04-18T09:38:34Z", "closed_at": "2019-04-18T09:38:34Z", "author_association": "NONE", "active_lock_reason": null, "body": "`Document.summary()` fails with `Unparseable: Invalid IPv6 URL` when the document has a base href and `<a>` element with broken `href`.\r\n\r\nExample\r\n\r\n```python\r\nimport readability\r\n\r\nhtml = \"\"\"\r\n<html>\r\n    <head>\r\n        <base href=\"https://example.com/\">\r\n        <title>Example</title>\r\n    </head>\r\n    <body>\r\n        <a href=\"https://example.com[foo\">Example</a>\r\n        <p>Some article content</p>\r\n    </body>\r\n</html>\r\n\"\"\"\r\n\r\ndoc = readability.Document(html)\r\ndoc.summary()\r\n```\r\n\r\n```\r\nUnparseableTraceback (most recent call last)\r\n<ipython-input-15-55c2592de729> in <module>()\r\n      1 doc = readability.Document(html)\r\n----> 2 doc.summary()\r\n\r\n/usr/local/lib/python2.7/site-packages/readability/readability.pyc in summary(self, html_partial)\r\n    201             else:\r\n    202                 from .compat.three import raise_with_traceback\r\n--> 203             raise_with_traceback(Unparseable, sys.exc_info()[2], str_(e))\r\n    204 \r\n    205     def get_article(self, candidates, best_candidate, html_partial=False):\r\n\r\n/usr/local/lib/python2.7/site-packages/readability/readability.pyc in summary(self, html_partial)\r\n    153             ruthless = True\r\n    154             while True:\r\n--> 155                 self._html(True)\r\n    156                 for i in self.tags(self.html, 'script', 'style'):\r\n    157                     i.drop_tree()\r\n\r\n/usr/local/lib/python2.7/site-packages/readability/readability.pyc in _html(self, force)\r\n    106     def _html(self, force=False):\r\n    107         if force or self.html is None:\r\n--> 108             self.html = self._parse(self.input)\r\n    109             if self.xpath:\r\n    110                 root = self.html.getroottree()\r\n\r\n/usr/local/lib/python2.7/site-packages/readability/readability.pyc in _parse(self, input)\r\n    128                 doc.make_links_absolute(base_href, resolve_base_href=True)\r\n    129         else:\r\n--> 130             doc.resolve_base_href()\r\n    131         return doc\r\n    132 \r\n\r\n/usr/local/lib/python2.7/site-packages/lxml/html/__init__.pyc in resolve_base_href(self, handle_failures)\r\n    492             return\r\n    493         self.make_links_absolute(base_href, resolve_base_href=False,\r\n--> 494                                  handle_failures=handle_failures)\r\n    495 \r\n    496     def iterlinks(self):\r\n\r\n/usr/local/lib/python2.7/site-packages/lxml/html/__init__.pyc in make_links_absolute(self, base_url, resolve_base_href, handle_failures)\r\n    471                 \"unexpected value for handle_failures: %r\" % handle_failures)\r\n    472 \r\n--> 473         self.rewrite_links(link_repl)\r\n    474 \r\n    475     def resolve_base_href(self, handle_failures=None):\r\n\r\n/usr/local/lib/python2.7/site-packages/lxml/html/__init__.pyc in rewrite_links(self, link_repl_func, resolve_base_href, base_href)\r\n    611 \r\n    612         for el, attrib, link, pos in self.iterlinks():\r\n--> 613             new_link = link_repl_func(link.strip())\r\n    614             if new_link == link:\r\n    615                 continue\r\n\r\n/usr/local/lib/python2.7/site-packages/lxml/html/__init__.pyc in link_repl(href)\r\n    466         elif handle_failures is None:\r\n    467             def link_repl(href):\r\n--> 468                 return urljoin(base_url, href)\r\n    469         else:\r\n    470             raise ValueError(\r\n\r\n/usr/lib/python2.7/urlparse.pyc in urljoin(base, url, allow_fragments)\r\n    259             urlparse(base, '', allow_fragments)\r\n    260     scheme, netloc, path, params, query, fragment = \\\r\n--> 261             urlparse(url, bscheme, allow_fragments)\r\n    262     if scheme != bscheme or scheme not in uses_relative:\r\n    263         return url\r\n\r\n/usr/lib/python2.7/urlparse.pyc in urlparse(url, scheme, allow_fragments)\r\n    141     Note that we don't break the components up in smaller bits\r\n    142     (e.g. netloc is a single string) and we don't expand % escapes.\"\"\"\r\n--> 143     tuple = urlsplit(url, scheme, allow_fragments)\r\n    144     scheme, netloc, url, query, fragment = tuple\r\n    145     if scheme in uses_params and ';' in url:\r\n\r\n/usr/lib/python2.7/urlparse.pyc in urlsplit(url, scheme, allow_fragments)\r\n    212         if (('[' in netloc and ']' not in netloc) or\r\n    213                 (']' in netloc and '[' not in netloc)):\r\n--> 214             raise ValueError(\"Invalid IPv6 URL\")\r\n    215     if allow_fragments and '#' in url:\r\n    216         url, fragment = url.split('#', 1)\r\n\r\nUnparseable: Invalid IPv6 URL\r\n```\r\n\r\nPackage versions\r\n\r\n```\r\npython==2.7.12\r\nlxml==3.6.4\r\nreadability-lxml==0.6.2\r\n```\r\n\r\nMy guess is that it would be enough to replace https://github.com/buriy/python-readability/blob/master/readability/readability.py#L142\r\n```diff\r\n-            doc.resolve_base_href()\r\n+            doc.resolve_base_href(handle_failures='discard')\r\n```\r\n...maybe with some lxml version guards, in case `handle_failures` is not supported.", "performed_via_github_app": null, "score": 1.0}, {"url": "https://api.github.com/repos/buriy/python-readability/issues/98", "repository_url": "https://api.github.com/repos/buriy/python-readability", "labels_url": "https://api.github.com/repos/buriy/python-readability/issues/98/labels{/name}", "comments_url": "https://api.github.com/repos/buriy/python-readability/issues/98/comments", "events_url": "https://api.github.com/repos/buriy/python-readability/issues/98/events", "html_url": "https://github.com/buriy/python-readability/issues/98", "id": 228374861, "node_id": "MDU6SXNzdWUyMjgzNzQ4NjE=", "number": 98, "title": "Syntax error while installing using pip3", "user": {"login": "alandria", "id": 8218416, "node_id": "MDQ6VXNlcjgyMTg0MTY=", "avatar_url": "https://avatars3.githubusercontent.com/u/8218416?v=4", "gravatar_id": "", "url": "https://api.github.com/users/alandria", "html_url": "https://github.com/alandria", "followers_url": "https://api.github.com/users/alandria/followers", "following_url": "https://api.github.com/users/alandria/following{/other_user}", "gists_url": "https://api.github.com/users/alandria/gists{/gist_id}", "starred_url": "https://api.github.com/users/alandria/starred{/owner}{/repo}", "subscriptions_url": "https://api.github.com/users/alandria/subscriptions", "organizations_url": "https://api.github.com/users/alandria/orgs", "repos_url": "https://api.github.com/users/alandria/repos", "events_url": "https://api.github.com/users/alandria/events{/privacy}", "received_events_url": "https://api.github.com/users/alandria/received_events", "type": "User", "site_admin": false}, "labels": [], "state": "closed", "locked": false, "assignee": null, "assignees": [], "milestone": null, "comments": 3, "created_at": "2017-05-12T18:41:04Z", "updated_at": "2020-03-20T19:57:04Z", "closed_at": "2018-05-07T13:16:07Z", "author_association": "NONE", "active_lock_reason": null, "body": "The problem occurs on Ubuntu 14.04\r\n\r\n```\r\nsudo pip3 install --upgrade readability-lxml\r\nDownloading/unpacking readability-lxml\r\n  Downloading readability-lxml-0.6.2.tar.gz\r\n  Running setup.py (path:/tmp/pip_build_root/readability-lxml/setup.py) egg_info for package readability-lxml\r\nDownloading/unpacking chardet from https://pypi.python.org/packages/b8/74/54fdc2fcfdd46b6c486964b64c5bb7db9a3664033ab25cf11aab06dd2a5d/chardet-3.0.2-py2.py3-none-any.whl#md5=f18688841820b46ecc430aabdc274cde (from readability-lxml)\r\n  Downloading chardet-3.0.2-py2.py3-none-any.whl (133kB): 133kB downloaded\r\nRequirement already up-to-date: lxml in /usr/local/lib/python3.4/dist-packages (from readability-lxml)\r\nRequirement already up-to-date: cssselect in /usr/local/lib/python3.4/dist-packages (from readability-lxml)\r\nInstalling collected packages: readability-lxml, chardet\r\n  Running setup.py install for readability-lxml\r\n      File \"/usr/local/lib/python3.4/dist-packages/readability/compat/two.py\", line 6\r\n        raise exc_type(*args, **kwargs), None, traceback\r\n                                       ^\r\n    SyntaxError: invalid syntax\r\n```", "performed_via_github_app": null, "score": 1.0}, {"url": "https://api.github.com/repos/buriy/python-readability/issues/97", "repository_url": "https://api.github.com/repos/buriy/python-readability", "labels_url": "https://api.github.com/repos/buriy/python-readability/issues/97/labels{/name}", "comments_url": "https://api.github.com/repos/buriy/python-readability/issues/97/comments", "events_url": "https://api.github.com/repos/buriy/python-readability/issues/97/events", "html_url": "https://github.com/buriy/python-readability/issues/97", "id": 208268773, "node_id": "MDU6SXNzdWUyMDgyNjg3NzM=", "number": 97, "title": "Drop support for Python 2.6", "user": {"login": "cmermingas", "id": 7100704, "node_id": "MDQ6VXNlcjcxMDA3MDQ=", "avatar_url": "https://avatars0.githubusercontent.com/u/7100704?v=4", "gravatar_id": "", "url": "https://api.github.com/users/cmermingas", "html_url": "https://github.com/cmermingas", "followers_url": "https://api.github.com/users/cmermingas/followers", "following_url": "https://api.github.com/users/cmermingas/following{/other_user}", "gists_url": "https://api.github.com/users/cmermingas/gists{/gist_id}", "starred_url": "https://api.github.com/users/cmermingas/starred{/owner}{/repo}", "subscriptions_url": "https://api.github.com/users/cmermingas/subscriptions", "organizations_url": "https://api.github.com/users/cmermingas/orgs", "repos_url": "https://api.github.com/users/cmermingas/repos", "events_url": "https://api.github.com/users/cmermingas/events{/privacy}", "received_events_url": "https://api.github.com/users/cmermingas/received_events", "type": "User", "site_admin": false}, "labels": [], "state": "closed", "locked": false, "assignee": null, "assignees": [], "milestone": null, "comments": 3, "created_at": "2017-02-16T22:31:44Z", "updated_at": "2017-11-27T12:02:56Z", "closed_at": "2017-11-27T12:02:56Z", "author_association": "NONE", "active_lock_reason": null, "body": "Python 2.6 has reached EOL:\r\n\r\nhttps://www.python.org/dev/peps/pep-0361/#release-lifespan\r\n\r\nSupport can be dropped. I can do a pull request if you are ok with this.", "performed_via_github_app": null, "score": 1.0}, {"url": "https://api.github.com/repos/buriy/python-readability/issues/95", "repository_url": "https://api.github.com/repos/buriy/python-readability", "labels_url": "https://api.github.com/repos/buriy/python-readability/issues/95/labels{/name}", "comments_url": "https://api.github.com/repos/buriy/python-readability/issues/95/comments", "events_url": "https://api.github.com/repos/buriy/python-readability/issues/95/events", "html_url": "https://github.com/buriy/python-readability/issues/95", "id": 201525946, "node_id": "MDU6SXNzdWUyMDE1MjU5NDY=", "number": 95, "title": "No module named langdata", "user": {"login": "sandeepsingh", "id": 2037943, "node_id": "MDQ6VXNlcjIwMzc5NDM=", "avatar_url": "https://avatars3.githubusercontent.com/u/2037943?v=4", "gravatar_id": "", "url": "https://api.github.com/users/sandeepsingh", "html_url": "https://github.com/sandeepsingh", "followers_url": "https://api.github.com/users/sandeepsingh/followers", "following_url": "https://api.github.com/users/sandeepsingh/following{/other_user}", "gists_url": "https://api.github.com/users/sandeepsingh/gists{/gist_id}", "starred_url": "https://api.github.com/users/sandeepsingh/starred{/owner}{/repo}", "subscriptions_url": "https://api.github.com/users/sandeepsingh/subscriptions", "organizations_url": "https://api.github.com/users/sandeepsingh/orgs", "repos_url": "https://api.github.com/users/sandeepsingh/repos", "events_url": "https://api.github.com/users/sandeepsingh/events{/privacy}", "received_events_url": "https://api.github.com/users/sandeepsingh/received_events", "type": "User", "site_admin": false}, "labels": [], "state": "closed", "locked": false, "assignee": null, "assignees": [], "milestone": null, "comments": 1, "created_at": "2017-01-18T09:56:26Z", "updated_at": "2017-01-18T12:43:19Z", "closed_at": "2017-01-18T12:43:19Z", "author_association": "NONE", "active_lock_reason": null, "body": "getting this error when i import this, \r\n\r\nfrom readability import Document\r\n\r\n\r\nImportError  Traceback (most recent call last)\r\n<ipython-input-81-fb5ee06c2292> in <module>()\r\n      1 #main content region from HTML web page\r\n----> 2 from readability import Document\r\n      3 \r\n      4 # doc = Document(html)\r\n\r\nanaconda2/lib/python2.7/site-packages/readability/__init__.py in <module>()\r\n     26 import subprocess\r\n     27 import collections\r\n---> 28 from readability.langdata import LANGDATA\r\n     29 if sys.version[0] >= '3':\r\n     30         unicode = str  # pylint: disable=invalid-name,redefined-builtin\r\n\r\nImportError: No module named langdata\r\n\r\n\r\nplease help thanks", "performed_via_github_app": null, "score": 1.0}, {"url": "https://api.github.com/repos/buriy/python-readability/issues/93", "repository_url": "https://api.github.com/repos/buriy/python-readability", "labels_url": "https://api.github.com/repos/buriy/python-readability/issues/93/labels{/name}", "comments_url": "https://api.github.com/repos/buriy/python-readability/issues/93/comments", "events_url": "https://api.github.com/repos/buriy/python-readability/issues/93/events", "html_url": "https://github.com/buriy/python-readability/issues/93", "id": 192740277, "node_id": "MDU6SXNzdWUxOTI3NDAyNzc=", "number": 93, "title": "Can you find all the pictures in HTML? Then batch download", "user": {"login": "por7er", "id": 5378632, "node_id": "MDQ6VXNlcjUzNzg2MzI=", "avatar_url": "https://avatars2.githubusercontent.com/u/5378632?v=4", "gravatar_id": "", "url": "https://api.github.com/users/por7er", "html_url": "https://github.com/por7er", "followers_url": "https://api.github.com/users/por7er/followers", "following_url": "https://api.github.com/users/por7er/following{/other_user}", "gists_url": "https://api.github.com/users/por7er/gists{/gist_id}", "starred_url": "https://api.github.com/users/por7er/starred{/owner}{/repo}", "subscriptions_url": "https://api.github.com/users/por7er/subscriptions", "organizations_url": "https://api.github.com/users/por7er/orgs", "repos_url": "https://api.github.com/users/por7er/repos", "events_url": "https://api.github.com/users/por7er/events{/privacy}", "received_events_url": "https://api.github.com/users/por7er/received_events", "type": "User", "site_admin": false}, "labels": [], "state": "closed", "locked": false, "assignee": null, "assignees": [], "milestone": null, "comments": 1, "created_at": "2016-12-01T02:41:14Z", "updated_at": "2016-12-01T10:37:27Z", "closed_at": "2016-12-01T10:36:48Z", "author_association": "NONE", "active_lock_reason": null, "body": "Can you find all the pictures in HTML? Then batch download", "performed_via_github_app": null, "score": 1.0}, {"url": "https://api.github.com/repos/buriy/python-readability/issues/92", "repository_url": "https://api.github.com/repos/buriy/python-readability", "labels_url": "https://api.github.com/repos/buriy/python-readability/issues/92/labels{/name}", "comments_url": "https://api.github.com/repos/buriy/python-readability/issues/92/comments", "events_url": "https://api.github.com/repos/buriy/python-readability/issues/92/events", "html_url": "https://github.com/buriy/python-readability/issues/92", "id": 191637004, "node_id": "MDU6SXNzdWUxOTE2MzcwMDQ=", "number": 92, "title": " ERROR: 'xslt-config", "user": {"login": "por7er", "id": 5378632, "node_id": "MDQ6VXNlcjUzNzg2MzI=", "avatar_url": "https://avatars2.githubusercontent.com/u/5378632?v=4", "gravatar_id": "", "url": "https://api.github.com/users/por7er", "html_url": "https://github.com/por7er", "followers_url": "https://api.github.com/users/por7er/followers", "following_url": "https://api.github.com/users/por7er/following{/other_user}", "gists_url": "https://api.github.com/users/por7er/gists{/gist_id}", "starred_url": "https://api.github.com/users/por7er/starred{/owner}{/repo}", "subscriptions_url": "https://api.github.com/users/por7er/subscriptions", "organizations_url": "https://api.github.com/users/por7er/orgs", "repos_url": "https://api.github.com/users/por7er/repos", "events_url": "https://api.github.com/users/por7er/events{/privacy}", "received_events_url": "https://api.github.com/users/por7er/received_events", "type": "User", "site_admin": false}, "labels": [], "state": "closed", "locked": false, "assignee": null, "assignees": [], "milestone": null, "comments": 1, "created_at": "2016-11-25T07:02:20Z", "updated_at": "2016-11-30T12:23:09Z", "closed_at": "2016-11-30T12:23:09Z", "author_association": "NONE", "active_lock_reason": null, "body": " ERROR: 'xslt-config", "performed_via_github_app": null, "score": 1.0}, {"url": "https://api.github.com/repos/buriy/python-readability/issues/91", "repository_url": "https://api.github.com/repos/buriy/python-readability", "labels_url": "https://api.github.com/repos/buriy/python-readability/issues/91/labels{/name}", "comments_url": "https://api.github.com/repos/buriy/python-readability/issues/91/comments", "events_url": "https://api.github.com/repos/buriy/python-readability/issues/91/events", "html_url": "https://github.com/buriy/python-readability/issues/91", "id": 189426665, "node_id": "MDU6SXNzdWUxODk0MjY2NjU=", "number": 91, "title": "Error when using a list for 'positive_keywords'", "user": {"login": "Bartvds", "id": 685984, "node_id": "MDQ6VXNlcjY4NTk4NA==", "avatar_url": "https://avatars2.githubusercontent.com/u/685984?v=4", "gravatar_id": "", "url": "https://api.github.com/users/Bartvds", "html_url": "https://github.com/Bartvds", "followers_url": "https://api.github.com/users/Bartvds/followers", "following_url": "https://api.github.com/users/Bartvds/following{/other_user}", "gists_url": "https://api.github.com/users/Bartvds/gists{/gist_id}", "starred_url": "https://api.github.com/users/Bartvds/starred{/owner}{/repo}", "subscriptions_url": "https://api.github.com/users/Bartvds/subscriptions", "organizations_url": "https://api.github.com/users/Bartvds/orgs", "repos_url": "https://api.github.com/users/Bartvds/repos", "events_url": "https://api.github.com/users/Bartvds/events{/privacy}", "received_events_url": "https://api.github.com/users/Bartvds/received_events", "type": "User", "site_admin": false}, "labels": [], "state": "closed", "locked": false, "assignee": null, "assignees": [], "milestone": null, "comments": 1, "created_at": "2016-11-15T15:44:15Z", "updated_at": "2018-05-07T13:10:21Z", "closed_at": "2018-05-07T13:10:21Z", "author_association": "NONE", "active_lock_reason": null, "body": "Looks like the `positive_keywords` (and possible the negative version) doesn't really support a list/tuple as value.\r\n\r\nThe `compile_pattern` helper doesn't transform the list/tuple case into a regex, so later things raise when it tries to call `search()`/`match()` on the list.\r\n\r\nNot sure what is intended here, I guess transforming into a regex?\r\n\r\n", "performed_via_github_app": null, "score": 1.0}, {"url": "https://api.github.com/repos/buriy/python-readability/issues/86", "repository_url": "https://api.github.com/repos/buriy/python-readability", "labels_url": "https://api.github.com/repos/buriy/python-readability/issues/86/labels{/name}", "comments_url": "https://api.github.com/repos/buriy/python-readability/issues/86/comments", "events_url": "https://api.github.com/repos/buriy/python-readability/issues/86/events", "html_url": "https://github.com/buriy/python-readability/issues/86", "id": 166281308, "node_id": "MDU6SXNzdWUxNjYyODEzMDg=", "number": 86, "title": "HTML isn't parsed when get_clean_html is called", "user": {"login": "Ostrea", "id": 9917165, "node_id": "MDQ6VXNlcjk5MTcxNjU=", "avatar_url": "https://avatars3.githubusercontent.com/u/9917165?v=4", "gravatar_id": "", "url": "https://api.github.com/users/Ostrea", "html_url": "https://github.com/Ostrea", "followers_url": "https://api.github.com/users/Ostrea/followers", "following_url": "https://api.github.com/users/Ostrea/following{/other_user}", "gists_url": "https://api.github.com/users/Ostrea/gists{/gist_id}", "starred_url": "https://api.github.com/users/Ostrea/starred{/owner}{/repo}", "subscriptions_url": "https://api.github.com/users/Ostrea/subscriptions", "organizations_url": "https://api.github.com/users/Ostrea/orgs", "repos_url": "https://api.github.com/users/Ostrea/repos", "events_url": "https://api.github.com/users/Ostrea/events{/privacy}", "received_events_url": "https://api.github.com/users/Ostrea/received_events", "type": "User", "site_admin": false}, "labels": [], "state": "closed", "locked": false, "assignee": null, "assignees": [], "milestone": null, "comments": 3, "created_at": "2016-07-19T09:01:17Z", "updated_at": "2016-07-19T11:32:29Z", "closed_at": "2016-07-19T10:59:53Z", "author_association": "NONE", "active_lock_reason": null, "body": "`get_clean_html` fails with `TypeError` when called right after document creation.\nHow to reproduce:\n\n``` python\nfrom readability import Document\ndocument = Document('Doesn't matter what to write here')\ndocument.get_clean_html()\n```\n\nLooks like problem is in not calling `_html` [here](https://github.com/buriy/python-readability/blob/master/readability/readability.py#L143). HTML isn't parsed if I didn't call for example `title` and so it passes `None`. It fixes the problem if I call `_html` by hand.\n", "performed_via_github_app": null, "score": 1.0}, {"url": "https://api.github.com/repos/buriy/python-readability/issues/83", "repository_url": "https://api.github.com/repos/buriy/python-readability", "labels_url": "https://api.github.com/repos/buriy/python-readability/issues/83/labels{/name}", "comments_url": "https://api.github.com/repos/buriy/python-readability/issues/83/comments", "events_url": "https://api.github.com/repos/buriy/python-readability/issues/83/events", "html_url": "https://github.com/buriy/python-readability/issues/83", "id": 164992572, "node_id": "MDU6SXNzdWUxNjQ5OTI1NzI=", "number": 83, "title": "Error in install and import", "user": {"login": "farhad-arjmand", "id": 1296505, "node_id": "MDQ6VXNlcjEyOTY1MDU=", "avatar_url": "https://avatars1.githubusercontent.com/u/1296505?v=4", "gravatar_id": "", "url": "https://api.github.com/users/farhad-arjmand", "html_url": "https://github.com/farhad-arjmand", "followers_url": "https://api.github.com/users/farhad-arjmand/followers", "following_url": "https://api.github.com/users/farhad-arjmand/following{/other_user}", "gists_url": "https://api.github.com/users/farhad-arjmand/gists{/gist_id}", "starred_url": "https://api.github.com/users/farhad-arjmand/starred{/owner}{/repo}", "subscriptions_url": "https://api.github.com/users/farhad-arjmand/subscriptions", "organizations_url": "https://api.github.com/users/farhad-arjmand/orgs", "repos_url": "https://api.github.com/users/farhad-arjmand/repos", "events_url": "https://api.github.com/users/farhad-arjmand/events{/privacy}", "received_events_url": "https://api.github.com/users/farhad-arjmand/received_events", "type": "User", "site_admin": false}, "labels": [], "state": "closed", "locked": false, "assignee": null, "assignees": [], "milestone": null, "comments": 1, "created_at": "2016-07-12T04:37:42Z", "updated_at": "2016-07-15T14:15:53Z", "closed_at": "2016-07-15T14:15:53Z", "author_association": "NONE", "active_lock_reason": null, "body": "hi\ni install readability but when import readability dosent work\n\n> > > from readability.readability import Document\n> > > Traceback (most recent call last):\n> > >   File \"<stdin>\", line 1, in <module>\n> > >   File \"readability.py\", line 1, in <module>\n> > >     from readability.readability import Document\n> > > ImportError: No module named readability\n\nbut i can use command line :\npython -m readability.readability -u http://pypi.python.org/pypi/readability-lxml\n", "performed_via_github_app": null, "score": 1.0}, {"url": "https://api.github.com/repos/buriy/python-readability/issues/81", "repository_url": "https://api.github.com/repos/buriy/python-readability", "labels_url": "https://api.github.com/repos/buriy/python-readability/issues/81/labels{/name}", "comments_url": "https://api.github.com/repos/buriy/python-readability/issues/81/comments", "events_url": "https://api.github.com/repos/buriy/python-readability/issues/81/events", "html_url": "https://github.com/buriy/python-readability/issues/81", "id": 164844266, "node_id": "MDU6SXNzdWUxNjQ4NDQyNjY=", "number": 81, "title": "Travis for CI", "user": {"login": "decentral1se", "id": 1991377, "node_id": "MDQ6VXNlcjE5OTEzNzc=", "avatar_url": "https://avatars1.githubusercontent.com/u/1991377?v=4", "gravatar_id": "", "url": "https://api.github.com/users/decentral1se", "html_url": "https://github.com/decentral1se", "followers_url": "https://api.github.com/users/decentral1se/followers", "following_url": "https://api.github.com/users/decentral1se/following{/other_user}", "gists_url": "https://api.github.com/users/decentral1se/gists{/gist_id}", "starred_url": "https://api.github.com/users/decentral1se/starred{/owner}{/repo}", "subscriptions_url": "https://api.github.com/users/decentral1se/subscriptions", "organizations_url": "https://api.github.com/users/decentral1se/orgs", "repos_url": "https://api.github.com/users/decentral1se/repos", "events_url": "https://api.github.com/users/decentral1se/events{/privacy}", "received_events_url": "https://api.github.com/users/decentral1se/received_events", "type": "User", "site_admin": false}, "labels": [], "state": "closed", "locked": false, "assignee": null, "assignees": [], "milestone": null, "comments": 1, "created_at": "2016-07-11T14:01:09Z", "updated_at": "2016-07-15T14:10:40Z", "closed_at": "2016-07-15T14:10:40Z", "author_association": "NONE", "active_lock_reason": null, "body": "Any interest in getting CI working for this project?\n\nI am working on an OS project which will rely on this library and would like to see if your build is passing / failing more easily :)\n\nI'd be happy to submit the PR for the `.travis.yml` file !\n\nhttps://travis-ci.org/\n", "performed_via_github_app": null, "score": 1.0}, {"url": "https://api.github.com/repos/buriy/python-readability/issues/78", "repository_url": "https://api.github.com/repos/buriy/python-readability", "labels_url": "https://api.github.com/repos/buriy/python-readability/issues/78/labels{/name}", "comments_url": "https://api.github.com/repos/buriy/python-readability/issues/78/comments", "events_url": "https://api.github.com/repos/buriy/python-readability/issues/78/events", "html_url": "https://github.com/buriy/python-readability/issues/78", "id": 163626969, "node_id": "MDU6SXNzdWUxNjM2MjY5Njk=", "number": 78, "title": "Why not calculate node score from deep to shallow?", "user": {"login": "eromoe", "id": 3938751, "node_id": "MDQ6VXNlcjM5Mzg3NTE=", "avatar_url": "https://avatars1.githubusercontent.com/u/3938751?v=4", "gravatar_id": "", "url": "https://api.github.com/users/eromoe", "html_url": "https://github.com/eromoe", "followers_url": "https://api.github.com/users/eromoe/followers", "following_url": "https://api.github.com/users/eromoe/following{/other_user}", "gists_url": "https://api.github.com/users/eromoe/gists{/gist_id}", "starred_url": "https://api.github.com/users/eromoe/starred{/owner}{/repo}", "subscriptions_url": "https://api.github.com/users/eromoe/subscriptions", "organizations_url": "https://api.github.com/users/eromoe/orgs", "repos_url": "https://api.github.com/users/eromoe/repos", "events_url": "https://api.github.com/users/eromoe/events{/privacy}", "received_events_url": "https://api.github.com/users/eromoe/received_events", "type": "User", "site_admin": false}, "labels": [], "state": "closed", "locked": false, "assignee": null, "assignees": [], "milestone": null, "comments": 3, "created_at": "2016-07-04T08:27:46Z", "updated_at": "2018-09-27T14:49:05Z", "closed_at": "2018-09-27T14:49:05Z", "author_association": "NONE", "active_lock_reason": null, "body": "Default calculation is follow:\n\n```\n/div/p[1]\n/div/div[1]/p[1]\n/div/div[1]/div/p\n/div/div[1]/div/div/p[1]\n/div/div[1]/div/div/p[2]\n/div/div[1]/div/div/p[3]\n/div/div[1]/p[2]\n/div/div[1]/p[3]\n/div/div[1]/p[4]\n/div/div[1]/p[5]\n/div/div[1]/p[6]\n```\n\nstep 1. `/div/div[1]/p[1]` add score to `/div/div[1]` and `/div`\n\nstep 2. `/div/div[1]/div/p` add score to `/div/div[1]/div` and `/div/div[1]`\n\nScore of `/div` doesn't change , but his child `/div/div[1]` score increased. \n\nI think it is not correct here, sort tags first would make score more accurate \n", "performed_via_github_app": null, "score": 1.0}, {"url": "https://api.github.com/repos/buriy/python-readability/issues/77", "repository_url": "https://api.github.com/repos/buriy/python-readability", "labels_url": "https://api.github.com/repos/buriy/python-readability/issues/77/labels{/name}", "comments_url": "https://api.github.com/repos/buriy/python-readability/issues/77/comments", "events_url": "https://api.github.com/repos/buriy/python-readability/issues/77/events", "html_url": "https://github.com/buriy/python-readability/issues/77", "id": 163597648, "node_id": "MDU6SXNzdWUxNjM1OTc2NDg=", "number": 77, "title": "-v/--verbose  not work", "user": {"login": "eromoe", "id": 3938751, "node_id": "MDQ6VXNlcjM5Mzg3NTE=", "avatar_url": "https://avatars1.githubusercontent.com/u/3938751?v=4", "gravatar_id": "", "url": "https://api.github.com/users/eromoe", "html_url": "https://github.com/eromoe", "followers_url": "https://api.github.com/users/eromoe/followers", "following_url": "https://api.github.com/users/eromoe/following{/other_user}", "gists_url": "https://api.github.com/users/eromoe/gists{/gist_id}", "starred_url": "https://api.github.com/users/eromoe/starred{/owner}{/repo}", "subscriptions_url": "https://api.github.com/users/eromoe/subscriptions", "organizations_url": "https://api.github.com/users/eromoe/orgs", "repos_url": "https://api.github.com/users/eromoe/repos", "events_url": "https://api.github.com/users/eromoe/events{/privacy}", "received_events_url": "https://api.github.com/users/eromoe/received_events", "type": "User", "site_admin": false}, "labels": [], "state": "closed", "locked": false, "assignee": null, "assignees": [], "milestone": null, "comments": 3, "created_at": "2016-07-04T03:36:01Z", "updated_at": "2016-07-05T06:01:53Z", "closed_at": "2016-07-04T16:08:34Z", "author_association": "NONE", "active_lock_reason": null, "body": "I add a print to see why not log:\n\n-v 3\n\n```\nE:\\Project>python -m readability.readability -v 3 -l readability_test.log  -u http://ecp.sgcc.com.cn/html/project/0140\n02007/9990000000010135023.html\n{'xpath': None, 'verbose': 1, 'url': 'http://ecp.sgcc.com.cn/html/project/014002007/9990000000010135023.html', 'negative\n_keywords': None, 'browser': None, 'positive_keywords': None, 'log': 'readability_test.log'}\n```\n\n--verbose 3\n\n```\nE:\\Project>python -m readability.readability -b --verbose 3 -l readability_test.log  -u http://ecp.sgcc.com.cn/html/proj\nect/014002007/9990000000010135023.html\n{'xpath': None, 'verbose': 1, 'url': 'http://ecp.sgcc.com.cn/html/project/014002007/9990000000010135023.html', 'negative\n_keywords': None, 'browser': True, 'positive_keywords': None, 'log': 'readability_test.log'}\n```\n\nsince `parser.add_option('-v', '--verbose', action='count', default=0)` default is `0`,  don't understand why it become `1`...\n\nenv: windows 8 , python 2.7 \n", "performed_via_github_app": null, "score": 1.0}, {"url": "https://api.github.com/repos/buriy/python-readability/issues/76", "repository_url": "https://api.github.com/repos/buriy/python-readability", "labels_url": "https://api.github.com/repos/buriy/python-readability/issues/76/labels{/name}", "comments_url": "https://api.github.com/repos/buriy/python-readability/issues/76/comments", "events_url": "https://api.github.com/repos/buriy/python-readability/issues/76/events", "html_url": "https://github.com/buriy/python-readability/issues/76", "id": 163593397, "node_id": "MDU6SXNzdWUxNjM1OTMzOTc=", "number": 76, "title": "Can't get correct article content if content in table, bug?", "user": {"login": "eromoe", "id": 3938751, "node_id": "MDQ6VXNlcjM5Mzg3NTE=", "avatar_url": "https://avatars1.githubusercontent.com/u/3938751?v=4", "gravatar_id": "", "url": "https://api.github.com/users/eromoe", "html_url": "https://github.com/eromoe", "followers_url": "https://api.github.com/users/eromoe/followers", "following_url": "https://api.github.com/users/eromoe/following{/other_user}", "gists_url": "https://api.github.com/users/eromoe/gists{/gist_id}", "starred_url": "https://api.github.com/users/eromoe/starred{/owner}{/repo}", "subscriptions_url": "https://api.github.com/users/eromoe/subscriptions", "organizations_url": "https://api.github.com/users/eromoe/orgs", "repos_url": "https://api.github.com/users/eromoe/repos", "events_url": "https://api.github.com/users/eromoe/events{/privacy}", "received_events_url": "https://api.github.com/users/eromoe/received_events", "type": "User", "site_admin": false}, "labels": [], "state": "closed", "locked": false, "assignee": null, "assignees": [], "milestone": null, "comments": 5, "created_at": "2016-07-04T02:28:47Z", "updated_at": "2016-07-05T08:35:36Z", "closed_at": "2016-07-04T16:18:39Z", "author_association": "NONE", "active_lock_reason": null, "body": "I have some urls on same site. \n\nCan't get corret contain(with table):\nhttp://ecp.sgcc.com.cn/html/project/014002007/9990000000010135023.html\nhttp://ecp.sgcc.com.cn/html/project/014001001/9900000000003560149.html\n\nWork fine if no table:\nhttp://ecp.sgcc.com.cn/html/news/014001008/7900000000000045486.html\n\nMaybe a bug?\n\nupdate:\nI use `print doc.score_paragraphs()` see what happen:\n\n```\n{ < Element table at 0x50fb180 > : {\n        'content_score': 1.95,\n        'elem': < Element table at 0x50fb180 >\n    },\n    < Element tr at 0x5024b10 > : {\n        'content_score': 2.0,\n        'elem': < Element tr at 0x5024b10 >\n    },\n    < Element tr at 0x50fb300 > : {\n        'content_score': 2.0,\n        'elem': < Element tr at 0x50fb300 >\n    }\n}\n```\n\nI think tag with `tr` and `td` shoud not be treat as candidate, beside they are under `table` which also should plus some score to their parent `table`.\n", "performed_via_github_app": null, "score": 1.0}, {"url": "https://api.github.com/repos/buriy/python-readability/issues/75", "repository_url": "https://api.github.com/repos/buriy/python-readability", "labels_url": "https://api.github.com/repos/buriy/python-readability/issues/75/labels{/name}", "comments_url": "https://api.github.com/repos/buriy/python-readability/issues/75/comments", "events_url": "https://api.github.com/repos/buriy/python-readability/issues/75/events", "html_url": "https://github.com/buriy/python-readability/issues/75", "id": 163355818, "node_id": "MDU6SXNzdWUxNjMzNTU4MTg=", "number": 75, "title": "Doesn't work on this website while safari reader works.", "user": {"login": "moeseth", "id": 534443, "node_id": "MDQ6VXNlcjUzNDQ0Mw==", "avatar_url": "https://avatars1.githubusercontent.com/u/534443?v=4", "gravatar_id": "", "url": "https://api.github.com/users/moeseth", "html_url": "https://github.com/moeseth", "followers_url": "https://api.github.com/users/moeseth/followers", "following_url": "https://api.github.com/users/moeseth/following{/other_user}", "gists_url": "https://api.github.com/users/moeseth/gists{/gist_id}", "starred_url": "https://api.github.com/users/moeseth/starred{/owner}{/repo}", "subscriptions_url": "https://api.github.com/users/moeseth/subscriptions", "organizations_url": "https://api.github.com/users/moeseth/orgs", "repos_url": "https://api.github.com/users/moeseth/repos", "events_url": "https://api.github.com/users/moeseth/events{/privacy}", "received_events_url": "https://api.github.com/users/moeseth/received_events", "type": "User", "site_admin": false}, "labels": [], "state": "closed", "locked": false, "assignee": null, "assignees": [], "milestone": null, "comments": 1, "created_at": "2016-07-01T09:28:16Z", "updated_at": "2018-05-07T13:13:03Z", "closed_at": "2018-05-07T13:13:03Z", "author_association": "NONE", "active_lock_reason": null, "body": "http://www.imyanmarhouse.com/news/read/492059\n", "performed_via_github_app": null, "score": 1.0}, {"url": "https://api.github.com/repos/buriy/python-readability/issues/72", "repository_url": "https://api.github.com/repos/buriy/python-readability", "labels_url": "https://api.github.com/repos/buriy/python-readability/issues/72/labels{/name}", "comments_url": "https://api.github.com/repos/buriy/python-readability/issues/72/comments", "events_url": "https://api.github.com/repos/buriy/python-readability/issues/72/events", "html_url": "https://github.com/buriy/python-readability/issues/72", "id": 124663053, "node_id": "MDU6SXNzdWUxMjQ2NjMwNTM=", "number": 72, "title": "Detect whether page is suitable for applying readability", "user": {"login": "Andre0991", "id": 7083061, "node_id": "MDQ6VXNlcjcwODMwNjE=", "avatar_url": "https://avatars2.githubusercontent.com/u/7083061?v=4", "gravatar_id": "", "url": "https://api.github.com/users/Andre0991", "html_url": "https://github.com/Andre0991", "followers_url": "https://api.github.com/users/Andre0991/followers", "following_url": "https://api.github.com/users/Andre0991/following{/other_user}", "gists_url": "https://api.github.com/users/Andre0991/gists{/gist_id}", "starred_url": "https://api.github.com/users/Andre0991/starred{/owner}{/repo}", "subscriptions_url": "https://api.github.com/users/Andre0991/subscriptions", "organizations_url": "https://api.github.com/users/Andre0991/orgs", "repos_url": "https://api.github.com/users/Andre0991/repos", "events_url": "https://api.github.com/users/Andre0991/events{/privacy}", "received_events_url": "https://api.github.com/users/Andre0991/received_events", "type": "User", "site_admin": false}, "labels": [], "state": "closed", "locked": false, "assignee": null, "assignees": [], "milestone": null, "comments": 2, "created_at": "2016-01-03T18:19:07Z", "updated_at": "2016-01-03T19:15:02Z", "closed_at": "2016-01-03T19:15:02Z", "author_association": "NONE", "active_lock_reason": null, "body": "Hi.\n\nI'd like to know whether it's possible to make `python-readability` to indicate whether the page is question is suitable for applying readability.\n\nFor example, consider New York Times homepage. It's not supposed to be parsed by  `python-readability`.\n\nIs it possible to check this?\n\nThanks.\n", "performed_via_github_app": null, "score": 1.0}, {"url": "https://api.github.com/repos/buriy/python-readability/issues/71", "repository_url": "https://api.github.com/repos/buriy/python-readability", "labels_url": "https://api.github.com/repos/buriy/python-readability/issues/71/labels{/name}", "comments_url": "https://api.github.com/repos/buriy/python-readability/issues/71/comments", "events_url": "https://api.github.com/repos/buriy/python-readability/issues/71/events", "html_url": "https://github.com/buriy/python-readability/issues/71", "id": 121263559, "node_id": "MDU6SXNzdWUxMjEyNjM1NTk=", "number": 71, "title": "Issue with Medium pages", "user": {"login": "Andre0991", "id": 7083061, "node_id": "MDQ6VXNlcjcwODMwNjE=", "avatar_url": "https://avatars2.githubusercontent.com/u/7083061?v=4", "gravatar_id": "", "url": "https://api.github.com/users/Andre0991", "html_url": "https://github.com/Andre0991", "followers_url": "https://api.github.com/users/Andre0991/followers", "following_url": "https://api.github.com/users/Andre0991/following{/other_user}", "gists_url": "https://api.github.com/users/Andre0991/gists{/gist_id}", "starred_url": "https://api.github.com/users/Andre0991/starred{/owner}{/repo}", "subscriptions_url": "https://api.github.com/users/Andre0991/subscriptions", "organizations_url": "https://api.github.com/users/Andre0991/orgs", "repos_url": "https://api.github.com/users/Andre0991/repos", "events_url": "https://api.github.com/users/Andre0991/events{/privacy}", "received_events_url": "https://api.github.com/users/Andre0991/received_events", "type": "User", "site_admin": false}, "labels": [], "state": "closed", "locked": false, "assignee": null, "assignees": [], "milestone": null, "comments": 5, "created_at": "2015-12-09T14:58:16Z", "updated_at": "2016-04-09T14:20:27Z", "closed_at": "2016-04-09T08:29:07Z", "author_association": "NONE", "active_lock_reason": null, "body": "Hi.\n\nI'm getting some errors when trying to process any page from Medium:\n\n```\n$ python -m readability.readability -u https://medium.com/thoughts-on-media/i-read-because-we-re-all-storytellers-it-s-human-nature-after-all-d957a9d2e621#.rn719ccdw\nTraceback (most recent call last):\n  File \"/usr/local/Cellar/python/2.7.10_2/Frameworks/Python.framework/Versions/2.7/lib/python2.7/runpy.py\", line 162, in _run_module_as_main\n    \"__main__\", fname, loader, pkg_name)\n  File \"/usr/local/Cellar/python/2.7.10_2/Frameworks/Python.framework/Versions/2.7/lib/python2.7/runpy.py\", line 72, in _run_code\n    exec code in run_globals\n  File \"/usr/local/lib/python2.7/site-packages/readability/readability.py\", line 624, in <module>\n    main()\n  File \"/usr/local/lib/python2.7/site-packages/readability/readability.py\", line 600, in main\n    file = urllib2.urlopen(options.url)\n  File \"/usr/local/Cellar/python/2.7.10_2/Frameworks/Python.framework/Versions/2.7/lib/python2.7/urllib2.py\", line 154, in urlopen\n    return opener.open(url, data, timeout)\n  File \"/usr/local/Cellar/python/2.7.10_2/Frameworks/Python.framework/Versions/2.7/lib/python2.7/urllib2.py\", line 437, in open\n    response = meth(req, response)\n  File \"/usr/local/Cellar/python/2.7.10_2/Frameworks/Python.framework/Versions/2.7/lib/python2.7/urllib2.py\", line 550, in http_response\n    'http', request, response, code, msg, hdrs)\n  File \"/usr/local/Cellar/python/2.7.10_2/Frameworks/Python.framework/Versions/2.7/lib/python2.7/urllib2.py\", line 475, in error\n    return self._call_chain(*args)\n  File \"/usr/local/Cellar/python/2.7.10_2/Frameworks/Python.framework/Versions/2.7/lib/python2.7/urllib2.py\", line 409, in _call_chain\n    result = func(*args)\n  File \"/usr/local/Cellar/python/2.7.10_2/Frameworks/Python.framework/Versions/2.7/lib/python2.7/urllib2.py\", line 558, in http_error_default\n    raise HTTPError(req.get_full_url(), code, msg, hdrs, fp)\nurllib2.HTTPError: HTTP Error 403: Forbidden\n```\n\nAt first I thought it could have something to do with special characters present on the url, but the same thing happens with Medium's homepage:\n\n```\n$ python -m readability.readability -u https://medium.com/\nTraceback (most recent call last):\n  File \"/usr/local/Cellar/python/2.7.10_2/Frameworks/Python.framework/Versions/2.7/lib/python2.7/runpy.py\", line 162, in _run_module_as_main\n    \"__main__\", fname, loader, pkg_name)\n  File \"/usr/local/Cellar/python/2.7.10_2/Frameworks/Python.framework/Versions/2.7/lib/python2.7/runpy.py\", line 72, in _run_code\n    exec code in run_globals\n  File \"/usr/local/lib/python2.7/site-packages/readability/readability.py\", line 624, in <module>\n    main()\n  File \"/usr/local/lib/python2.7/site-packages/readability/readability.py\", line 600, in main\n    file = urllib2.urlopen(options.url)\n  File \"/usr/local/Cellar/python/2.7.10_2/Frameworks/Python.framework/Versions/2.7/lib/python2.7/urllib2.py\", line 154, in urlopen\n    return opener.open(url, data, timeout)\n  File \"/usr/local/Cellar/python/2.7.10_2/Frameworks/Python.framework/Versions/2.7/lib/python2.7/urllib2.py\", line 437, in open\n    response = meth(req, response)\n  File \"/usr/local/Cellar/python/2.7.10_2/Frameworks/Python.framework/Versions/2.7/lib/python2.7/urllib2.py\", line 550, in http_response\n    'http', request, response, code, msg, hdrs)\n  File \"/usr/local/Cellar/python/2.7.10_2/Frameworks/Python.framework/Versions/2.7/lib/python2.7/urllib2.py\", line 475, in error\n    return self._call_chain(*args)\n  File \"/usr/local/Cellar/python/2.7.10_2/Frameworks/Python.framework/Versions/2.7/lib/python2.7/urllib2.py\", line 409, in _call_chain\n    result = func(*args)\n  File \"/usr/local/Cellar/python/2.7.10_2/Frameworks/Python.framework/Versions/2.7/lib/python2.7/urllib2.py\", line 558, in http_error_default\n    raise HTTPError(req.get_full_url(), code, msg, hdrs, fp)\nurllib2.HTTPError: HTTP Error 403: Forbidden\n```\n\nThanks.\n", "performed_via_github_app": null, "score": 1.0}, {"url": "https://api.github.com/repos/buriy/python-readability/issues/70", "repository_url": "https://api.github.com/repos/buriy/python-readability", "labels_url": "https://api.github.com/repos/buriy/python-readability/issues/70/labels{/name}", "comments_url": "https://api.github.com/repos/buriy/python-readability/issues/70/comments", "events_url": "https://api.github.com/repos/buriy/python-readability/issues/70/events", "html_url": "https://github.com/buriy/python-readability/issues/70", "id": 105252844, "node_id": "MDU6SXNzdWUxMDUyNTI4NDQ=", "number": 70, "title": "AttributeError: 'list' object has no attribute 'split'", "user": {"login": "oncletom", "id": 138627, "node_id": "MDQ6VXNlcjEzODYyNw==", "avatar_url": "https://avatars0.githubusercontent.com/u/138627?v=4", "gravatar_id": "", "url": "https://api.github.com/users/oncletom", "html_url": "https://github.com/oncletom", "followers_url": "https://api.github.com/users/oncletom/followers", "following_url": "https://api.github.com/users/oncletom/following{/other_user}", "gists_url": "https://api.github.com/users/oncletom/gists{/gist_id}", "starred_url": "https://api.github.com/users/oncletom/starred{/owner}{/repo}", "subscriptions_url": "https://api.github.com/users/oncletom/subscriptions", "organizations_url": "https://api.github.com/users/oncletom/orgs", "repos_url": "https://api.github.com/users/oncletom/repos", "events_url": "https://api.github.com/users/oncletom/events{/privacy}", "received_events_url": "https://api.github.com/users/oncletom/received_events", "type": "User", "site_admin": false}, "labels": [], "state": "closed", "locked": false, "assignee": null, "assignees": [], "milestone": null, "comments": 5, "created_at": "2015-09-07T18:01:42Z", "updated_at": "2015-09-29T16:40:35Z", "closed_at": "2015-09-29T16:40:35Z", "author_association": "NONE", "active_lock_reason": null, "body": "Hello,\n\nI faced the aforementioned error recently with the latest version of readability-lxml. This is part of the stacktrace:\n\n```\n    text = document_fromstring(Document(html,negative_keywords=['related']).summary()).text_content()\n  File \"build/bdist.linux-x86_64/egg/readability/readability.py\", line 98, in __init__\n    self.negative_keywords = compile_pattern(negative_keywords)\n  File \"build/bdist.linux-x86_64/egg/readability/readability.py\", line 74, in compile_pattern\n    elements = elements.split(',')\nAttributeError: 'list' object has no attribute 'split'\n```\n\nAnd how it is used in our codebase:\n\n``` python\nfrom readability.readability import Document\n\nhtml = ...\n\ntext = document_fromstring(Document(html,negative_keywords=['related']).summary()).text_content()\n```\n\n**However**, this is **OK** if I pin to the version `0.3.0.6` of the library.\n\n``` bash\n$ python --version\nPython 2.7.6\n\n$ pip --version\npip 1.5.4 from /usr/lib/python2.7/dist-packages (python 2.7)\n```\n\nAny idea why such a breakage?\n\nThanks\n\ncc @olivierthereaux\n", "performed_via_github_app": null, "score": 1.0}, {"url": "https://api.github.com/repos/buriy/python-readability/issues/69", "repository_url": "https://api.github.com/repos/buriy/python-readability", "labels_url": "https://api.github.com/repos/buriy/python-readability/issues/69/labels{/name}", "comments_url": "https://api.github.com/repos/buriy/python-readability/issues/69/comments", "events_url": "https://api.github.com/repos/buriy/python-readability/issues/69/events", "html_url": "https://github.com/buriy/python-readability/issues/69", "id": 103080789, "node_id": "MDU6SXNzdWUxMDMwODA3ODk=", "number": 69, "title": "Debug.info to debug.warning", "user": {"login": "c24b", "id": 856293, "node_id": "MDQ6VXNlcjg1NjI5Mw==", "avatar_url": "https://avatars2.githubusercontent.com/u/856293?v=4", "gravatar_id": "", "url": "https://api.github.com/users/c24b", "html_url": "https://github.com/c24b", "followers_url": "https://api.github.com/users/c24b/followers", "following_url": "https://api.github.com/users/c24b/following{/other_user}", "gists_url": "https://api.github.com/users/c24b/gists{/gist_id}", "starred_url": "https://api.github.com/users/c24b/starred{/owner}{/repo}", "subscriptions_url": "https://api.github.com/users/c24b/subscriptions", "organizations_url": "https://api.github.com/users/c24b/orgs", "repos_url": "https://api.github.com/users/c24b/repos", "events_url": "https://api.github.com/users/c24b/events{/privacy}", "received_events_url": "https://api.github.com/users/c24b/received_events", "type": "User", "site_admin": false}, "labels": [], "state": "closed", "locked": false, "assignee": null, "assignees": [], "milestone": null, "comments": 2, "created_at": "2015-08-25T17:49:58Z", "updated_at": "2015-08-26T16:02:56Z", "closed_at": "2015-08-26T10:16:55Z", "author_association": "NONE", "active_lock_reason": null, "body": "You should p)rovide an option to make readibility debug info silent while using it into a programm as you provide it in cmd line\n\nI tried to rewrite logger.Level with no success\nlogging.getLogger(\"readability\").setLevel(logging.WARNING)\n", "performed_via_github_app": null, "score": 1.0}, {"url": "https://api.github.com/repos/buriy/python-readability/issues/66", "repository_url": "https://api.github.com/repos/buriy/python-readability", "labels_url": "https://api.github.com/repos/buriy/python-readability/issues/66/labels{/name}", "comments_url": "https://api.github.com/repos/buriy/python-readability/issues/66/comments", "events_url": "https://api.github.com/repos/buriy/python-readability/issues/66/events", "html_url": "https://github.com/buriy/python-readability/issues/66", "id": 77467166, "node_id": "MDU6SXNzdWU3NzQ2NzE2Ng==", "number": 66, "title": "Python 3.4 Support", "user": {"login": "shaka908", "id": 2031672, "node_id": "MDQ6VXNlcjIwMzE2NzI=", "avatar_url": "https://avatars3.githubusercontent.com/u/2031672?v=4", "gravatar_id": "", "url": "https://api.github.com/users/shaka908", "html_url": "https://github.com/shaka908", "followers_url": "https://api.github.com/users/shaka908/followers", "following_url": "https://api.github.com/users/shaka908/following{/other_user}", "gists_url": "https://api.github.com/users/shaka908/gists{/gist_id}", "starred_url": "https://api.github.com/users/shaka908/starred{/owner}{/repo}", "subscriptions_url": "https://api.github.com/users/shaka908/subscriptions", "organizations_url": "https://api.github.com/users/shaka908/orgs", "repos_url": "https://api.github.com/users/shaka908/repos", "events_url": "https://api.github.com/users/shaka908/events{/privacy}", "received_events_url": "https://api.github.com/users/shaka908/received_events", "type": "User", "site_admin": false}, "labels": [], "state": "closed", "locked": false, "assignee": null, "assignees": [], "milestone": null, "comments": 4, "created_at": "2015-05-18T02:34:45Z", "updated_at": "2015-07-27T03:40:34Z", "closed_at": "2015-07-27T03:40:34Z", "author_association": "NONE", "active_lock_reason": null, "body": "Latest version still cannot support Python 3.4\n", "performed_via_github_app": null, "score": 1.0}, {"url": "https://api.github.com/repos/buriy/python-readability/issues/58", "repository_url": "https://api.github.com/repos/buriy/python-readability", "labels_url": "https://api.github.com/repos/buriy/python-readability/issues/58/labels{/name}", "comments_url": "https://api.github.com/repos/buriy/python-readability/issues/58/comments", "events_url": "https://api.github.com/repos/buriy/python-readability/issues/58/events", "html_url": "https://github.com/buriy/python-readability/issues/58", "id": 53360724, "node_id": "MDU6SXNzdWU1MzM2MDcyNA==", "number": 58, "title": "Failure if best_elem is root", "user": {"login": "jnothman", "id": 78827, "node_id": "MDQ6VXNlcjc4ODI3", "avatar_url": "https://avatars2.githubusercontent.com/u/78827?v=4", "gravatar_id": "", "url": "https://api.github.com/users/jnothman", "html_url": "https://github.com/jnothman", "followers_url": "https://api.github.com/users/jnothman/followers", "following_url": "https://api.github.com/users/jnothman/following{/other_user}", "gists_url": "https://api.github.com/users/jnothman/gists{/gist_id}", "starred_url": "https://api.github.com/users/jnothman/starred{/owner}{/repo}", "subscriptions_url": "https://api.github.com/users/jnothman/subscriptions", "organizations_url": "https://api.github.com/users/jnothman/orgs", "repos_url": "https://api.github.com/users/jnothman/repos", "events_url": "https://api.github.com/users/jnothman/events{/privacy}", "received_events_url": "https://api.github.com/users/jnothman/received_events", "type": "User", "site_admin": false}, "labels": [], "state": "closed", "locked": false, "assignee": null, "assignees": [], "milestone": null, "comments": 2, "created_at": "2015-01-05T03:22:18Z", "updated_at": "2015-05-06T07:44:42Z", "closed_at": "2015-05-06T07:44:42Z", "author_association": "NONE", "active_lock_reason": null, "body": "I have some documents that are raising the following exception\n\n```\nTraceback (most recent call last):\n...\n  File \".../site-packages/readability/readability.py\", line 168, in summary\n    html_partial=html_partial)\n  File \".../site-packages/readability/readability.py\", line 214, in get_article\n    for sibling in best_elem.getparent().getchildren():\nUnparseable: 'NoneType' object has no attribute 'getchildren'\n```\n\nI assume there should be a fix along the lines of:\n\n``` python\nif best_elem.getparent() is None:\n    siblings = [best_elem]\nelse:\n    siblings = best_elem.getparent().getchildren()\nfor sibling in siblings:\n```\n", "performed_via_github_app": null, "score": 1.0}, {"url": "https://api.github.com/repos/buriy/python-readability/issues/57", "repository_url": "https://api.github.com/repos/buriy/python-readability", "labels_url": "https://api.github.com/repos/buriy/python-readability/issues/57/labels{/name}", "comments_url": "https://api.github.com/repos/buriy/python-readability/issues/57/comments", "events_url": "https://api.github.com/repos/buriy/python-readability/issues/57/events", "html_url": "https://github.com/buriy/python-readability/issues/57", "id": 52709237, "node_id": "MDU6SXNzdWU1MjcwOTIzNw==", "number": 57, "title": "Differences with Goose", "user": {"login": "0x0ece", "id": 1491992, "node_id": "MDQ6VXNlcjE0OTE5OTI=", "avatar_url": "https://avatars3.githubusercontent.com/u/1491992?v=4", "gravatar_id": "", "url": "https://api.github.com/users/0x0ece", "html_url": "https://github.com/0x0ece", "followers_url": "https://api.github.com/users/0x0ece/followers", "following_url": "https://api.github.com/users/0x0ece/following{/other_user}", "gists_url": "https://api.github.com/users/0x0ece/gists{/gist_id}", "starred_url": "https://api.github.com/users/0x0ece/starred{/owner}{/repo}", "subscriptions_url": "https://api.github.com/users/0x0ece/subscriptions", "organizations_url": "https://api.github.com/users/0x0ece/orgs", "repos_url": "https://api.github.com/users/0x0ece/repos", "events_url": "https://api.github.com/users/0x0ece/events{/privacy}", "received_events_url": "https://api.github.com/users/0x0ece/received_events", "type": "User", "site_admin": false}, "labels": [], "state": "closed", "locked": false, "assignee": null, "assignees": [], "milestone": null, "comments": 9, "created_at": "2014-12-23T02:39:40Z", "updated_at": "2014-12-30T18:32:34Z", "closed_at": "2014-12-28T18:38:41Z", "author_association": "NONE", "active_lock_reason": null, "body": "Hi, can I ask what are the differences with python-goose?\nhttps://github.com/grangier/python-goose\n\nOr, said in another way, why did you decide to resurrect python-readability, instead of investing in Goose?\n\nIt's a genuine question, I'm evaluating content extraction frameworks, and trying to decide which one to use. So far I prefer Goose, but I'm trying to understand if I missed something. Thank you in advance!\n", "performed_via_github_app": null, "score": 1.0}, {"url": "https://api.github.com/repos/buriy/python-readability/issues/54", "repository_url": "https://api.github.com/repos/buriy/python-readability", "labels_url": "https://api.github.com/repos/buriy/python-readability/issues/54/labels{/name}", "comments_url": "https://api.github.com/repos/buriy/python-readability/issues/54/comments", "events_url": "https://api.github.com/repos/buriy/python-readability/issues/54/events", "html_url": "https://github.com/buriy/python-readability/issues/54", "id": 50250478, "node_id": "MDU6SXNzdWU1MDI1MDQ3OA==", "number": 54, "title": "installed file(s) were overrided by readability's package", "user": {"login": "windedge", "id": 27651, "node_id": "MDQ6VXNlcjI3NjUx", "avatar_url": "https://avatars0.githubusercontent.com/u/27651?v=4", "gravatar_id": "", "url": "https://api.github.com/users/windedge", "html_url": "https://github.com/windedge", "followers_url": "https://api.github.com/users/windedge/followers", "following_url": "https://api.github.com/users/windedge/following{/other_user}", "gists_url": "https://api.github.com/users/windedge/gists{/gist_id}", "starred_url": "https://api.github.com/users/windedge/starred{/owner}{/repo}", "subscriptions_url": "https://api.github.com/users/windedge/subscriptions", "organizations_url": "https://api.github.com/users/windedge/orgs", "repos_url": "https://api.github.com/users/windedge/repos", "events_url": "https://api.github.com/users/windedge/events{/privacy}", "received_events_url": "https://api.github.com/users/windedge/received_events", "type": "User", "site_admin": false}, "labels": [], "state": "closed", "locked": false, "assignee": null, "assignees": [], "milestone": null, "comments": 1, "created_at": "2014-11-27T03:23:44Z", "updated_at": "2018-05-07T13:13:28Z", "closed_at": "2018-05-07T13:13:28Z", "author_association": "NONE", "active_lock_reason": null, "body": "There is a pypi package named 'readability' (https://pypi.python.org/pypi/readability/0.1), which install files to the same directory of readability-lxml's.\n", "performed_via_github_app": null, "score": 1.0}, {"url": "https://api.github.com/repos/buriy/python-readability/issues/52", "repository_url": "https://api.github.com/repos/buriy/python-readability", "labels_url": "https://api.github.com/repos/buriy/python-readability/issues/52/labels{/name}", "comments_url": "https://api.github.com/repos/buriy/python-readability/issues/52/comments", "events_url": "https://api.github.com/repos/buriy/python-readability/issues/52/events", "html_url": "https://github.com/buriy/python-readability/issues/52", "id": 43336823, "node_id": "MDU6SXNzdWU0MzMzNjgyMw==", "number": 52, "title": "Having problems grabbing the main article", "user": {"login": "appscluster", "id": 7013811, "node_id": "MDQ6VXNlcjcwMTM4MTE=", "avatar_url": "https://avatars2.githubusercontent.com/u/7013811?v=4", "gravatar_id": "", "url": "https://api.github.com/users/appscluster", "html_url": "https://github.com/appscluster", "followers_url": "https://api.github.com/users/appscluster/followers", "following_url": "https://api.github.com/users/appscluster/following{/other_user}", "gists_url": "https://api.github.com/users/appscluster/gists{/gist_id}", "starred_url": "https://api.github.com/users/appscluster/starred{/owner}{/repo}", "subscriptions_url": "https://api.github.com/users/appscluster/subscriptions", "organizations_url": "https://api.github.com/users/appscluster/orgs", "repos_url": "https://api.github.com/users/appscluster/repos", "events_url": "https://api.github.com/users/appscluster/events{/privacy}", "received_events_url": "https://api.github.com/users/appscluster/received_events", "type": "User", "site_admin": false}, "labels": [], "state": "closed", "locked": false, "assignee": null, "assignees": [], "milestone": null, "comments": 2, "created_at": "2014-09-21T14:51:08Z", "updated_at": "2014-09-22T12:58:23Z", "closed_at": "2014-09-22T08:48:30Z", "author_association": "NONE", "active_lock_reason": null, "body": "I am having problems grabbing the main article for this url http://ukbdnews.com/2014/09/%E0%A6%85%E0%A6%AC%E0%A6%B6%E0%A7%87%E0%A6%B7-%E0%A6%9A%E0%A6%B2%E0%A6%9A%E0%A7%8D%E0%A6%9A%E0%A6%BF%E0%A6%A4%E0%A7%8D%E0%A6%B0%E0%A6%95%E0%A7%87-%E0%A6%AC%E0%A6%BF%E0%A6%A6%E0%A6%BE%E0%A6%AF%E0%A6%BC/\n\nI have tried using different combination of positive_keywords but no luck. \n\nHowever, it does grab the title.\n\nAny help would be much appreciated. \n\nThank you\n", "performed_via_github_app": null, "score": 1.0}, {"url": "https://api.github.com/repos/buriy/python-readability/issues/51", "repository_url": "https://api.github.com/repos/buriy/python-readability", "labels_url": "https://api.github.com/repos/buriy/python-readability/issues/51/labels{/name}", "comments_url": "https://api.github.com/repos/buriy/python-readability/issues/51/comments", "events_url": "https://api.github.com/repos/buriy/python-readability/issues/51/events", "html_url": "https://github.com/buriy/python-readability/issues/51", "id": 41982910, "node_id": "MDU6SXNzdWU0MTk4MjkxMA==", "number": 51, "title": "Keep the <meta charset> tag or even add it ", "user": {"login": "gdamjan", "id": 81654, "node_id": "MDQ6VXNlcjgxNjU0", "avatar_url": "https://avatars1.githubusercontent.com/u/81654?v=4", "gravatar_id": "", "url": "https://api.github.com/users/gdamjan", "html_url": "https://github.com/gdamjan", "followers_url": "https://api.github.com/users/gdamjan/followers", "following_url": "https://api.github.com/users/gdamjan/following{/other_user}", "gists_url": "https://api.github.com/users/gdamjan/gists{/gist_id}", "starred_url": "https://api.github.com/users/gdamjan/starred{/owner}{/repo}", "subscriptions_url": "https://api.github.com/users/gdamjan/subscriptions", "organizations_url": "https://api.github.com/users/gdamjan/orgs", "repos_url": "https://api.github.com/users/gdamjan/repos", "events_url": "https://api.github.com/users/gdamjan/events{/privacy}", "received_events_url": "https://api.github.com/users/gdamjan/received_events", "type": "User", "site_admin": false}, "labels": [], "state": "closed", "locked": false, "assignee": null, "assignees": [], "milestone": null, "comments": 1, "created_at": "2014-09-04T20:40:56Z", "updated_at": "2015-07-27T04:11:58Z", "closed_at": "2015-07-27T04:11:58Z", "author_association": "NONE", "active_lock_reason": null, "body": "Html5 uses `<meta charset=\"UTF-8\">`\nHTML4 uses `<meta http-equiv=\"Content-Type\" content=\"text/html; charset=iso-8859-1\" />`\n", "performed_via_github_app": null, "score": 1.0}, {"url": "https://api.github.com/repos/buriy/python-readability/issues/49", "repository_url": "https://api.github.com/repos/buriy/python-readability", "labels_url": "https://api.github.com/repos/buriy/python-readability/issues/49/labels{/name}", "comments_url": "https://api.github.com/repos/buriy/python-readability/issues/49/comments", "events_url": "https://api.github.com/repos/buriy/python-readability/issues/49/events", "html_url": "https://github.com/buriy/python-readability/issues/49", "id": 34495938, "node_id": "MDU6SXNzdWUzNDQ5NTkzOA==", "number": 49, "title": "Crash when parsing articles with invalid link \"http://[\"", "user": {"login": "EmilStenstrom", "id": 224130, "node_id": "MDQ6VXNlcjIyNDEzMA==", "avatar_url": "https://avatars0.githubusercontent.com/u/224130?v=4", "gravatar_id": "", "url": "https://api.github.com/users/EmilStenstrom", "html_url": "https://github.com/EmilStenstrom", "followers_url": "https://api.github.com/users/EmilStenstrom/followers", "following_url": "https://api.github.com/users/EmilStenstrom/following{/other_user}", "gists_url": "https://api.github.com/users/EmilStenstrom/gists{/gist_id}", "starred_url": "https://api.github.com/users/EmilStenstrom/starred{/owner}{/repo}", "subscriptions_url": "https://api.github.com/users/EmilStenstrom/subscriptions", "organizations_url": "https://api.github.com/users/EmilStenstrom/orgs", "repos_url": "https://api.github.com/users/EmilStenstrom/repos", "events_url": "https://api.github.com/users/EmilStenstrom/events{/privacy}", "received_events_url": "https://api.github.com/users/EmilStenstrom/received_events", "type": "User", "site_admin": false}, "labels": [], "state": "closed", "locked": false, "assignee": null, "assignees": [], "milestone": null, "comments": 7, "created_at": "2014-05-28T18:56:56Z", "updated_at": "2015-07-27T04:07:08Z", "closed_at": "2015-07-27T04:07:08Z", "author_association": "NONE", "active_lock_reason": null, "body": "It seems readability crashes on links with an extra \"[\" in the url. Here's an example: http://www.theguardian.com/film/2014/apr/24/the-hurricane-rubin-carter-denzel-washington\n\n``` html\n<a href=\"http://[http://www.theguardian.com/film/filmblog/2013/may/09/raging-bull-reel-history-martin-scorsese\" title=\"\">Raging Bull</a>\n```\n\nHere's the stacktrace:\n\n```\nTraceback (most recent call last):\n  File \"manage.py\", line 14, in <module>\n    execute_from_command_line(sys.argv)\n  File \"C:\\Users\\Admin\\Envs\\presskoll\\lib\\site-packages\\django\\core\\management\\__init__.py\", line 399, in execute_from_command_line\n    utility.execute()\n  File \"C:\\Users\\Admin\\Envs\\presskoll\\lib\\site-packages\\django\\core\\management\\__init__.py\", line 392, in execute\n    self.fetch_command(subcommand).run_from_argv(self.argv)\n  File \"C:\\Users\\Admin\\Envs\\presskoll\\lib\\site-packages\\django\\core\\management\\base.py\", line 242, in run_from_argv\n    self.execute(*args, **options.__dict__)\n  File \"C:\\Users\\Admin\\Envs\\presskoll\\lib\\site-packages\\django\\core\\management\\base.py\", line 285, in execute\n    output = self.handle(*args, **options)\n  File \"C:\\Emils\\Projects\\presskoll\\presskoll\\webhook\\management\\commands\\extract_articles.py\", line 69, in handle\n    parse_article(rawarticle, overwrite=options[\"overwrite\"], DEBUG=DEBUG)\n  File \"C:\\Emils\\Projects\\presskoll\\presskoll\\webhook\\article_parser.py\", line 59, in parse_article\n    title, body = title_and_body_from_article(rawarticle)\n  File \"C:\\Emils\\Projects\\presskoll\\presskoll\\webhook\\content_util.py\", line 393, in title_and_body_from_article\n    doc = document._html(True)\n  File \"C:\\Users\\Admin\\Envs\\presskoll\\lib\\site-packages\\readability\\readability.py\", line 119, in _html\n    self.html = self._parse(self.input)\n  File \"C:\\Users\\Admin\\Envs\\presskoll\\lib\\site-packages\\readability\\readability.py\", line 127, in _parse\n    doc.make_links_absolute(base_href, resolve_base_href=True)\n  File \"C:\\Users\\Admin\\Envs\\presskoll\\lib\\site-packages\\lxml\\html\\__init__.py\", line 340, in make_links_absolute\n    self.rewrite_links(link_repl)\n  File \"C:\\Users\\Admin\\Envs\\presskoll\\lib\\site-packages\\lxml\\html\\__init__.py\", line 469, in rewrite_links\n    new_link = link_repl_func(link.strip())\n  File \"C:\\Users\\Admin\\Envs\\presskoll\\lib\\site-packages\\lxml\\html\\__init__.py\", line 335, in link_repl\n    return urljoin(base_url, href)\n  File \"C:\\Program Files\\Python27\\Lib\\urlparse.py\", line 260, in urljoin\n    urlparse(url, bscheme, allow_fragments)\n  File \"C:\\Program Files\\Python27\\Lib\\urlparse.py\", line 142, in urlparse\n    tuple = urlsplit(url, scheme, allow_fragments)\n  File \"C:\\Program Files\\Python27\\Lib\\urlparse.py\", line 190, in urlsplit\n    raise ValueError(\"Invalid IPv6 URL\")\nValueError: Invalid IPv6 URL\n```\n\nI suggest this error is catched and discarded.\n", "performed_via_github_app": null, "score": 1.0}, {"url": "https://api.github.com/repos/buriy/python-readability/issues/47", "repository_url": "https://api.github.com/repos/buriy/python-readability", "labels_url": "https://api.github.com/repos/buriy/python-readability/issues/47/labels{/name}", "comments_url": "https://api.github.com/repos/buriy/python-readability/issues/47/comments", "events_url": "https://api.github.com/repos/buriy/python-readability/issues/47/events", "html_url": "https://github.com/buriy/python-readability/issues/47", "id": 33289306, "node_id": "MDU6SXNzdWUzMzI4OTMwNg==", "number": 47, "title": "I can't extract content from this Chinese article", "user": {"login": "nathanathan", "id": 710024, "node_id": "MDQ6VXNlcjcxMDAyNA==", "avatar_url": "https://avatars2.githubusercontent.com/u/710024?v=4", "gravatar_id": "", "url": "https://api.github.com/users/nathanathan", "html_url": "https://github.com/nathanathan", "followers_url": "https://api.github.com/users/nathanathan/followers", "following_url": "https://api.github.com/users/nathanathan/following{/other_user}", "gists_url": "https://api.github.com/users/nathanathan/gists{/gist_id}", "starred_url": "https://api.github.com/users/nathanathan/starred{/owner}{/repo}", "subscriptions_url": "https://api.github.com/users/nathanathan/subscriptions", "organizations_url": "https://api.github.com/users/nathanathan/orgs", "repos_url": "https://api.github.com/users/nathanathan/repos", "events_url": "https://api.github.com/users/nathanathan/events{/privacy}", "received_events_url": "https://api.github.com/users/nathanathan/received_events", "type": "User", "site_admin": false}, "labels": [], "state": "closed", "locked": false, "assignee": null, "assignees": [], "milestone": null, "comments": 6, "created_at": "2014-05-12T08:38:39Z", "updated_at": "2015-07-27T03:37:31Z", "closed_at": "2015-07-27T03:37:31Z", "author_association": "NONE", "active_lock_reason": null, "body": "When I use readability on this article http://www.he.xinhuanet.com/news/2012-06/05/content_25346340.htm I am unable to extract any content. The encoding is gb2312, but I've converted it to unicode and the summary is still empty. The html elements don't have informative ids/classes, is there any way readability could handle documents like it?\n", "performed_via_github_app": null, "score": 1.0}, {"url": "https://api.github.com/repos/buriy/python-readability/issues/46", "repository_url": "https://api.github.com/repos/buriy/python-readability", "labels_url": "https://api.github.com/repos/buriy/python-readability/issues/46/labels{/name}", "comments_url": "https://api.github.com/repos/buriy/python-readability/issues/46/comments", "events_url": "https://api.github.com/repos/buriy/python-readability/issues/46/events", "html_url": "https://github.com/buriy/python-readability/issues/46", "id": 31131999, "node_id": "MDU6SXNzdWUzMTEzMTk5OQ==", "number": 46, "title": "No Title for most articles", "user": {"login": "gevezex", "id": 4493063, "node_id": "MDQ6VXNlcjQ0OTMwNjM=", "avatar_url": "https://avatars2.githubusercontent.com/u/4493063?v=4", "gravatar_id": "", "url": "https://api.github.com/users/gevezex", "html_url": "https://github.com/gevezex", "followers_url": "https://api.github.com/users/gevezex/followers", "following_url": "https://api.github.com/users/gevezex/following{/other_user}", "gists_url": "https://api.github.com/users/gevezex/gists{/gist_id}", "starred_url": "https://api.github.com/users/gevezex/starred{/owner}{/repo}", "subscriptions_url": "https://api.github.com/users/gevezex/subscriptions", "organizations_url": "https://api.github.com/users/gevezex/orgs", "repos_url": "https://api.github.com/users/gevezex/repos", "events_url": "https://api.github.com/users/gevezex/events{/privacy}", "received_events_url": "https://api.github.com/users/gevezex/received_events", "type": "User", "site_admin": false}, "labels": [], "state": "closed", "locked": false, "assignee": null, "assignees": [], "milestone": null, "comments": 7, "created_at": "2014-04-09T06:10:46Z", "updated_at": "2015-07-27T04:26:44Z", "closed_at": "2015-07-27T04:26:44Z", "author_association": "NONE", "active_lock_reason": null, "body": "Is there a known problem that there are nog titles for most articles on internet? When I try \"python -m readability.readability -u <url>\"  on popular news sites i don't get any headings.\n", "performed_via_github_app": null, "score": 1.0}, {"url": "https://api.github.com/repos/buriy/python-readability/issues/41", "repository_url": "https://api.github.com/repos/buriy/python-readability", "labels_url": "https://api.github.com/repos/buriy/python-readability/issues/41/labels{/name}", "comments_url": "https://api.github.com/repos/buriy/python-readability/issues/41/comments", "events_url": "https://api.github.com/repos/buriy/python-readability/issues/41/events", "html_url": "https://github.com/buriy/python-readability/issues/41", "id": 20789367, "node_id": "MDU6SXNzdWUyMDc4OTM2Nw==", "number": 41, "title": "Unparseable: local variable 'enc' referenced before assignment", "user": {"login": "Telofy", "id": 223663, "node_id": "MDQ6VXNlcjIyMzY2Mw==", "avatar_url": "https://avatars0.githubusercontent.com/u/223663?v=4", "gravatar_id": "", "url": "https://api.github.com/users/Telofy", "html_url": "https://github.com/Telofy", "followers_url": "https://api.github.com/users/Telofy/followers", "following_url": "https://api.github.com/users/Telofy/following{/other_user}", "gists_url": "https://api.github.com/users/Telofy/gists{/gist_id}", "starred_url": "https://api.github.com/users/Telofy/starred{/owner}{/repo}", "subscriptions_url": "https://api.github.com/users/Telofy/subscriptions", "organizations_url": "https://api.github.com/users/Telofy/orgs", "repos_url": "https://api.github.com/users/Telofy/repos", "events_url": "https://api.github.com/users/Telofy/events{/privacy}", "received_events_url": "https://api.github.com/users/Telofy/received_events", "type": "User", "site_admin": false}, "labels": [], "state": "closed", "locked": false, "assignee": null, "assignees": [], "milestone": null, "comments": 6, "created_at": "2013-10-10T06:19:37Z", "updated_at": "2013-11-08T10:28:03Z", "closed_at": "2013-10-10T06:53:58Z", "author_association": "NONE", "active_lock_reason": null, "body": "Hi there!\n\nExtracting doesn\u2019t work anymore when you predecode the strings. This looks pretty trivial though. `enc` could be initialized with `None`, unless that would cause any problems in other parts of the code.\n\nBy the way, I would discourage the use of the old chardet library. The range of encodings it can detect is very limited and it\u2019s slow on top. I\u2019ve found cchardet to be a lot better, but really there is the excellent `UnicodeDammit` library in BeautifulSoup that first tries to extract various explicit encoding specifications and then falls back on such implicit methods. Thanks to their latest refactoring, I could even remove a number of ugly hacks I needed to use the older version.\n\n```\n/home/telofy/.buildout/eggs/readability_lxml-0.3.0.1-py2.7.egg/readability/readability.pyc in summary(self, html_partial)\n    152             ruthless = True\n    153             while True:\n--> 154                 self._html(True)\n    155                 for i in self.tags(self.html, 'script', 'style'):\n    156                     i.drop_tree()\n\n/home/telofy/.buildout/eggs/readability_lxml-0.3.0.1-py2.7.egg/readability/readability.pyc in _html(self, force)\n    117     def _html(self, force=False):\n    118         if force or self.html is None:\n--> 119             self.html = self._parse(self.input)\n    120         return self.html\n    121 \n\n/home/telofy/.buildout/eggs/readability_lxml-0.3.0.1-py2.7.egg/readability/readability.pyc in _parse(self, input)\n    121 \n    122     def _parse(self, input):\n--> 123         doc, self.encoding = build_doc(input)\n    124         doc = html_cleaner.clean_html(doc)\n    125         base_href = self.options.get('url', None)\n\n/home/telofy/.buildout/eggs/readability_lxml-0.3.0.1-py2.7.egg/readability/htmls.pyc in build_doc(page)\n     15         page_unicode = page.decode(enc, 'replace')\n     16     doc = lxml.html.document_fromstring(page_unicode.encode('utf-8', 'replace'), parser=utf8_parser)\n---> 17     return doc, enc\n     18 \n     19 def js_re(src, pattern, flags, repl):\n\nUnparseable: local variable 'enc' referenced before assignment\n```\n", "performed_via_github_app": null, "score": 1.0}, {"url": "https://api.github.com/repos/buriy/python-readability/issues/40", "repository_url": "https://api.github.com/repos/buriy/python-readability", "labels_url": "https://api.github.com/repos/buriy/python-readability/issues/40/labels{/name}", "comments_url": "https://api.github.com/repos/buriy/python-readability/issues/40/comments", "events_url": "https://api.github.com/repos/buriy/python-readability/issues/40/events", "html_url": "https://github.com/buriy/python-readability/issues/40", "id": 20255880, "node_id": "MDU6SXNzdWUyMDI1NTg4MA==", "number": 40, "title": "Pypi not up-to-date", "user": {"login": "scraperdragon", "id": 1957682, "node_id": "MDQ6VXNlcjE5NTc2ODI=", "avatar_url": "https://avatars0.githubusercontent.com/u/1957682?v=4", "gravatar_id": "", "url": "https://api.github.com/users/scraperdragon", "html_url": "https://github.com/scraperdragon", "followers_url": "https://api.github.com/users/scraperdragon/followers", "following_url": "https://api.github.com/users/scraperdragon/following{/other_user}", "gists_url": "https://api.github.com/users/scraperdragon/gists{/gist_id}", "starred_url": "https://api.github.com/users/scraperdragon/starred{/owner}{/repo}", "subscriptions_url": "https://api.github.com/users/scraperdragon/subscriptions", "organizations_url": "https://api.github.com/users/scraperdragon/orgs", "repos_url": "https://api.github.com/users/scraperdragon/repos", "events_url": "https://api.github.com/users/scraperdragon/events{/privacy}", "received_events_url": "https://api.github.com/users/scraperdragon/received_events", "type": "User", "site_admin": false}, "labels": [], "state": "closed", "locked": false, "assignee": null, "assignees": [], "milestone": null, "comments": 3, "created_at": "2013-09-30T11:14:13Z", "updated_at": "2013-10-16T08:48:15Z", "closed_at": "2013-10-09T19:52:18Z", "author_association": "NONE", "active_lock_reason": null, "body": "Could there be a fresh version of readability on Pypi which includes fdba8d9e11494c7ae9d984afa334dc125edac7be ?\n\nI've just hit this bug, and whilst fixing it's not too much of a pain, it'd be good for people pulling fresh from Pypi to not hit it too.\n\nCheers!\n", "performed_via_github_app": null, "score": 1.0}, {"url": "https://api.github.com/repos/buriy/python-readability/issues/39", "repository_url": "https://api.github.com/repos/buriy/python-readability", "labels_url": "https://api.github.com/repos/buriy/python-readability/issues/39/labels{/name}", "comments_url": "https://api.github.com/repos/buriy/python-readability/issues/39/comments", "events_url": "https://api.github.com/repos/buriy/python-readability/issues/39/events", "html_url": "https://github.com/buriy/python-readability/issues/39", "id": 20015747, "node_id": "MDU6SXNzdWUyMDAxNTc0Nw==", "number": 39, "title": "Require older lxml version for OSX compatibility", "user": {"login": "syllog1sm", "id": 781165, "node_id": "MDQ6VXNlcjc4MTE2NQ==", "avatar_url": "https://avatars1.githubusercontent.com/u/781165?v=4", "gravatar_id": "", "url": "https://api.github.com/users/syllog1sm", "html_url": "https://github.com/syllog1sm", "followers_url": "https://api.github.com/users/syllog1sm/followers", "following_url": "https://api.github.com/users/syllog1sm/following{/other_user}", "gists_url": "https://api.github.com/users/syllog1sm/gists{/gist_id}", "starred_url": "https://api.github.com/users/syllog1sm/starred{/owner}{/repo}", "subscriptions_url": "https://api.github.com/users/syllog1sm/subscriptions", "organizations_url": "https://api.github.com/users/syllog1sm/orgs", "repos_url": "https://api.github.com/users/syllog1sm/repos", "events_url": "https://api.github.com/users/syllog1sm/events{/privacy}", "received_events_url": "https://api.github.com/users/syllog1sm/received_events", "type": "User", "site_admin": false}, "labels": [], "state": "closed", "locked": false, "assignee": null, "assignees": [], "milestone": null, "comments": 6, "created_at": "2013-09-25T00:30:01Z", "updated_at": "2014-04-02T07:24:54Z", "closed_at": "2013-10-09T19:53:17Z", "author_association": "NONE", "active_lock_reason": null, "body": "Currently, the package does not work on OSX, if installed directly via pip, because \"pip install lxml\" does not currently work on OSX.\n\nI don't know how many programmer-hours have been lost due to frustrations in installing lxml on OSX, due to OSX shipping out-dated libxml libraries. StackOverflow is littered with questions about it, and even the solutions that worked for other people didn't work for me.\n\nWhat _did_ work for me to use this package was to simply install an older lxml. If you write a requirements.txt in the root of this package, and write the lxml dependency as e.g.\n\nlxml==2.3\n\nThe package will work successfully on OSX. It works up to lxml 2.3.5, and doesn't work with lxml 3.0. I'm not sure what the oldest version your package will work with; I haven't tested that sorry.\n\nP.S Thanks for your work on this package. If this wasn't here, I'd have probably written it myself.\n\nP.P.S. After spending _hours_ on this stupid, stupid problem, let me just say: ***\\* developing on OSX sucks.\n", "performed_via_github_app": null, "score": 1.0}, {"url": "https://api.github.com/repos/buriy/python-readability/issues/37", "repository_url": "https://api.github.com/repos/buriy/python-readability", "labels_url": "https://api.github.com/repos/buriy/python-readability/issues/37/labels{/name}", "comments_url": "https://api.github.com/repos/buriy/python-readability/issues/37/comments", "events_url": "https://api.github.com/repos/buriy/python-readability/issues/37/events", "html_url": "https://github.com/buriy/python-readability/issues/37", "id": 18204507, "node_id": "MDU6SXNzdWUxODIwNDUwNw==", "number": 37, "title": "htmls.py sets root logger loglevel", "user": {"login": "youngrok", "id": 629151, "node_id": "MDQ6VXNlcjYyOTE1MQ==", "avatar_url": "https://avatars2.githubusercontent.com/u/629151?v=4", "gravatar_id": "", "url": "https://api.github.com/users/youngrok", "html_url": "https://github.com/youngrok", "followers_url": "https://api.github.com/users/youngrok/followers", "following_url": "https://api.github.com/users/youngrok/following{/other_user}", "gists_url": "https://api.github.com/users/youngrok/gists{/gist_id}", "starred_url": "https://api.github.com/users/youngrok/starred{/owner}{/repo}", "subscriptions_url": "https://api.github.com/users/youngrok/subscriptions", "organizations_url": "https://api.github.com/users/youngrok/orgs", "repos_url": "https://api.github.com/users/youngrok/repos", "events_url": "https://api.github.com/users/youngrok/events{/privacy}", "received_events_url": "https://api.github.com/users/youngrok/received_events", "type": "User", "site_admin": false}, "labels": [], "state": "closed", "locked": false, "assignee": null, "assignees": [], "milestone": null, "comments": 3, "created_at": "2013-08-18T07:57:22Z", "updated_at": "2013-10-10T02:49:23Z", "closed_at": "2013-10-09T19:54:02Z", "author_association": "NONE", "active_lock_reason": null, "body": "line 8: logging.getLogger().setLevel(logging.DEBUG)\n\nThis line should be removed. It overrides other root logger setting.\n", "performed_via_github_app": null, "score": 1.0}, {"url": "https://api.github.com/repos/buriy/python-readability/issues/34", "repository_url": "https://api.github.com/repos/buriy/python-readability", "labels_url": "https://api.github.com/repos/buriy/python-readability/issues/34/labels{/name}", "comments_url": "https://api.github.com/repos/buriy/python-readability/issues/34/comments", "events_url": "https://api.github.com/repos/buriy/python-readability/issues/34/events", "html_url": "https://github.com/buriy/python-readability/issues/34", "id": 13206116, "node_id": "MDU6SXNzdWUxMzIwNjExNg==", "number": 34, "title": "Save charset", "user": {"login": "Cosmologist", "id": 966525, "node_id": "MDQ6VXNlcjk2NjUyNQ==", "avatar_url": "https://avatars0.githubusercontent.com/u/966525?v=4", "gravatar_id": "", "url": "https://api.github.com/users/Cosmologist", "html_url": "https://github.com/Cosmologist", "followers_url": "https://api.github.com/users/Cosmologist/followers", "following_url": "https://api.github.com/users/Cosmologist/following{/other_user}", "gists_url": "https://api.github.com/users/Cosmologist/gists{/gist_id}", "starred_url": "https://api.github.com/users/Cosmologist/starred{/owner}{/repo}", "subscriptions_url": "https://api.github.com/users/Cosmologist/subscriptions", "organizations_url": "https://api.github.com/users/Cosmologist/orgs", "repos_url": "https://api.github.com/users/Cosmologist/repos", "events_url": "https://api.github.com/users/Cosmologist/events{/privacy}", "received_events_url": "https://api.github.com/users/Cosmologist/received_events", "type": "User", "site_admin": false}, "labels": [], "state": "closed", "locked": false, "assignee": null, "assignees": [], "milestone": null, "comments": 2, "created_at": "2013-04-15T15:48:47Z", "updated_at": "2013-10-09T20:02:01Z", "closed_at": "2013-10-09T20:01:54Z", "author_association": "NONE", "active_lock_reason": null, "body": "Hello!\nHow to store information about the charset (&lt;meta http-equiv=\"Content-Type\" content=\"text/html; charset=xxx\"&gt;)?\nWhen I process documents that are not encoded in utf-8 - charset information is lost and I can not correctly display the processed document to the user.\n", "performed_via_github_app": null, "score": 1.0}, {"url": "https://api.github.com/repos/buriy/python-readability/issues/33", "repository_url": "https://api.github.com/repos/buriy/python-readability", "labels_url": "https://api.github.com/repos/buriy/python-readability/issues/33/labels{/name}", "comments_url": "https://api.github.com/repos/buriy/python-readability/issues/33/comments", "events_url": "https://api.github.com/repos/buriy/python-readability/issues/33/events", "html_url": "https://github.com/buriy/python-readability/issues/33", "id": 12833015, "node_id": "MDU6SXNzdWUxMjgzMzAxNQ==", "number": 33, "title": "build_doc in htmls.py does not handle cases where get_encoding returns None", "user": {"login": "saffsd", "id": 128034, "node_id": "MDQ6VXNlcjEyODAzNA==", "avatar_url": "https://avatars0.githubusercontent.com/u/128034?v=4", "gravatar_id": "", "url": "https://api.github.com/users/saffsd", "html_url": "https://github.com/saffsd", "followers_url": "https://api.github.com/users/saffsd/followers", "following_url": "https://api.github.com/users/saffsd/following{/other_user}", "gists_url": "https://api.github.com/users/saffsd/gists{/gist_id}", "starred_url": "https://api.github.com/users/saffsd/starred{/owner}{/repo}", "subscriptions_url": "https://api.github.com/users/saffsd/subscriptions", "organizations_url": "https://api.github.com/users/saffsd/orgs", "repos_url": "https://api.github.com/users/saffsd/repos", "events_url": "https://api.github.com/users/saffsd/events{/privacy}", "received_events_url": "https://api.github.com/users/saffsd/received_events", "type": "User", "site_admin": false}, "labels": [], "state": "closed", "locked": false, "assignee": null, "assignees": [], "milestone": null, "comments": 2, "created_at": "2013-04-05T05:42:46Z", "updated_at": "2013-10-09T19:54:32Z", "closed_at": "2013-10-09T19:54:32Z", "author_association": "NONE", "active_lock_reason": null, "body": "It is possible for the call on line 16 of htmls.py to return None. This is not handled by htmls.py, resulting in the next call (page.decode) to fail with a rather cryptic\n\n```\nUnparseable: decode() argument 1 must be string, not None\n```\n\nMight it be worthwhile to raise a specific error when get_encoding returns None?\n", "performed_via_github_app": null, "score": 1.0}, {"url": "https://api.github.com/repos/buriy/python-readability/issues/32", "repository_url": "https://api.github.com/repos/buriy/python-readability", "labels_url": "https://api.github.com/repos/buriy/python-readability/issues/32/labels{/name}", "comments_url": "https://api.github.com/repos/buriy/python-readability/issues/32/comments", "events_url": "https://api.github.com/repos/buriy/python-readability/issues/32/events", "html_url": "https://github.com/buriy/python-readability/issues/32", "id": 12018575, "node_id": "MDU6SXNzdWUxMjAxODU3NQ==", "number": 32, "title": "Any research work for extracting the main body of pages? ", "user": {"login": "hupili", "id": 1227160, "node_id": "MDQ6VXNlcjEyMjcxNjA=", "avatar_url": "https://avatars0.githubusercontent.com/u/1227160?v=4", "gravatar_id": "", "url": "https://api.github.com/users/hupili", "html_url": "https://github.com/hupili", "followers_url": "https://api.github.com/users/hupili/followers", "following_url": "https://api.github.com/users/hupili/following{/other_user}", "gists_url": "https://api.github.com/users/hupili/gists{/gist_id}", "starred_url": "https://api.github.com/users/hupili/starred{/owner}{/repo}", "subscriptions_url": "https://api.github.com/users/hupili/subscriptions", "organizations_url": "https://api.github.com/users/hupili/orgs", "repos_url": "https://api.github.com/users/hupili/repos", "events_url": "https://api.github.com/users/hupili/events{/privacy}", "received_events_url": "https://api.github.com/users/hupili/received_events", "type": "User", "site_admin": false}, "labels": [], "state": "closed", "locked": false, "assignee": null, "assignees": [], "milestone": null, "comments": 2, "created_at": "2013-03-14T13:41:52Z", "updated_at": "2015-07-27T05:27:55Z", "closed_at": "2015-07-27T05:27:55Z", "author_association": "NONE", "active_lock_reason": null, "body": "Hi, \n\nI'm new to this. Tested python-readability and it works most of the time. I have not yet studied the code in details. By a fast scanning, it looks like a heuristic scoring of elements. Is there any documents to explain the scoring strategies? e.g. some quantitative study of to what degree those heuristics work? e.g. some formal datasets to test the performance of extraction by different algorithms. etc. \n\nHighly appreciated if someone can point me to recent good research works. \n\np.s. Add a funny case. It can not extract the README part (which I personally consider to be the main body) of the project homepage.\n", "performed_via_github_app": null, "score": 1.0}, {"url": "https://api.github.com/repos/buriy/python-readability/issues/31", "repository_url": "https://api.github.com/repos/buriy/python-readability", "labels_url": "https://api.github.com/repos/buriy/python-readability/issues/31/labels{/name}", "comments_url": "https://api.github.com/repos/buriy/python-readability/issues/31/comments", "events_url": "https://api.github.com/repos/buriy/python-readability/issues/31/events", "html_url": "https://github.com/buriy/python-readability/issues/31", "id": 11601068, "node_id": "MDU6SXNzdWUxMTYwMTA2OA==", "number": 31, "title": "Getting lxml stack traces with NY Times urls", "user": {"login": "dpapathanasiou", "id": 1387395, "node_id": "MDQ6VXNlcjEzODczOTU=", "avatar_url": "https://avatars0.githubusercontent.com/u/1387395?v=4", "gravatar_id": "", "url": "https://api.github.com/users/dpapathanasiou", "html_url": "https://github.com/dpapathanasiou", "followers_url": "https://api.github.com/users/dpapathanasiou/followers", "following_url": "https://api.github.com/users/dpapathanasiou/following{/other_user}", "gists_url": "https://api.github.com/users/dpapathanasiou/gists{/gist_id}", "starred_url": "https://api.github.com/users/dpapathanasiou/starred{/owner}{/repo}", "subscriptions_url": "https://api.github.com/users/dpapathanasiou/subscriptions", "organizations_url": "https://api.github.com/users/dpapathanasiou/orgs", "repos_url": "https://api.github.com/users/dpapathanasiou/repos", "events_url": "https://api.github.com/users/dpapathanasiou/events{/privacy}", "received_events_url": "https://api.github.com/users/dpapathanasiou/received_events", "type": "User", "site_admin": false}, "labels": [], "state": "closed", "locked": false, "assignee": null, "assignees": [], "milestone": null, "comments": 5, "created_at": "2013-03-04T00:33:13Z", "updated_at": "2013-07-16T13:57:07Z", "closed_at": "2013-03-04T15:06:02Z", "author_association": "NONE", "active_lock_reason": null, "body": "I've installed readability-lxml with pip on ubuntu 12.10 (64 bit, amd), and all my packages are up-to-date.\n\nWhen I try accessing urls from the NY Times website using the command line syntax, e.g., these requests:\n\n$ python -m readability.readability -u \"http://www.nytimes.com/2013/01/25/sports/25iht-sumo25.html?_r=0\"\n$ python -m readability.readability -u \"http://www.nytimes.com/2013/01/25/sports/25iht-sumo25.html\"\n$ python -m readability.readability -u \"http://www.nytimes.com/2013/03/03/magazine/beer-mergers.html?ref=magazine\"\n$ python -m readability.readability -u \"http://www.nytimes.com/2013/03/03/magazine/beer-mergers.html\"\n\nI'm getting the following stack trace:\n\n```\nERROR:root:error getting summary: \nTraceback (most recent call last):\n  File \"/usr/local/lib/python2.7/dist-packages/readability/readability.py\", line 136, in summary\n    self._html(True)\n  File \"/usr/local/lib/python2.7/dist-packages/readability/readability.py\", line 104, in _html\n    self.html = self._parse(self.input)\n  File \"/usr/local/lib/python2.7/dist-packages/readability/readability.py\", line 108, in _parse\n    doc = build_doc(input)\n  File \"/usr/local/lib/python2.7/dist-packages/readability/htmls.py\", line 18, in build_doc\n    doc = lxml.html.document_fromstring(page_unicode.encode('utf-8', 'replace'), parser=utf8_parser)\n  File \"/usr/lib/python2.7/dist-packages/lxml/html/__init__.py\", line 532, in document_fromstring\n    value = etree.fromstring(html, parser, **kw)\n  File \"lxml.etree.pyx\", line 2756, in lxml.etree.fromstring (src/lxml/lxml.etree.c:54726)\n  File \"parser.pxi\", line 1578, in lxml.etree._parseMemoryDocument (src/lxml/lxml.etree.c:82843)\n  File \"parser.pxi\", line 1457, in lxml.etree._parseDoc (src/lxml/lxml.etree.c:81641)\n  File \"parser.pxi\", line 965, in lxml.etree._BaseParser._parseDoc (src/lxml/lxml.etree.c:78311)\n  File \"parser.pxi\", line 569, in lxml.etree._ParserContext._handleParseResultDoc (src/lxml/lxml.etree.c:74567)\n  File \"parser.pxi\", line 650, in lxml.etree._handleParseResult (src/lxml/lxml.etree.c:75458)\n  File \"parser.pxi\", line 601, in lxml.etree._raiseParseError (src/lxml/lxml.etree.c:74958)\nXMLSyntaxError: None\nTraceback (most recent call last):\n  File \"/usr/lib/python2.7/runpy.py\", line 162, in _run_module_as_main\n    \"__main__\", fname, loader, pkg_name)\n  File \"/usr/lib/python2.7/runpy.py\", line 72, in _run_code\n    exec code in run_globals\n  File \"/usr/local/lib/python2.7/dist-packages/readability/readability.py\", line 589, in <module>\n    main()\n  File \"/usr/local/lib/python2.7/dist-packages/readability/readability.py\", line 584, in main\n    url=options.url).summary().encode(enc, 'replace')\n  File \"/usr/local/lib/python2.7/dist-packages/readability/readability.py\", line 136, in summary\n    self._html(True)\n  File \"/usr/local/lib/python2.7/dist-packages/readability/readability.py\", line 104, in _html\n    self.html = self._parse(self.input)\n  File \"/usr/local/lib/python2.7/dist-packages/readability/readability.py\", line 108, in _parse\n    doc = build_doc(input)\n  File \"/usr/local/lib/python2.7/dist-packages/readability/htmls.py\", line 18, in build_doc\n    doc = lxml.html.document_fromstring(page_unicode.encode('utf-8', 'replace'), parser=utf8_parser)\n  File \"/usr/lib/python2.7/dist-packages/lxml/html/__init__.py\", line 532, in document_fromstring\n    value = etree.fromstring(html, parser, **kw)\n  File \"lxml.etree.pyx\", line 2756, in lxml.etree.fromstring (src/lxml/lxml.etree.c:54726)\n  File \"parser.pxi\", line 1578, in lxml.etree._parseMemoryDocument (src/lxml/lxml.etree.c:82843)\n  File \"parser.pxi\", line 1457, in lxml.etree._parseDoc (src/lxml/lxml.etree.c:81641)\n  File \"parser.pxi\", line 965, in lxml.etree._BaseParser._parseDoc (src/lxml/lxml.etree.c:78311)\n  File \"parser.pxi\", line 569, in lxml.etree._ParserContext._handleParseResultDoc (src/lxml/lxml.etree.c:74567)\n  File \"parser.pxi\", line 650, in lxml.etree._handleParseResult (src/lxml/lxml.etree.c:75458)\n  File \"parser.pxi\", line 601, in lxml.etree._raiseParseError (src/lxml/lxml.etree.c:74958)\n__main__.Unparseable: None\n```\n", "performed_via_github_app": null, "score": 1.0}, {"url": "https://api.github.com/repos/buriy/python-readability/issues/30", "repository_url": "https://api.github.com/repos/buriy/python-readability", "labels_url": "https://api.github.com/repos/buriy/python-readability/issues/30/labels{/name}", "comments_url": "https://api.github.com/repos/buriy/python-readability/issues/30/comments", "events_url": "https://api.github.com/repos/buriy/python-readability/issues/30/events", "html_url": "https://github.com/buriy/python-readability/issues/30", "id": 7633061, "node_id": "MDU6SXNzdWU3NjMzMDYx", "number": 30, "title": "Erratic <p> insertion in Macrumors article", "user": {"login": "akavlie", "id": 306444, "node_id": "MDQ6VXNlcjMwNjQ0NA==", "avatar_url": "https://avatars2.githubusercontent.com/u/306444?v=4", "gravatar_id": "", "url": "https://api.github.com/users/akavlie", "html_url": "https://github.com/akavlie", "followers_url": "https://api.github.com/users/akavlie/followers", "following_url": "https://api.github.com/users/akavlie/following{/other_user}", "gists_url": "https://api.github.com/users/akavlie/gists{/gist_id}", "starred_url": "https://api.github.com/users/akavlie/starred{/owner}{/repo}", "subscriptions_url": "https://api.github.com/users/akavlie/subscriptions", "organizations_url": "https://api.github.com/users/akavlie/orgs", "repos_url": "https://api.github.com/users/akavlie/repos", "events_url": "https://api.github.com/users/akavlie/events{/privacy}", "received_events_url": "https://api.github.com/users/akavlie/received_events", "type": "User", "site_admin": false}, "labels": [], "state": "closed", "locked": false, "assignee": {"login": "buriy", "id": 21124, "node_id": "MDQ6VXNlcjIxMTI0", "avatar_url": "https://avatars1.githubusercontent.com/u/21124?v=4", "gravatar_id": "", "url": "https://api.github.com/users/buriy", "html_url": "https://github.com/buriy", "followers_url": "https://api.github.com/users/buriy/followers", "following_url": "https://api.github.com/users/buriy/following{/other_user}", "gists_url": "https://api.github.com/users/buriy/gists{/gist_id}", "starred_url": "https://api.github.com/users/buriy/starred{/owner}{/repo}", "subscriptions_url": "https://api.github.com/users/buriy/subscriptions", "organizations_url": "https://api.github.com/users/buriy/orgs", "repos_url": "https://api.github.com/users/buriy/repos", "events_url": "https://api.github.com/users/buriy/events{/privacy}", "received_events_url": "https://api.github.com/users/buriy/received_events", "type": "User", "site_admin": false}, "assignees": [{"login": "buriy", "id": 21124, "node_id": "MDQ6VXNlcjIxMTI0", "avatar_url": "https://avatars1.githubusercontent.com/u/21124?v=4", "gravatar_id": "", "url": "https://api.github.com/users/buriy", "html_url": "https://github.com/buriy", "followers_url": "https://api.github.com/users/buriy/followers", "following_url": "https://api.github.com/users/buriy/following{/other_user}", "gists_url": "https://api.github.com/users/buriy/gists{/gist_id}", "starred_url": "https://api.github.com/users/buriy/starred{/owner}{/repo}", "subscriptions_url": "https://api.github.com/users/buriy/subscriptions", "organizations_url": "https://api.github.com/users/buriy/orgs", "repos_url": "https://api.github.com/users/buriy/repos", "events_url": "https://api.github.com/users/buriy/events{/privacy}", "received_events_url": "https://api.github.com/users/buriy/received_events", "type": "User", "site_admin": false}], "milestone": null, "comments": 3, "created_at": "2012-10-16T17:42:06Z", "updated_at": "2012-10-17T17:56:42Z", "closed_at": "2012-10-17T07:32:00Z", "author_association": "NONE", "active_lock_reason": null, "body": "Macrumors uses `<br>` tags to separate their paragraphs. Readability attempts to insert `<p>` tags into the article, but results are not as you'd expect.\n\nFor example, this article: http://www.macrumors.com/2012/10/12/apples-ipad-mini-media-event-reportedly-scheduled-for-october-23/\n\nresults in this output for `Document(content).summary()`:\n\n``` html\n<html><body><div><div class=\"content\">\n                        <a href=\"http://allthingsd.com/20121012/apple-likely-to-unveil-ipad-mini-at-october-23-event/\">\n<i>AllThingsD</i> reports</a><p> that Apple appears to be planning to hold a media event on Tuesday, October 23 to introduce \nthe \"iPad mini\", Apple's smaller tablet device said to be carrying a display measuring 7.85 inches diagonally.</p>\n<p class=\"quote\">As AllThingsD reported in August, Apple will hold a special event this month at which it will showcase a new, \nsmaller iPad. People familiar with Apple\u2019s plans tell us that the company will unveil the so-called \u201ciPad mini\u201d on October 23 at an \ninvitation-only event.<br/><br/>\nThat\u2019s a Tuesday, not a Wednesday, so this is a bit of a break with recent tradition. It also happens to be just three days prior to \nthe street date for Microsoft\u2019s new Surface tablet.</p><center>\n<img src=\"http://cdn.macrumors.com/article-new/2012/09/ipadmini_small.jpg\"/><br/><i>Physical mockup of rumored iPad mini design</i></center><p>\nThe location of the event is unconfirmed, but the report suggests that it is likely to be held at the company's Town Hall \nauditorium at its corporate headquarters in Cupertino, California.</p><i>AllThingsD</i><p> has an excellent track record \nregarding Apple media event rumors, giving this claim a high probability of proving true.  Given past history, Apple would be \nexpected to send out invitations early next week if the event is to be held on October 23.</p><b>Update</b><p>: </p><em>The \nLoop</em><p>'s Jim Dalrymple weighs in, </p>\n<a href=\"http://www.loopinsight.com/2012/10/12/apples-rumored-oct-23-ipad-mini-event/\">confirming the date</a><p> with a \"Yep.\"\n                                        </p><p/>\n                    </div>\n                    </div></body></html>\n```\n", "performed_via_github_app": null, "score": 1.0}, {"url": "https://api.github.com/repos/buriy/python-readability/issues/28", "repository_url": "https://api.github.com/repos/buriy/python-readability", "labels_url": "https://api.github.com/repos/buriy/python-readability/issues/28/labels{/name}", "comments_url": "https://api.github.com/repos/buriy/python-readability/issues/28/comments", "events_url": "https://api.github.com/repos/buriy/python-readability/issues/28/events", "html_url": "https://github.com/buriy/python-readability/issues/28", "id": 6834656, "node_id": "MDU6SXNzdWU2ODM0NjU2", "number": 28, "title": "We need a way to cut out bad scoring elems inside good ones.", "user": {"login": "nhnifong", "id": 345920, "node_id": "MDQ6VXNlcjM0NTkyMA==", "avatar_url": "https://avatars0.githubusercontent.com/u/345920?v=4", "gravatar_id": "", "url": "https://api.github.com/users/nhnifong", "html_url": "https://github.com/nhnifong", "followers_url": "https://api.github.com/users/nhnifong/followers", "following_url": "https://api.github.com/users/nhnifong/following{/other_user}", "gists_url": "https://api.github.com/users/nhnifong/gists{/gist_id}", "starred_url": "https://api.github.com/users/nhnifong/starred{/owner}{/repo}", "subscriptions_url": "https://api.github.com/users/nhnifong/subscriptions", "organizations_url": "https://api.github.com/users/nhnifong/orgs", "repos_url": "https://api.github.com/users/nhnifong/repos", "events_url": "https://api.github.com/users/nhnifong/events{/privacy}", "received_events_url": "https://api.github.com/users/nhnifong/received_events", "type": "User", "site_admin": false}, "labels": [], "state": "closed", "locked": false, "assignee": null, "assignees": [], "milestone": null, "comments": 3, "created_at": "2012-09-12T23:12:26Z", "updated_at": "2013-10-09T20:03:38Z", "closed_at": "2013-10-09T20:03:38Z", "author_association": "NONE", "active_lock_reason": null, "body": "For example, in http://www.kwqc.com/story/19484184/shots-fired-in-ill-school-2-students-in-custody\nreadability will include the block of related links that is inside the div of the main story, dispite it's link density being high and it's overall content score being low.\n\nFirstly I want to know if it's supposed to do that. Is there any support for cutting out bad divs from inside good ones?\n\nand if not, can you suggest a starting place to go about doing this?\n", "performed_via_github_app": null, "score": 1.0}, {"url": "https://api.github.com/repos/buriy/python-readability/issues/26", "repository_url": "https://api.github.com/repos/buriy/python-readability", "labels_url": "https://api.github.com/repos/buriy/python-readability/issues/26/labels{/name}", "comments_url": "https://api.github.com/repos/buriy/python-readability/issues/26/comments", "events_url": "https://api.github.com/repos/buriy/python-readability/issues/26/events", "html_url": "https://github.com/buriy/python-readability/issues/26", "id": 5733673, "node_id": "MDU6SXNzdWU1NzMzNjcz", "number": 26, "title": "Annoying warning when using readability", "user": {"login": "sprat", "id": 577183, "node_id": "MDQ6VXNlcjU3NzE4Mw==", "avatar_url": "https://avatars2.githubusercontent.com/u/577183?v=4", "gravatar_id": "", "url": "https://api.github.com/users/sprat", "html_url": "https://github.com/sprat", "followers_url": "https://api.github.com/users/sprat/followers", "following_url": "https://api.github.com/users/sprat/following{/other_user}", "gists_url": "https://api.github.com/users/sprat/gists{/gist_id}", "starred_url": "https://api.github.com/users/sprat/starred{/owner}{/repo}", "subscriptions_url": "https://api.github.com/users/sprat/subscriptions", "organizations_url": "https://api.github.com/users/sprat/orgs", "repos_url": "https://api.github.com/users/sprat/repos", "events_url": "https://api.github.com/users/sprat/events{/privacy}", "received_events_url": "https://api.github.com/users/sprat/received_events", "type": "User", "site_admin": false}, "labels": [], "state": "closed", "locked": false, "assignee": null, "assignees": [], "milestone": null, "comments": 2, "created_at": "2012-07-20T09:58:57Z", "updated_at": "2012-07-23T08:34:39Z", "closed_at": "2012-07-23T08:34:39Z", "author_association": "NONE", "active_lock_reason": null, "body": "Here it is:\n/home/spt/projects/sandboxes/readability/lib/python2.7/site-packages/readability_lxml-0.2.6-py2.7.egg/readability/htmls.py:60: FutureWarning: The behavior of this method will change in future versions. Use specific 'len(elem)' or 'elem is not None' test instead.\n\nSorry, I've not much time to contribute a patch right now but I may contribute one if nobody fixes the problem before me ;)\n", "performed_via_github_app": null, "score": 1.0}, {"url": "https://api.github.com/repos/buriy/python-readability/issues/23", "repository_url": "https://api.github.com/repos/buriy/python-readability", "labels_url": "https://api.github.com/repos/buriy/python-readability/issues/23/labels{/name}", "comments_url": "https://api.github.com/repos/buriy/python-readability/issues/23/comments", "events_url": "https://api.github.com/repos/buriy/python-readability/issues/23/events", "html_url": "https://github.com/buriy/python-readability/issues/23", "id": 5196740, "node_id": "MDU6SXNzdWU1MTk2NzQw", "number": 23, "title": "error: get comments, not text", "user": {"login": "xnj", "id": 1877472, "node_id": "MDQ6VXNlcjE4Nzc0NzI=", "avatar_url": "https://avatars0.githubusercontent.com/u/1877472?v=4", "gravatar_id": "", "url": "https://api.github.com/users/xnj", "html_url": "https://github.com/xnj", "followers_url": "https://api.github.com/users/xnj/followers", "following_url": "https://api.github.com/users/xnj/following{/other_user}", "gists_url": "https://api.github.com/users/xnj/gists{/gist_id}", "starred_url": "https://api.github.com/users/xnj/starred{/owner}{/repo}", "subscriptions_url": "https://api.github.com/users/xnj/subscriptions", "organizations_url": "https://api.github.com/users/xnj/orgs", "repos_url": "https://api.github.com/users/xnj/repos", "events_url": "https://api.github.com/users/xnj/events{/privacy}", "received_events_url": "https://api.github.com/users/xnj/received_events", "type": "User", "site_admin": false}, "labels": [], "state": "closed", "locked": false, "assignee": null, "assignees": [], "milestone": null, "comments": 2, "created_at": "2012-06-21T15:54:56Z", "updated_at": "2013-10-09T20:03:29Z", "closed_at": "2013-10-09T20:03:29Z", "author_association": "NONE", "active_lock_reason": null, "body": "my code:\n\nfrom readability.readability import Document\nimport urllib\n\nurl='http://www.womanclinics.ru/boli-vnizu-zhivota-u-zhenshhin.html'\n\nhtml = urllib.urlopen(url).read()\n\nreadable_article = Document(html).summary()\n\nprint readable_article\n\n\"\"\"\nin readable_article we get comments, not article text\nbut when i use original tool: http://www.readability.com/articles/erldraqk\nits work right, we get article text, not comments\n\"\"\"\n", "performed_via_github_app": null, "score": 1.0}, {"url": "https://api.github.com/repos/buriy/python-readability/issues/22", "repository_url": "https://api.github.com/repos/buriy/python-readability", "labels_url": "https://api.github.com/repos/buriy/python-readability/issues/22/labels{/name}", "comments_url": "https://api.github.com/repos/buriy/python-readability/issues/22/comments", "events_url": "https://api.github.com/repos/buriy/python-readability/issues/22/events", "html_url": "https://github.com/buriy/python-readability/issues/22", "id": 5196618, "node_id": "MDU6SXNzdWU1MTk2NjE4", "number": 22, "title": "Warning in htmls.py", "user": {"login": "xnj", "id": 1877472, "node_id": "MDQ6VXNlcjE4Nzc0NzI=", "avatar_url": "https://avatars0.githubusercontent.com/u/1877472?v=4", "gravatar_id": "", "url": "https://api.github.com/users/xnj", "html_url": "https://github.com/xnj", "followers_url": "https://api.github.com/users/xnj/followers", "following_url": "https://api.github.com/users/xnj/following{/other_user}", "gists_url": "https://api.github.com/users/xnj/gists{/gist_id}", "starred_url": "https://api.github.com/users/xnj/starred{/owner}{/repo}", "subscriptions_url": "https://api.github.com/users/xnj/subscriptions", "organizations_url": "https://api.github.com/users/xnj/orgs", "repos_url": "https://api.github.com/users/xnj/repos", "events_url": "https://api.github.com/users/xnj/events{/privacy}", "received_events_url": "https://api.github.com/users/xnj/received_events", "type": "User", "site_admin": false}, "labels": [], "state": "closed", "locked": false, "assignee": null, "assignees": [], "milestone": null, "comments": 0, "created_at": "2012-06-21T15:50:13Z", "updated_at": "2012-07-17T12:32:25Z", "closed_at": "2012-07-17T12:32:25Z", "author_association": "NONE", "active_lock_reason": null, "body": "Warning (from warnings module):\n  File \"c:\\Python27\\egg\\Lib\\site-packages\\readability\\htmls.py\", line 60\n    if not title or not title.text:\nFutureWarning: The behavior of this method will change in future versions. Use specific 'len(elem)' or 'elem is not None' test instead.\n\nupdate \n\n```\n#if not title or not title.text:\n```\n# replace to:\n\n```\nif title is not None or title.text is not None:\n```\n", "performed_via_github_app": null, "score": 1.0}, {"url": "https://api.github.com/repos/buriy/python-readability/issues/21", "repository_url": "https://api.github.com/repos/buriy/python-readability", "labels_url": "https://api.github.com/repos/buriy/python-readability/issues/21/labels{/name}", "comments_url": "https://api.github.com/repos/buriy/python-readability/issues/21/comments", "events_url": "https://api.github.com/repos/buriy/python-readability/issues/21/events", "html_url": "https://github.com/buriy/python-readability/issues/21", "id": 5145332, "node_id": "MDU6SXNzdWU1MTQ1MzMy", "number": 21, "title": "Add version 0.2.5.1 to pypi", "user": {"login": "droodle", "id": 1867537, "node_id": "MDQ6VXNlcjE4Njc1Mzc=", "avatar_url": "https://avatars1.githubusercontent.com/u/1867537?v=4", "gravatar_id": "", "url": "https://api.github.com/users/droodle", "html_url": "https://github.com/droodle", "followers_url": "https://api.github.com/users/droodle/followers", "following_url": "https://api.github.com/users/droodle/following{/other_user}", "gists_url": "https://api.github.com/users/droodle/gists{/gist_id}", "starred_url": "https://api.github.com/users/droodle/starred{/owner}{/repo}", "subscriptions_url": "https://api.github.com/users/droodle/subscriptions", "organizations_url": "https://api.github.com/users/droodle/orgs", "repos_url": "https://api.github.com/users/droodle/repos", "events_url": "https://api.github.com/users/droodle/events{/privacy}", "received_events_url": "https://api.github.com/users/droodle/received_events", "type": "User", "site_admin": false}, "labels": [], "state": "closed", "locked": false, "assignee": null, "assignees": [], "milestone": null, "comments": 1, "created_at": "2012-06-19T12:45:15Z", "updated_at": "2012-06-21T14:58:05Z", "closed_at": "2012-06-21T14:58:05Z", "author_association": "NONE", "active_lock_reason": null, "body": "Since the last version (0.2.5.1) integrates an interesting bugfix (https://github.com/buriy/python-readability/commit/95852d5c1828823e2706cff792229f8b112f2047) it would be great if it was available on pypi.\n", "performed_via_github_app": null, "score": 1.0}, {"url": "https://api.github.com/repos/buriy/python-readability/issues/16", "repository_url": "https://api.github.com/repos/buriy/python-readability", "labels_url": "https://api.github.com/repos/buriy/python-readability/issues/16/labels{/name}", "comments_url": "https://api.github.com/repos/buriy/python-readability/issues/16/comments", "events_url": "https://api.github.com/repos/buriy/python-readability/issues/16/events", "html_url": "https://github.com/buriy/python-readability/issues/16", "id": 4151845, "node_id": "MDU6SXNzdWU0MTUxODQ1", "number": 16, "title": "0.2.4 uninstallable .egg uploaded to pypi", "user": {"login": "mitechie", "id": 75915, "node_id": "MDQ6VXNlcjc1OTE1", "avatar_url": "https://avatars1.githubusercontent.com/u/75915?v=4", "gravatar_id": "", "url": "https://api.github.com/users/mitechie", "html_url": "https://github.com/mitechie", "followers_url": "https://api.github.com/users/mitechie/followers", "following_url": "https://api.github.com/users/mitechie/following{/other_user}", "gists_url": "https://api.github.com/users/mitechie/gists{/gist_id}", "starred_url": "https://api.github.com/users/mitechie/starred{/owner}{/repo}", "subscriptions_url": "https://api.github.com/users/mitechie/subscriptions", "organizations_url": "https://api.github.com/users/mitechie/orgs", "repos_url": "https://api.github.com/users/mitechie/repos", "events_url": "https://api.github.com/users/mitechie/events{/privacy}", "received_events_url": "https://api.github.com/users/mitechie/received_events", "type": "User", "site_admin": false}, "labels": [], "state": "closed", "locked": false, "assignee": null, "assignees": [], "milestone": null, "comments": 11, "created_at": "2012-04-17T12:27:11Z", "updated_at": "2012-08-30T03:11:45Z", "closed_at": "2012-08-30T03:11:45Z", "author_association": "COLLABORATOR", "active_lock_reason": null, "body": "The latest package isn't installable from pypi as it's a .egg. Previous versions appear to have been .zip files. \n\nI've always just uploaded with setup.py sdist upload. I'm not sure how this was setup. \n", "performed_via_github_app": null, "score": 1.0}, {"url": "https://api.github.com/repos/buriy/python-readability/issues/13", "repository_url": "https://api.github.com/repos/buriy/python-readability", "labels_url": "https://api.github.com/repos/buriy/python-readability/issues/13/labels{/name}", "comments_url": "https://api.github.com/repos/buriy/python-readability/issues/13/comments", "events_url": "https://api.github.com/repos/buriy/python-readability/issues/13/events", "html_url": "https://github.com/buriy/python-readability/issues/13", "id": 4030132, "node_id": "MDU6SXNzdWU0MDMwMTMy", "number": 13, "title": "processed html has self closed body tag", "user": {"login": "mitechie", "id": 75915, "node_id": "MDQ6VXNlcjc1OTE1", "avatar_url": "https://avatars1.githubusercontent.com/u/75915?v=4", "gravatar_id": "", "url": "https://api.github.com/users/mitechie", "html_url": "https://github.com/mitechie", "followers_url": "https://api.github.com/users/mitechie/followers", "following_url": "https://api.github.com/users/mitechie/following{/other_user}", "gists_url": "https://api.github.com/users/mitechie/gists{/gist_id}", "starred_url": "https://api.github.com/users/mitechie/starred{/owner}{/repo}", "subscriptions_url": "https://api.github.com/users/mitechie/subscriptions", "organizations_url": "https://api.github.com/users/mitechie/orgs", "repos_url": "https://api.github.com/users/mitechie/repos", "events_url": "https://api.github.com/users/mitechie/events{/privacy}", "received_events_url": "https://api.github.com/users/mitechie/received_events", "type": "User", "site_admin": false}, "labels": [], "state": "closed", "locked": false, "assignee": null, "assignees": [], "milestone": null, "comments": 2, "created_at": "2012-04-09T15:09:07Z", "updated_at": "2012-04-17T11:28:28Z", "closed_at": "2012-04-17T11:28:28Z", "author_association": "COLLABORATOR", "active_lock_reason": null, "body": "In testing it out I find that the body tag in the processed html is <body/> and not real open/close tags?\n\nI'm using the 0.2.3 from pypi and you can see it here for instance:\n\nview-source:http://readable.bmark.us/view/http%3A%2F%2Fcnnsi.com%2Fbaseball%2Fmlb%2Fgameflash%2F2012%2F04%2F08%2F40523_recap.html%3Fsct%3Dhp_t2_a2%26eref%3Dsihp\n", "performed_via_github_app": null, "score": 1.0}, {"url": "https://api.github.com/repos/buriy/python-readability/issues/12", "repository_url": "https://api.github.com/repos/buriy/python-readability", "labels_url": "https://api.github.com/repos/buriy/python-readability/issues/12/labels{/name}", "comments_url": "https://api.github.com/repos/buriy/python-readability/issues/12/comments", "events_url": "https://api.github.com/repos/buriy/python-readability/issues/12/events", "html_url": "https://github.com/buriy/python-readability/issues/12", "id": 3791233, "node_id": "MDU6SXNzdWUzNzkxMjMz", "number": 12, "title": "Errors in processing  slashdot pages", "user": {"login": "andrebask", "id": 344195, "node_id": "MDQ6VXNlcjM0NDE5NQ==", "avatar_url": "https://avatars2.githubusercontent.com/u/344195?v=4", "gravatar_id": "", "url": "https://api.github.com/users/andrebask", "html_url": "https://github.com/andrebask", "followers_url": "https://api.github.com/users/andrebask/followers", "following_url": "https://api.github.com/users/andrebask/following{/other_user}", "gists_url": "https://api.github.com/users/andrebask/gists{/gist_id}", "starred_url": "https://api.github.com/users/andrebask/starred{/owner}{/repo}", "subscriptions_url": "https://api.github.com/users/andrebask/subscriptions", "organizations_url": "https://api.github.com/users/andrebask/orgs", "repos_url": "https://api.github.com/users/andrebask/repos", "events_url": "https://api.github.com/users/andrebask/events{/privacy}", "received_events_url": "https://api.github.com/users/andrebask/received_events", "type": "User", "site_admin": false}, "labels": [], "state": "closed", "locked": false, "assignee": null, "assignees": [], "milestone": null, "comments": 2, "created_at": "2012-03-24T09:22:15Z", "updated_at": "2013-10-09T20:03:51Z", "closed_at": "2013-10-09T20:03:51Z", "author_association": "NONE", "active_lock_reason": null, "body": "I noticed that there are some problems in processing pages from slashdot.org, for example this page:\nhttp://developers.slashdot.org/story/12/03/22/2149251/gcc-turns-25?utm_source=feedburner&utm_medium=feed&utm_campaign=Feed%3A+Slashdot%2FslashdotDevelopers+%28Slashdot%3A+Developers%29\nOne of the comments is shown instead of the body.\n\nWith this other page python-readability works well:\nhttp://developers.slashdot.org/story/12/03/19/1458206/mystery-of-duqu-programming-language-solved?utm_source=feedburner&utm_medium=feed&utm_campaign=Feed%3A+Slashdot%2FslashdotDevelopers+%28Slashdot%3A+Developers%29\n\nThe same problem is present in the javascript version of readability.\n", "performed_via_github_app": null, "score": 1.0}, {"url": "https://api.github.com/repos/buriy/python-readability/issues/8", "repository_url": "https://api.github.com/repos/buriy/python-readability", "labels_url": "https://api.github.com/repos/buriy/python-readability/issues/8/labels{/name}", "comments_url": "https://api.github.com/repos/buriy/python-readability/issues/8/comments", "events_url": "https://api.github.com/repos/buriy/python-readability/issues/8/events", "html_url": "https://github.com/buriy/python-readability/issues/8", "id": 2532773, "node_id": "MDU6SXNzdWUyNTMyNzcz", "number": 8, "title": "Remove logging configuration when used in library mode.", "user": {"login": "buriy", "id": 21124, "node_id": "MDQ6VXNlcjIxMTI0", "avatar_url": "https://avatars1.githubusercontent.com/u/21124?v=4", "gravatar_id": "", "url": "https://api.github.com/users/buriy", "html_url": "https://github.com/buriy", "followers_url": "https://api.github.com/users/buriy/followers", "following_url": "https://api.github.com/users/buriy/following{/other_user}", "gists_url": "https://api.github.com/users/buriy/gists{/gist_id}", "starred_url": "https://api.github.com/users/buriy/starred{/owner}{/repo}", "subscriptions_url": "https://api.github.com/users/buriy/subscriptions", "organizations_url": "https://api.github.com/users/buriy/orgs", "repos_url": "https://api.github.com/users/buriy/repos", "events_url": "https://api.github.com/users/buriy/events{/privacy}", "received_events_url": "https://api.github.com/users/buriy/received_events", "type": "User", "site_admin": false}, "labels": [], "state": "closed", "locked": false, "assignee": null, "assignees": [], "milestone": null, "comments": 1, "created_at": "2011-12-13T04:24:25Z", "updated_at": "2013-10-09T20:03:05Z", "closed_at": "2013-10-09T20:03:05Z", "author_association": "OWNER", "active_lock_reason": null, "body": "Remove logging configuration when used in library mode.\nImprove logging (add prefix)\n", "performed_via_github_app": null, "score": 1.0}, {"url": "https://api.github.com/repos/buriy/python-readability/issues/7", "repository_url": "https://api.github.com/repos/buriy/python-readability", "labels_url": "https://api.github.com/repos/buriy/python-readability/issues/7/labels{/name}", "comments_url": "https://api.github.com/repos/buriy/python-readability/issues/7/comments", "events_url": "https://api.github.com/repos/buriy/python-readability/issues/7/events", "html_url": "https://github.com/buriy/python-readability/issues/7", "id": 2053132, "node_id": "MDU6SXNzdWUyMDUzMTMy", "number": 7, "title": "Rename this package to python-readability-lxml", "user": {"login": "buriy", "id": 21124, "node_id": "MDQ6VXNlcjIxMTI0", "avatar_url": "https://avatars1.githubusercontent.com/u/21124?v=4", "gravatar_id": "", "url": "https://api.github.com/users/buriy", "html_url": "https://github.com/buriy", "followers_url": "https://api.github.com/users/buriy/followers", "following_url": "https://api.github.com/users/buriy/following{/other_user}", "gists_url": "https://api.github.com/users/buriy/gists{/gist_id}", "starred_url": "https://api.github.com/users/buriy/starred{/owner}{/repo}", "subscriptions_url": "https://api.github.com/users/buriy/subscriptions", "organizations_url": "https://api.github.com/users/buriy/orgs", "repos_url": "https://api.github.com/users/buriy/repos", "events_url": "https://api.github.com/users/buriy/events{/privacy}", "received_events_url": "https://api.github.com/users/buriy/received_events", "type": "User", "site_admin": false}, "labels": [], "state": "closed", "locked": false, "assignee": null, "assignees": [], "milestone": null, "comments": 0, "created_at": "2011-10-26T04:17:34Z", "updated_at": "2013-10-09T20:04:02Z", "closed_at": "2013-10-09T20:04:02Z", "author_association": "OWNER", "active_lock_reason": null, "body": "", "performed_via_github_app": null, "score": 1.0}, {"url": "https://api.github.com/repos/buriy/python-readability/issues/6", "repository_url": "https://api.github.com/repos/buriy/python-readability", "labels_url": "https://api.github.com/repos/buriy/python-readability/issues/6/labels{/name}", "comments_url": "https://api.github.com/repos/buriy/python-readability/issues/6/comments", "events_url": "https://api.github.com/repos/buriy/python-readability/issues/6/events", "html_url": "https://github.com/buriy/python-readability/issues/6", "id": 2053128, "node_id": "MDU6SXNzdWUyMDUzMTI4", "number": 6, "title": "Merge David's branch at https://github.com/dcramer/decruft", "user": {"login": "buriy", "id": 21124, "node_id": "MDQ6VXNlcjIxMTI0", "avatar_url": "https://avatars1.githubusercontent.com/u/21124?v=4", "gravatar_id": "", "url": "https://api.github.com/users/buriy", "html_url": "https://github.com/buriy", "followers_url": "https://api.github.com/users/buriy/followers", "following_url": "https://api.github.com/users/buriy/following{/other_user}", "gists_url": "https://api.github.com/users/buriy/gists{/gist_id}", "starred_url": "https://api.github.com/users/buriy/starred{/owner}{/repo}", "subscriptions_url": "https://api.github.com/users/buriy/subscriptions", "organizations_url": "https://api.github.com/users/buriy/orgs", "repos_url": "https://api.github.com/users/buriy/repos", "events_url": "https://api.github.com/users/buriy/events{/privacy}", "received_events_url": "https://api.github.com/users/buriy/received_events", "type": "User", "site_admin": false}, "labels": [], "state": "closed", "locked": false, "assignee": null, "assignees": [], "milestone": null, "comments": 0, "created_at": "2011-10-26T04:16:34Z", "updated_at": "2015-07-27T05:29:19Z", "closed_at": "2015-07-27T05:29:19Z", "author_association": "OWNER", "active_lock_reason": null, "body": "", "performed_via_github_app": null, "score": 1.0}, {"url": "https://api.github.com/repos/buriy/python-readability/issues/5", "repository_url": "https://api.github.com/repos/buriy/python-readability", "labels_url": "https://api.github.com/repos/buriy/python-readability/issues/5/labels{/name}", "comments_url": "https://api.github.com/repos/buriy/python-readability/issues/5/comments", "events_url": "https://api.github.com/repos/buriy/python-readability/issues/5/events", "html_url": "https://github.com/buriy/python-readability/issues/5", "id": 2053121, "node_id": "MDU6SXNzdWUyMDUzMTIx", "number": 5, "title": "Merge Jerry's branch at https://github.com/jcharum/lxml-readability", "user": {"login": "buriy", "id": 21124, "node_id": "MDQ6VXNlcjIxMTI0", "avatar_url": "https://avatars1.githubusercontent.com/u/21124?v=4", "gravatar_id": "", "url": "https://api.github.com/users/buriy", "html_url": "https://github.com/buriy", "followers_url": "https://api.github.com/users/buriy/followers", "following_url": "https://api.github.com/users/buriy/following{/other_user}", "gists_url": "https://api.github.com/users/buriy/gists{/gist_id}", "starred_url": "https://api.github.com/users/buriy/starred{/owner}{/repo}", "subscriptions_url": "https://api.github.com/users/buriy/subscriptions", "organizations_url": "https://api.github.com/users/buriy/orgs", "repos_url": "https://api.github.com/users/buriy/repos", "events_url": "https://api.github.com/users/buriy/events{/privacy}", "received_events_url": "https://api.github.com/users/buriy/received_events", "type": "User", "site_admin": false}, "labels": [], "state": "closed", "locked": false, "assignee": null, "assignees": [], "milestone": null, "comments": 2, "created_at": "2011-10-26T04:16:12Z", "updated_at": "2015-07-27T05:28:48Z", "closed_at": "2015-07-27T05:28:48Z", "author_association": "OWNER", "active_lock_reason": null, "body": "", "performed_via_github_app": null, "score": 1.0}, {"url": "https://api.github.com/repos/buriy/python-readability/issues/4", "repository_url": "https://api.github.com/repos/buriy/python-readability", "labels_url": "https://api.github.com/repos/buriy/python-readability/issues/4/labels{/name}", "comments_url": "https://api.github.com/repos/buriy/python-readability/issues/4/comments", "events_url": "https://api.github.com/repos/buriy/python-readability/issues/4/events", "html_url": "https://github.com/buriy/python-readability/issues/4", "id": 2052266, "node_id": "MDU6SXNzdWUyMDUyMjY2", "number": 4, "title": "Update to latest readability", "user": {"login": "cmhamill", "id": 1100029, "node_id": "MDQ6VXNlcjExMDAwMjk=", "avatar_url": "https://avatars3.githubusercontent.com/u/1100029?v=4", "gravatar_id": "", "url": "https://api.github.com/users/cmhamill", "html_url": "https://github.com/cmhamill", "followers_url": "https://api.github.com/users/cmhamill/followers", "following_url": "https://api.github.com/users/cmhamill/following{/other_user}", "gists_url": "https://api.github.com/users/cmhamill/gists{/gist_id}", "starred_url": "https://api.github.com/users/cmhamill/starred{/owner}{/repo}", "subscriptions_url": "https://api.github.com/users/cmhamill/subscriptions", "organizations_url": "https://api.github.com/users/cmhamill/orgs", "repos_url": "https://api.github.com/users/cmhamill/repos", "events_url": "https://api.github.com/users/cmhamill/events{/privacy}", "received_events_url": "https://api.github.com/users/cmhamill/received_events", "type": "User", "site_admin": false}, "labels": [], "state": "closed", "locked": false, "assignee": null, "assignees": [], "milestone": null, "comments": 1, "created_at": "2011-10-26T01:14:46Z", "updated_at": "2011-10-26T04:15:13Z", "closed_at": "2011-10-26T04:15:13Z", "author_association": "NONE", "active_lock_reason": null, "body": "The latest version of [arc90's Readability](http://blog.arc90.com/2010/08/02/readability-updated-to-support-multi-page-articles/) supports fetching multiple pages of an article and returning a stitched-together page.\n\nAny chance that change might propagate into `python-readability`?\n", "performed_via_github_app": null, "score": 1.0}, {"url": "https://api.github.com/repos/buriy/python-readability/issues/3", "repository_url": "https://api.github.com/repos/buriy/python-readability", "labels_url": "https://api.github.com/repos/buriy/python-readability/issues/3/labels{/name}", "comments_url": "https://api.github.com/repos/buriy/python-readability/issues/3/comments", "events_url": "https://api.github.com/repos/buriy/python-readability/issues/3/events", "html_url": "https://github.com/buriy/python-readability/issues/3", "id": 1459294, "node_id": "MDU6SXNzdWUxNDU5Mjk0", "number": 3, "title": "chardet requirement in setup.py un-installs newer versions of chardet", "user": {"login": "saidimu", "id": 468077, "node_id": "MDQ6VXNlcjQ2ODA3Nw==", "avatar_url": "https://avatars2.githubusercontent.com/u/468077?v=4", "gravatar_id": "", "url": "https://api.github.com/users/saidimu", "html_url": "https://github.com/saidimu", "followers_url": "https://api.github.com/users/saidimu/followers", "following_url": "https://api.github.com/users/saidimu/following{/other_user}", "gists_url": "https://api.github.com/users/saidimu/gists{/gist_id}", "starred_url": "https://api.github.com/users/saidimu/starred{/owner}{/repo}", "subscriptions_url": "https://api.github.com/users/saidimu/subscriptions", "organizations_url": "https://api.github.com/users/saidimu/orgs", "repos_url": "https://api.github.com/users/saidimu/repos", "events_url": "https://api.github.com/users/saidimu/events{/privacy}", "received_events_url": "https://api.github.com/users/saidimu/received_events", "type": "User", "site_admin": false}, "labels": [], "state": "closed", "locked": false, "assignee": {"login": "buriy", "id": 21124, "node_id": "MDQ6VXNlcjIxMTI0", "avatar_url": "https://avatars1.githubusercontent.com/u/21124?v=4", "gravatar_id": "", "url": "https://api.github.com/users/buriy", "html_url": "https://github.com/buriy", "followers_url": "https://api.github.com/users/buriy/followers", "following_url": "https://api.github.com/users/buriy/following{/other_user}", "gists_url": "https://api.github.com/users/buriy/gists{/gist_id}", "starred_url": "https://api.github.com/users/buriy/starred{/owner}{/repo}", "subscriptions_url": "https://api.github.com/users/buriy/subscriptions", "organizations_url": "https://api.github.com/users/buriy/orgs", "repos_url": "https://api.github.com/users/buriy/repos", "events_url": "https://api.github.com/users/buriy/events{/privacy}", "received_events_url": "https://api.github.com/users/buriy/received_events", "type": "User", "site_admin": false}, "assignees": [{"login": "buriy", "id": 21124, "node_id": "MDQ6VXNlcjIxMTI0", "avatar_url": "https://avatars1.githubusercontent.com/u/21124?v=4", "gravatar_id": "", "url": "https://api.github.com/users/buriy", "html_url": "https://github.com/buriy", "followers_url": "https://api.github.com/users/buriy/followers", "following_url": "https://api.github.com/users/buriy/following{/other_user}", "gists_url": "https://api.github.com/users/buriy/gists{/gist_id}", "starred_url": "https://api.github.com/users/buriy/starred{/owner}{/repo}", "subscriptions_url": "https://api.github.com/users/buriy/subscriptions", "organizations_url": "https://api.github.com/users/buriy/orgs", "repos_url": "https://api.github.com/users/buriy/repos", "events_url": "https://api.github.com/users/buriy/events{/privacy}", "received_events_url": "https://api.github.com/users/buriy/received_events", "type": "User", "site_admin": false}], "milestone": null, "comments": 1, "created_at": "2011-08-22T16:47:54Z", "updated_at": "2011-09-04T15:12:25Z", "closed_at": "2011-09-04T15:12:25Z", "author_association": "NONE", "active_lock_reason": null, "body": "setup.py requires chardet from pypi http://pypi.python.org/pypi/chardet (version 1.01) but un-installs any later version of chardet not from pypi (version 2.01 from http://chardet.feedparser.org/download/)\n\nIs there a way to leave intact newer versions of chardet _not_ from pypi?\n", "performed_via_github_app": null, "score": 1.0}, {"url": "https://api.github.com/repos/buriy/python-readability/issues/2", "repository_url": "https://api.github.com/repos/buriy/python-readability", "labels_url": "https://api.github.com/repos/buriy/python-readability/issues/2/labels{/name}", "comments_url": "https://api.github.com/repos/buriy/python-readability/issues/2/comments", "events_url": "https://api.github.com/repos/buriy/python-readability/issues/2/events", "html_url": "https://github.com/buriy/python-readability/issues/2", "id": 1286104, "node_id": "MDU6SXNzdWUxMjg2MTA0", "number": 2, "title": "Please tag commits which correspond to the releases on PyPI", "user": {"login": "gjastrab", "id": 15297, "node_id": "MDQ6VXNlcjE1Mjk3", "avatar_url": "https://avatars0.githubusercontent.com/u/15297?v=4", "gravatar_id": "", "url": "https://api.github.com/users/gjastrab", "html_url": "https://github.com/gjastrab", "followers_url": "https://api.github.com/users/gjastrab/followers", "following_url": "https://api.github.com/users/gjastrab/following{/other_user}", "gists_url": "https://api.github.com/users/gjastrab/gists{/gist_id}", "starred_url": "https://api.github.com/users/gjastrab/starred{/owner}{/repo}", "subscriptions_url": "https://api.github.com/users/gjastrab/subscriptions", "organizations_url": "https://api.github.com/users/gjastrab/orgs", "repos_url": "https://api.github.com/users/gjastrab/repos", "events_url": "https://api.github.com/users/gjastrab/events{/privacy}", "received_events_url": "https://api.github.com/users/gjastrab/received_events", "type": "User", "site_admin": false}, "labels": [], "state": "closed", "locked": false, "assignee": {"login": "buriy", "id": 21124, "node_id": "MDQ6VXNlcjIxMTI0", "avatar_url": "https://avatars1.githubusercontent.com/u/21124?v=4", "gravatar_id": "", "url": "https://api.github.com/users/buriy", "html_url": "https://github.com/buriy", "followers_url": "https://api.github.com/users/buriy/followers", "following_url": "https://api.github.com/users/buriy/following{/other_user}", "gists_url": "https://api.github.com/users/buriy/gists{/gist_id}", "starred_url": "https://api.github.com/users/buriy/starred{/owner}{/repo}", "subscriptions_url": "https://api.github.com/users/buriy/subscriptions", "organizations_url": "https://api.github.com/users/buriy/orgs", "repos_url": "https://api.github.com/users/buriy/repos", "events_url": "https://api.github.com/users/buriy/events{/privacy}", "received_events_url": "https://api.github.com/users/buriy/received_events", "type": "User", "site_admin": false}, "assignees": [{"login": "buriy", "id": 21124, "node_id": "MDQ6VXNlcjIxMTI0", "avatar_url": "https://avatars1.githubusercontent.com/u/21124?v=4", "gravatar_id": "", "url": "https://api.github.com/users/buriy", "html_url": "https://github.com/buriy", "followers_url": "https://api.github.com/users/buriy/followers", "following_url": "https://api.github.com/users/buriy/following{/other_user}", "gists_url": "https://api.github.com/users/buriy/gists{/gist_id}", "starred_url": "https://api.github.com/users/buriy/starred{/owner}{/repo}", "subscriptions_url": "https://api.github.com/users/buriy/subscriptions", "organizations_url": "https://api.github.com/users/buriy/orgs", "repos_url": "https://api.github.com/users/buriy/repos", "events_url": "https://api.github.com/users/buriy/events{/privacy}", "received_events_url": "https://api.github.com/users/buriy/received_events", "type": "User", "site_admin": false}], "milestone": null, "comments": 3, "created_at": "2011-07-26T02:02:39Z", "updated_at": "2011-07-26T19:08:30Z", "closed_at": "2011-07-26T06:47:27Z", "author_association": "NONE", "active_lock_reason": null, "body": "Keep the tags in git inline with the releases on PyPI please.  Thanks\n", "performed_via_github_app": null, "score": 1.0}]}